; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 22 2021 16:50:55 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAFT0ABUNXB65:
	dc.w DATAFT0ABUNXB65_0-DATAFT0ABUNXB65
DATAFT0ABUNXB65_0: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
	even