; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 15 2018 04:02:04 GMT-0700 (Pacific Daylight Time)
; ================================================================================

DATAY4YT03U38I:
	dc.w DATAY4YT03U38I_0-DATAY4YT03U38I
DATAY4YT03U38I_0: dc.b $2
	dc.b $FC, $0, $0, $0, $F8
	dc.b $FC, $0, $0, $1, $0
	even