; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Mar 27 2018 22:08:29 GMT-0400 (Eastern Daylight Time)
; ================================================================================

Sonic_Map:
	dc.w $0, Sonic_Map_1-Sonic_Map
	dc.w Sonic_Map_2-Sonic_Map, Sonic_Map_3-Sonic_Map
	dc.w Sonic_Map_4-Sonic_Map, Sonic_Map_5-Sonic_Map
	dc.w Sonic_Map_6-Sonic_Map, Sonic_Map_7-Sonic_Map
	dc.w Sonic_Map_8-Sonic_Map, Sonic_Map_9-Sonic_Map
	dc.w Sonic_Map_A-Sonic_Map, Sonic_Map_B-Sonic_Map
	dc.w Sonic_Map_C-Sonic_Map, Sonic_Map_D-Sonic_Map
	dc.w Sonic_Map_E-Sonic_Map, Sonic_Map_F-Sonic_Map
	dc.w Sonic_Map_10-Sonic_Map, Sonic_Map_11-Sonic_Map
	dc.w Sonic_Map_12-Sonic_Map, Sonic_Map_13-Sonic_Map
	dc.w Sonic_Map_14-Sonic_Map, Sonic_Map_15-Sonic_Map
	dc.w Sonic_Map_16-Sonic_Map, Sonic_Map_17-Sonic_Map
	dc.w Sonic_Map_18-Sonic_Map, Sonic_Map_19-Sonic_Map
	dc.w Sonic_Map_1A-Sonic_Map, Sonic_Map_1B-Sonic_Map
	dc.w Sonic_Map_1C-Sonic_Map, Sonic_Map_1D-Sonic_Map
	dc.w Sonic_Map_1E-Sonic_Map, Sonic_Map_1F-Sonic_Map
	dc.w Sonic_Map_20-Sonic_Map, Sonic_Map_21-Sonic_Map
	dc.w Sonic_Map_22-Sonic_Map, Sonic_Map_23-Sonic_Map
	dc.w Sonic_Map_24-Sonic_Map, Sonic_Map_25-Sonic_Map
	dc.w Sonic_Map_26-Sonic_Map, Sonic_Map_27-Sonic_Map
	dc.w Sonic_Map_28-Sonic_Map, Sonic_Map_29-Sonic_Map
	dc.w Sonic_Map_2A-Sonic_Map, Sonic_Map_2B-Sonic_Map
	dc.w Sonic_Map_2C-Sonic_Map, Sonic_Map_2D-Sonic_Map
	dc.w Sonic_Map_2E-Sonic_Map, Sonic_Map_2F-Sonic_Map
	dc.w Sonic_Map_30-Sonic_Map, Sonic_Map_31-Sonic_Map
	dc.w Sonic_Map_32-Sonic_Map, Sonic_Map_33-Sonic_Map
	dc.w Sonic_Map_34-Sonic_Map, Sonic_Map_35-Sonic_Map
	dc.w Sonic_Map_36-Sonic_Map, Sonic_Map_37-Sonic_Map
	dc.w Sonic_Map_38-Sonic_Map, Sonic_Map_39-Sonic_Map
	dc.w Sonic_Map_3A-Sonic_Map, Sonic_Map_3B-Sonic_Map
	dc.w Sonic_Map_3C-Sonic_Map, Sonic_Map_3D-Sonic_Map
	dc.w Sonic_Map_3E-Sonic_Map, Sonic_Map_3F-Sonic_Map
	dc.w Sonic_Map_40-Sonic_Map, Sonic_Map_41-Sonic_Map
	dc.w Sonic_Map_42-Sonic_Map, Sonic_Map_43-Sonic_Map
	dc.w Sonic_Map_44-Sonic_Map, Sonic_Map_45-Sonic_Map
	dc.w Sonic_Map_46-Sonic_Map, Sonic_Map_47-Sonic_Map
	dc.w Sonic_Map_48-Sonic_Map, Sonic_Map_49-Sonic_Map
	dc.w Sonic_Map_4A-Sonic_Map, Sonic_Map_4B-Sonic_Map
	dc.w Sonic_Map_4C-Sonic_Map, Sonic_Map_4D-Sonic_Map
	dc.w Sonic_Map_4E-Sonic_Map, Sonic_Map_4F-Sonic_Map
	dc.w Sonic_Map_50-Sonic_Map, Sonic_Map_51-Sonic_Map
	dc.w Sonic_Map_52-Sonic_Map, Sonic_Map_53-Sonic_Map
	dc.w Sonic_Map_54-Sonic_Map, Sonic_Map_55-Sonic_Map
	dc.w Sonic_Map_56-Sonic_Map, Sonic_Map_57-Sonic_Map
	dc.w Sonic_Map_58-Sonic_Map, Sonic_Map_59-Sonic_Map
	dc.w Sonic_Map_5A-Sonic_Map, Sonic_Map_5B-Sonic_Map
	dc.w Sonic_Map_5C-Sonic_Map, Sonic_Map_5D-Sonic_Map
	dc.w Sonic_Map_5E-Sonic_Map, Sonic_Map_5F-Sonic_Map
	dc.w Sonic_Map_60-Sonic_Map, Sonic_Map_61-Sonic_Map
	dc.w Sonic_Map_62-Sonic_Map, Sonic_Map_63-Sonic_Map
	dc.w Sonic_Map_64-Sonic_Map, Sonic_Map_65-Sonic_Map
	dc.w Sonic_Map_66-Sonic_Map, Sonic_Map_67-Sonic_Map
	dc.w Sonic_Map_68-Sonic_Map, Sonic_Map_69-Sonic_Map
	dc.w Sonic_Map_6A-Sonic_Map, Sonic_Map_6B-Sonic_Map
	dc.w Sonic_Map_6C-Sonic_Map, Sonic_Map_6D-Sonic_Map
	dc.w Sonic_Map_6E-Sonic_Map, Sonic_Map_6F-Sonic_Map
Sonic_Map_1: dc.b $3
	dc.b $EE, $D, $0, $0, $F0
	dc.b $FE, $8, $0, $8, $F0
	dc.b $6, $9, $0, $B, $F8
Sonic_Map_2: dc.b $2
	dc.b $EF, $B, $0, $0, $F0
	dc.b $F, $8, $0, $C, $F8
Sonic_Map_3: dc.b $2
	dc.b $EF, $B, $0, $0, $F0
	dc.b $F, $8, $0, $C, $F8
Sonic_Map_4: dc.b $3
	dc.b $EF, $B, $0, $0, $F0
	dc.b $7, $1, $0, $C, $8
	dc.b $F, $4, $0, $E, $F8
Sonic_Map_5: dc.b $3
	dc.b $F0, $E, $0, $0, $EB
	dc.b $8, $9, $0, $C, $F3
	dc.b $10, $0, $0, $12, $B
Sonic_Map_6: dc.b $4
	dc.b $ED, $F, $0, $0, $EF
	dc.b $FD, $1, $0, $10, $F
	dc.b $D, $0, $0, $12, $EF
	dc.b $D, $0, $0, $13, $7
Sonic_Map_7: dc.b $2
	dc.b $EE, $F, $0, $0, $F3
	dc.b $E, $8, $0, $10, $FB
Sonic_Map_8: dc.b $2
	dc.b $EF, $D, $0, $0, $F1
	dc.b $FF, $A, $0, $8, $F1
Sonic_Map_9: dc.b $4
	dc.b $ED, $B, $0, $0, $F7
	dc.b $F5, $3, $0, $C, $EF
	dc.b $FD, $1, $0, $10, $F
	dc.b $D, $8, $0, $12, $F7
Sonic_Map_A: dc.b $2
	dc.b $EE, $F, $0, $0, $EE
	dc.b $E, $4, $0, $10, $FE
Sonic_Map_B: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
Sonic_Map_C: dc.b $4
	dc.b $ED, $E, $0, $0, $EE
	dc.b $ED, $2, $0, $C, $E
	dc.b $5, $5, $0, $F, $F6
	dc.b $15, $0, $0, $13, $FE
Sonic_Map_D: dc.b $5
	dc.b $EE, $E, $0, $0, $EE
	dc.b $F6, $2, $0, $C, $E
	dc.b $FE, $0, $0, $F, $16
	dc.b $6, $8, $0, $10, $F6
	dc.b $E, $0, $0, $13, $FE
Sonic_Map_E: dc.b $4
	dc.b $ED, $A, $0, $0, $F1
	dc.b $FD, $5, $0, $9, $9
	dc.b $5, $4, $0, $D, $F9
	dc.b $D, $4, $0, $F, $1
Sonic_Map_F: dc.b $4
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $6, $0, $C, $8
	dc.b $C, $8, $0, $12, $F0
	dc.b $14, $4, $0, $15, $F8
Sonic_Map_10: dc.b $4
	dc.b $EE, $E, $0, $0, $EE
	dc.b $FE, $1, $0, $C, $E
	dc.b $6, $8, $0, $E, $F6
	dc.b $E, $4, $0, $11, $F6
Sonic_Map_11: dc.b $4
	dc.b $EF, $E, $0, $0, $EF
	dc.b $FF, $1, $0, $C, $F
	dc.b $7, $8, $0, $E, $F7
	dc.b $F, $4, $0, $11, $FF
Sonic_Map_12: dc.b $4
	dc.b $ED, $F, $0, $0, $ED
	dc.b $ED, $1, $0, $10, $D
	dc.b $5, $1, $0, $12, $D
	dc.b $D, $8, $0, $14, $F5
Sonic_Map_13: dc.b $2
	dc.b $EE, $F, $0, $0, $EE
	dc.b $EE, $2, $0, $10, $E
Sonic_Map_14: dc.b $3
	dc.b $F4, $E, $0, $0, $EF
	dc.b $F4, $2, $0, $C, $F
	dc.b $C, $0, $0, $F, $F7
Sonic_Map_15: dc.b $4
	dc.b $F0, $F, $0, $0, $ED
	dc.b $F0, $1, $0, $10, $D
	dc.b $8, $0, $0, $12, $D
	dc.b $10, $0, $0, $13, $FD
Sonic_Map_16: dc.b $4
	dc.b $F5, $E, $0, $0, $EE
	dc.b $F5, $1, $0, $C, $E
	dc.b $D, $0, $0, $E, $F6
	dc.b $D, $0, $0, $F, $6
Sonic_Map_17: dc.b $2
	dc.b $F2, $F, $0, $0, $EF
	dc.b $F2, $3, $0, $10, $F
Sonic_Map_18: dc.b $5
	dc.b $EC, $B, $0, $0, $ED
	dc.b $F4, $5, $0, $C, $5
	dc.b $FC, $0, $0, $10, $15
	dc.b $4, $0, $0, $11, $5
	dc.b $C, $8, $0, $12, $ED
Sonic_Map_19: dc.b $3
	dc.b $EA, $B, $0, $0, $F8
	dc.b $F2, $3, $0, $C, $F0
	dc.b $A, $4, $0, $10, $F8
Sonic_Map_1A: dc.b $5
	dc.b $ED, $9, $0, $0, $FE
	dc.b $F5, $6, $0, $6, $EE
	dc.b $FD, $4, $0, $C, $FE
	dc.b $5, $0, $0, $E, $FE
	dc.b $D, $0, $0, $F, $F6
Sonic_Map_1B: dc.b $5
	dc.b $EC, $B, $0, $0, $F2
	dc.b $F4, $3, $0, $C, $EA
	dc.b $F4, $5, $0, $10, $A
	dc.b $4, $0, $0, $14, $A
	dc.b $C, $4, $0, $15, $F2
Sonic_Map_1C: dc.b $4
	dc.b $ED, $7, $0, $0, $FF
	dc.b $F5, $7, $0, $8, $EF
	dc.b $F5, $1, $0, $10, $F
	dc.b $D, $0, $0, $12, $FF
Sonic_Map_1D: dc.b $5
	dc.b $E9, $3, $0, $0, $0
	dc.b $F1, $7, $0, $4, $F0
	dc.b $F1, $5, $0, $C, $8
	dc.b $1, $0, $0, $10, $8
	dc.b $9, $0, $0, $11, $0
Sonic_Map_1E: dc.b $4
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $F8, $1, $0, $10, $11
	dc.b $10, $8, $0, $12, $F9
Sonic_Map_1F: dc.b $4
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $F8, $1, $0, $10, $11
	dc.b $10, $8, $0, $12, $F9
Sonic_Map_20: dc.b $2
	dc.b $F0, $F, $0, $0, $F2
	dc.b $10, $8, $0, $10, $F2
Sonic_Map_21: dc.b $4
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $F8, $1, $0, $10, $11
	dc.b $10, $8, $0, $12, $F9
Sonic_Map_22: dc.b $3
	dc.b $EE, $F, $0, $0, $F4
	dc.b $FE, $1, $0, $10, $14
	dc.b $E, $8, $0, $12, $FC
Sonic_Map_23: dc.b $3
	dc.b $EE, $F, $0, $0, $F4
	dc.b $FE, $1, $0, $10, $14
	dc.b $E, $C, $0, $12, $F4
Sonic_Map_24: dc.b $3
	dc.b $EE, $F, $0, $0, $F3
	dc.b $FE, $1, $0, $10, $13
	dc.b $E, $8, $0, $12, $FB
Sonic_Map_25: dc.b $2
	dc.b $EE, $F, $0, $0, $F4
	dc.b $E, $C, $0, $10, $F4
Sonic_Map_26: dc.b $3
	dc.b $F2, $F, $0, $0, $F0
	dc.b $F2, $3, $0, $10, $10
	dc.b $12, $4, $0, $14, $0
Sonic_Map_27: dc.b $4
	dc.b $F2, $E, $0, $0, $F0
	dc.b $F2, $3, $0, $C, $10
	dc.b $A, $8, $0, $10, $F8
	dc.b $12, $4, $0, $13, $0
Sonic_Map_28: dc.b $2
	dc.b $F2, $F, $0, $0, $F0
	dc.b $FA, $2, $0, $10, $10
Sonic_Map_29: dc.b $4
	dc.b $F2, $E, $0, $0, $F0
	dc.b $F2, $3, $0, $C, $10
	dc.b $A, $8, $0, $10, $F8
	dc.b $12, $4, $0, $13, $0
Sonic_Map_2A: dc.b $4
	dc.b $EB, $F, $0, $0, $F6
	dc.b $F3, $2, $0, $10, $EE
	dc.b $F3, $1, $0, $13, $16
	dc.b $B, $4, $0, $15, $F6
Sonic_Map_2B: dc.b $4
	dc.b $EB, $F, $0, $0, $EE
	dc.b $EB, $3, $0, $10, $E
	dc.b $FB, $0, $0, $14, $16
	dc.b $B, $0, $0, $15, $F6
Sonic_Map_2C: dc.b $3
	dc.b $EC, $F, $0, $0, $EE
	dc.b $EC, $2, $0, $10, $E
	dc.b $C, $0, $0, $13, $F6
Sonic_Map_2D: dc.b $3
	dc.b $EB, $F, $0, $0, $EE
	dc.b $EB, $3, $0, $10, $E
	dc.b $B, $0, $0, $14, $F6
Sonic_Map_2E: dc.b $1
	dc.b $F1, $F, $0, $0, $F2
Sonic_Map_2F: dc.b $1
	dc.b $F2, $F, $0, $0, $F1
Sonic_Map_30: dc.b $2
	dc.b $F1, $B, $0, $0, $F4
	dc.b $F9, $2, $0, $C, $C
Sonic_Map_31: dc.b $2
	dc.b $F2, $E, $0, $0, $F1
	dc.b $A, $8, $0, $C, $F1
Sonic_Map_32: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Sonic_Map_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
Sonic_Map_34: dc.b $3
	dc.b $F0, $A, $0, $0, $F8
	dc.b $F8, $2, $0, $9, $F0
	dc.b $8, $4, $0, $C, $F8
Sonic_Map_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
Sonic_Map_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $2, $0, $9, $8
	dc.b $8, $4, $0, $C, $F8
Sonic_Map_37: dc.b $3
	dc.b $F2, $F, $0, $0, $EE
	dc.b $FA, $2, $0, $10, $E
	dc.b $12, $0, $0, $13, $6
Sonic_Map_38: dc.b $3
	dc.b $F2, $F, $0, $0, $EF
	dc.b $2, $1, $0, $10, $F
	dc.b $12, $0, $0, $12, $7
Sonic_Map_39: dc.b $2
	dc.b $F8, $E, $0, $0, $F6
	dc.b $10, $8, $0, $C, $F6
Sonic_Map_3A: dc.b $4
	dc.b $ED, $B, $0, $0, $EA
	dc.b $F5, $3, $0, $C, $E2
	dc.b $FD, $1, $0, $10, $2
	dc.b $D, $8, $0, $12, $EA
Sonic_Map_3B: dc.b $2
	dc.b $EE, $F, $0, $0, $E4
	dc.b $E, $8, $0, $10, $EC
Sonic_Map_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FF
	dc.b $FC, $5, $0, $8, $EF
	dc.b $4, $8, $0, $C, $FF
Sonic_Map_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $F4, $5, $0, $8, $A
	dc.b $4, $C, $0, $C, $F2
Sonic_Map_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $1, $0, $8, $4
	dc.b $4, $8, $0, $A, $EC
Sonic_Map_3F: dc.b $3
	dc.b $F4, $E, $0, $0, $F8
	dc.b $F4, $1, $0, $C, $18
	dc.b $FC, $1, $0, $E, $F0
Sonic_Map_40: dc.b $2
	dc.b $EB, $E, $0, $0, $EB
	dc.b $3, $A, $0, $C, $F3
Sonic_Map_41: dc.b $3
	dc.b $F7, $E, $0, $0, $E6
	dc.b $F7, $2, $0, $C, $6
	dc.b $FF, $5, $0, $F, $E
Sonic_Map_42: dc.b $3
	dc.b $F7, $E, $0, $0, $E6
	dc.b $F7, $2, $0, $C, $6
	dc.b $FF, $5, $0, $F, $E
Sonic_Map_43: dc.b $3
	dc.b $E9, $F, $0, $0, $F1
	dc.b $9, $8, $0, $10, $F9
	dc.b $11, $4, $0, $13, $F9
Sonic_Map_44: dc.b $5
	dc.b $E9, $D, $0, $0, $F1
	dc.b $E9, $0, $0, $8, $11
	dc.b $F9, $9, $0, $9, $F1
	dc.b $1, $1, $0, $F, $9
	dc.b $9, $5, $0, $11, $F9
Sonic_Map_45: dc.b $2
	dc.b $F3, $F, $0, $0, $EF
	dc.b $13, $C, $0, $10, $EF
Sonic_Map_46: dc.b $3
	dc.b $F3, $D, $0, $0, $F2
	dc.b $3, $8, $0, $8, $F2
	dc.b $B, $5, $0, $B, $F2
Sonic_Map_47: dc.b $2
	dc.b $F3, $E, $0, $0, $EF
	dc.b $B, $9, $0, $C, $EF
Sonic_Map_48: dc.b $3
	dc.b $F3, $D, $0, $0, $F2
	dc.b $3, $8, $0, $8, $F2
	dc.b $B, $5, $0, $B, $F2
Sonic_Map_49: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $FD, $2, $0, $C, $8
	dc.b $D, $8, $0, $F, $F0
Sonic_Map_4A: dc.b $3
	dc.b $EB, $B, $0, $0, $F2
	dc.b $B, $8, $0, $C, $F2
	dc.b $13, $4, $0, $F, $FA
Sonic_Map_4B: dc.b $5
	dc.b $E8, $E, $0, $0, $F2
	dc.b $E8, $1, $0, $C, $12
	dc.b $0, $6, $0, $E, $FA
	dc.b $8, $1, $0, $14, $F2
	dc.b $8, $1, $0, $16, $A
Sonic_Map_4C: dc.b $3
	dc.b $EC, $F, $0, $0, $F3
	dc.b $F4, $0, $0, $10, $13
	dc.b $C, $C, $0, $11, $F3
Sonic_Map_4D: dc.b $3
	dc.b $EA, $F, $0, $0, $F3
	dc.b $F2, $0, $0, $10, $13
	dc.b $A, $C, $0, $11, $F3
Sonic_Map_4E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $8
	dc.b $C, $8, $0, $10, $F0
Sonic_Map_4F: dc.b $3
	dc.b $EE, $B, $0, $0, $F2
	dc.b $F6, $2, $0, $C, $A
	dc.b $E, $8, $0, $F, $F2
Sonic_Map_50: dc.b $2
	dc.b $F2, $7, $0, $0, $F5
	dc.b $FA, $2, $0, $8, $5
Sonic_Map_51: dc.b $1
	dc.b $F7, $6, $0, $0, $F9
Sonic_Map_52: dc.b $1
	dc.b $FB, $1, $0, $0, $FC
Sonic_Map_53: dc.b $3
	dc.b $F3, $D, $0, $0, $E3
	dc.b $FB, $5, $0, $8, $3
	dc.b $3, $8, $0, $C, $EB
Sonic_Map_54: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $1, $0, $8, $F4
	dc.b $4, $8, $0, $A, $FC
Sonic_Map_55: dc.b $3
	dc.b $F4, $E, $0, $0, $EE
	dc.b $FC, $1, $0, $C, $E
	dc.b $C, $8, $0, $E, $F6
Sonic_Map_56: dc.b $4
	dc.b $EC, $B, $0, $0, $F1
	dc.b $F4, $3, $0, $C, $9
	dc.b $FC, $1, $0, $10, $11
	dc.b $C, $8, $0, $12, $F1
Sonic_Map_57: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $FA, $2, $0, $C, $C
	dc.b $A, $8, $0, $F, $F4
Sonic_Map_58: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_59: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_5A: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_5B: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_5C: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_5D: dc.b $2
	dc.b $F9, $E, $0, $0, $F3
	dc.b $11, $8, $0, $C, $F3
Sonic_Map_5E: dc.b $3
	dc.b $EF, $F, $0, $0, $F0
	dc.b $FF, $2, $0, $10, $E8
	dc.b $F, $C, $0, $13, $F0
Sonic_Map_5F: dc.b $3
	dc.b $F0, $F, $0, $0, $F0
	dc.b $0, $1, $0, $10, $E8
	dc.b $10, $C, $0, $12, $F0
Sonic_Map_60: dc.b $3
	dc.b $EF, $F, $0, $0, $F0
	dc.b $FF, $2, $0, $10, $E8
	dc.b $F, $C, $0, $13, $F0
Sonic_Map_61: dc.b $3
	dc.b $F0, $F, $0, $0, $F0
	dc.b $0, $1, $0, $10, $E8
	dc.b $10, $8, $0, $12, $F8
Sonic_Map_62: dc.b $4
	dc.b $F4, $F, $0, $0, $EA
	dc.b $4, $1, $0, $10, $A
	dc.b $14, $8, $0, $12, $EA
	dc.b $1C, $4, $0, $15, $EA
Sonic_Map_63: dc.b $4
	dc.b $F5, $F, $0, $0, $EB
	dc.b $5, $1, $0, $10, $B
	dc.b $15, $C, $0, $12, $EB
	dc.b $1D, $4, $0, $16, $EB
Sonic_Map_64: dc.b $4
	dc.b $F4, $F, $0, $0, $EA
	dc.b $FC, $2, $0, $10, $A
	dc.b $14, $C, $0, $13, $EA
	dc.b $1C, $8, $0, $17, $EA
Sonic_Map_65: dc.b $4
	dc.b $F5, $F, $0, $0, $EB
	dc.b $5, $1, $0, $10, $B
	dc.b $15, $C, $0, $12, $EB
	dc.b $1D, $0, $0, $16, $EB
Sonic_Map_66: dc.b $3
	dc.b $F6, $F, $0, $0, $EF
	dc.b $F6, $3, $0, $10, $F
	dc.b $16, $8, $0, $14, $FF
Sonic_Map_67: dc.b $3
	dc.b $F6, $F, $0, $0, $F0
	dc.b $F6, $3, $0, $10, $10
	dc.b $16, $4, $0, $14, $0
Sonic_Map_68: dc.b $3
	dc.b $F6, $F, $0, $0, $EF
	dc.b $F6, $3, $0, $10, $F
	dc.b $16, $8, $0, $14, $FF
Sonic_Map_69: dc.b $3
	dc.b $F6, $F, $0, $0, $F0
	dc.b $F6, $2, $0, $10, $10
	dc.b $16, $4, $0, $13, $0
Sonic_Map_6A: dc.b $5
	dc.b $EE, $7, $0, $0, $0
	dc.b $F6, $7, $0, $8, $F0
	dc.b $F6, $3, $0, $10, $10
	dc.b $FE, $1, $0, $14, $18
	dc.b $E, $4, $0, $16, $0
Sonic_Map_6B: dc.b $4
	dc.b $F1, $F, $0, $0, $F1
	dc.b $F1, $3, $0, $10, $11
	dc.b $1, $1, $0, $14, $19
	dc.b $11, $4, $0, $16, $F9
Sonic_Map_6C: dc.b $4
	dc.b $EF, $F, $0, $0, $F0
	dc.b $EF, $3, $0, $10, $10
	dc.b $FF, $1, $0, $14, $18
	dc.b $F, $C, $0, $16, $F0
Sonic_Map_6D: dc.b $4
	dc.b $F1, $F, $0, $0, $F1
	dc.b $F1, $3, $0, $10, $11
	dc.b $9, $0, $0, $14, $19
	dc.b $11, $4, $0, $15, $F9
Sonic_Map_6E: dc.b $3
	dc.b $E5, $E, $0, $0, $F4
	dc.b $ED, $1, $0, $C, $EC
	dc.b $FD, $6, $0, $E, $F4
Sonic_Map_6F: dc.b $3
	dc.b $E5, $E, $0, $0, $EF
	dc.b $FD, $6, $0, $C, $F7
	dc.b $ED, $1, $0, $12, $F
	even