; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed May 23 2018 20:48:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAT0N1PMJ2B8L:
	dc.w $0, DATAT0N1PMJ2B8L_1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_10-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_11-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_12-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_13-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_14-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_15-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_16-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_17-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_18-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_19-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_1A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_1B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_1C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_1D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_1E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_1F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_20-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_21-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_22-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_23-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_24-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_25-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_26-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_27-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_28-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_29-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_2A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_2B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_2C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_2D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_2E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_2F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_30-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_31-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_32-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_33-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_34-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_35-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_36-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_37-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_38-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_39-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_3A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_3B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_3C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_3D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_3E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_3F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_40-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_41-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_42-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_43-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_44-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_45-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_46-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_47-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_48-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_49-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_4A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_4B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_4C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_4D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_4E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_4F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_50-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_51-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_52-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_53-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_54-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_55-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_56-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_57-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_58-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_59-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_5A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_5B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_5C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_5D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_5E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_5F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_60-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_61-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_62-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_63-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_64-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_65-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_66-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_67-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_68-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_69-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_6A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_6B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_6C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_6D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_6E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_6F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_70-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_71-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_72-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_73-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_74-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_75-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_76-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_77-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_78-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_79-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_7A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_7B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_7C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_7D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_7E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_7F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_80-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_81-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_82-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_83-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_84-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_85-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_86-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_87-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_88-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_89-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_8A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_8B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_8C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_8D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_8E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_8F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_90-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_91-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_92-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_93-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_94-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_95-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_96-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_97-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_98-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_99-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_9A-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_9B-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_9C-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_9D-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_9E-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_9F-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_A1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_A3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_A5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_A7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_A8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_A9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_AA-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_AB-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_AC-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_AD-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_AE-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_AF-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_B0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_B2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_B4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_B6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_B8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_B9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_BA-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_BB-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_BC-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_BD-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_BE-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_BF-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_C1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_C3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_C5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_C7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_C8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_C9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_CA-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_CB-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_CC-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_CD-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_CE-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_CF-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_D0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_D2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_D4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_D6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_D8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_D9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_DA-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_DB-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_DC-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_DD-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_DE-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_DF-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_E1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_E3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_E5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_E7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_E8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_E9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_EA-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_EB-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_EC-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_ED-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_EE-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_EF-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_F0-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F1-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_F2-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F3-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_F4-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F5-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_F6-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F7-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_F8-DATAT0N1PMJ2B8L, DATAT0N1PMJ2B8L_F9-DATAT0N1PMJ2B8L
	dc.w DATAT0N1PMJ2B8L_FA-DATAT0N1PMJ2B8L
DATAT0N1PMJ2B8L_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $FC, $2, $0, $F, $EB
	dc.b $C, $4, $0, $12, $3
DATAT0N1PMJ2B8L_2: dc.b $3
	dc.b $EC, $4, $0, $0, $F9
	dc.b $F4, $F, $0, $2, $F1
	dc.b $FC, $2, $0, $12, $E9
DATAT0N1PMJ2B8L_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $D, $0, $6, $EC
	dc.b $C, $4, $0, $E, $F4
DATAT0N1PMJ2B8L_4: dc.b $2
	dc.b $EC, $9, $0, $0, $F5
	dc.b $FC, $E, $0, $6, $ED
DATAT0N1PMJ2B8L_5: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $FC, $1, $0, $F, $EB
	dc.b $C, $C, $0, $11, $EB
DATAT0N1PMJ2B8L_6: dc.b $4
	dc.b $EA, $4, $0, $0, $FA
	dc.b $F2, $8, $0, $2, $F2
	dc.b $FA, $E, $0, $5, $F2
	dc.b $2, $1, $0, $11, $EA
DATAT0N1PMJ2B8L_7: dc.b $3
	dc.b $EC, $4, $0, $0, $F7
	dc.b $F4, $E, $0, $2, $EF
	dc.b $C, $8, $0, $E, $EF
DATAT0N1PMJ2B8L_8: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $8, $0, $3, $F3
	dc.b $FC, $E, $0, $6, $F3
	dc.b $FC, $0, $0, $12, $EB
DATAT0N1PMJ2B8L_9: dc.b $3
	dc.b $ED, $E, $0, $0, $F2
	dc.b $5, $8, $0, $C, $F2
	dc.b $D, $5, $0, $F, $FA
DATAT0N1PMJ2B8L_A: dc.b $3
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F7, $2, $0, $10, $10
	dc.b $F, $4, $0, $13, $F8
DATAT0N1PMJ2B8L_B: dc.b $3
	dc.b $EF, $8, $0, $0, $F4
	dc.b $F7, $E, $0, $3, $F4
	dc.b $F, $0, $0, $F, $4
DATAT0N1PMJ2B8L_C: dc.b $4
	dc.b $F0, $8, $0, $0, $F3
	dc.b $F8, $D, $0, $3, $F3
	dc.b $8, $8, $0, $B, $F3
	dc.b $10, $4, $0, $E, $FB
DATAT0N1PMJ2B8L_D: dc.b $3
	dc.b $EB, $F, $0, $0, $F2
	dc.b $B, $4, $0, $10, $F2
	dc.b $13, $4, $0, $12, $FA
DATAT0N1PMJ2B8L_E: dc.b $2
	dc.b $EF, $E, $0, $0, $F5
	dc.b $7, $5, $0, $C, $F5
DATAT0N1PMJ2B8L_F: dc.b $3
	dc.b $F0, $8, $0, $0, $F5
	dc.b $F8, $E, $0, $3, $F5
	dc.b $10, $0, $0, $F, $5
DATAT0N1PMJ2B8L_10: dc.b $3
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $E, $0, $3, $F3
	dc.b $C, $4, $0, $F, $FB
DATAT0N1PMJ2B8L_11: dc.b $4
	dc.b $EE, $C, $0, $0, $F4
	dc.b $F6, $E, $0, $4, $EC
	dc.b $F6, $0, $0, $10, $C
	dc.b $E, $8, $0, $11, $FC
DATAT0N1PMJ2B8L_12: dc.b $4
	dc.b $F0, $C, $0, $0, $F4
	dc.b $F8, $D, $0, $4, $EC
	dc.b $F8, $0, $0, $C, $C
	dc.b $8, $D, $0, $D, $F4
DATAT0N1PMJ2B8L_13: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $FD, $1, $0, $C, $C
	dc.b $D, $4, $0, $E, $FC
DATAT0N1PMJ2B8L_14: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAT0N1PMJ2B8L_15: dc.b $4
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $E, $0, $3, $EC
	dc.b $F5, $0, $0, $F, $C
	dc.b $D, $8, $0, $10, $FC
DATAT0N1PMJ2B8L_16: dc.b $4
	dc.b $EF, $8, $0, $0, $FB
	dc.b $F7, $E, $0, $3, $F3
	dc.b $F7, $1, $0, $F, $EB
	dc.b $F, $4, $0, $11, $3
DATAT0N1PMJ2B8L_17: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $E, $0, $3, $F4
	dc.b $FA, $1, $0, $F, $EC
DATAT0N1PMJ2B8L_18: dc.b $4
	dc.b $EE, $4, $0, $0, $FC
	dc.b $F6, $E, $0, $2, $EC
	dc.b $F6, $2, $0, $E, $C
	dc.b $E, $0, $0, $11, $FC
DATAT0N1PMJ2B8L_19: dc.b $3
	dc.b $F0, $8, $0, $0, $EE
	dc.b $F8, $E, $0, $3, $EE
	dc.b $F8, $5, $0, $F, $E
DATAT0N1PMJ2B8L_1A: dc.b $3
	dc.b $E9, $8, $0, $0, $F7
	dc.b $F1, $F, $0, $3, $EF
	dc.b $F9, $1, $0, $13, $F
DATAT0N1PMJ2B8L_1B: dc.b $3
	dc.b $EB, $8, $0, $0, $F8
	dc.b $F3, $E, $0, $3, $F0
	dc.b $F3, $0, $0, $F, $10
DATAT0N1PMJ2B8L_1C: dc.b $3
	dc.b $EC, $4, $0, $0, $FA
	dc.b $F4, $E, $0, $2, $F2
	dc.b $F4, $1, $0, $E, $12
DATAT0N1PMJ2B8L_1D: dc.b $2
	dc.b $EE, $F, $0, $0, $EB
	dc.b $F6, $6, $0, $10, $B
DATAT0N1PMJ2B8L_1E: dc.b $2
	dc.b $ED, $B, $0, $0, $EE
	dc.b $FD, $5, $0, $C, $6
DATAT0N1PMJ2B8L_1F: dc.b $3
	dc.b $EB, $8, $0, $0, $F9
	dc.b $F3, $E, $0, $3, $F1
	dc.b $F3, $0, $0, $F, $11
DATAT0N1PMJ2B8L_20: dc.b $3
	dc.b $EC, $8, $0, $0, $F6
	dc.b $F4, $E, $0, $3, $EE
	dc.b $F4, $1, $0, $F, $E
DATAT0N1PMJ2B8L_21: dc.b $2
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $F, $0, $3, $EC
DATAT0N1PMJ2B8L_22: dc.b $2
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $F, $0, $3, $EC
DATAT0N1PMJ2B8L_23: dc.b $2
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $F, $0, $3, $EC
DATAT0N1PMJ2B8L_24: dc.b $2
	dc.b $ED, $8, $0, $0, $F4
	dc.b $F5, $F, $0, $3, $EC
DATAT0N1PMJ2B8L_25: dc.b $4
	dc.b $F0, $8, $0, $0, $EE
	dc.b $F8, $E, $0, $3, $EE
	dc.b $0, $1, $0, $F, $E
	dc.b $10, $8, $0, $11, $F6
DATAT0N1PMJ2B8L_26: dc.b $4
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $E, $0, $3, $F1
	dc.b $F8, $1, $0, $F, $E9
	dc.b $10, $8, $0, $11, $F9
DATAT0N1PMJ2B8L_27: dc.b $3
	dc.b $F1, $8, $0, $0, $EF
	dc.b $F9, $D, $0, $3, $EF
	dc.b $9, $9, $0, $B, $F7
DATAT0N1PMJ2B8L_28: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $F, $0, $3, $F1
	dc.b $F8, $1, $0, $13, $E9
DATAT0N1PMJ2B8L_29: dc.b $2
	dc.b $F4, $2, $0, $0, $EA
	dc.b $F4, $F, $0, $3, $F2
DATAT0N1PMJ2B8L_2A: dc.b $2
	dc.b $F4, $2, $0, $0, $EB
	dc.b $F4, $F, $0, $3, $F3
DATAT0N1PMJ2B8L_2B: dc.b $2
	dc.b $F4, $2, $0, $0, $EA
	dc.b $F4, $F, $0, $3, $F2
DATAT0N1PMJ2B8L_2C: dc.b $2
	dc.b $F4, $2, $0, $0, $EB
	dc.b $F4, $F, $0, $3, $F3
DATAT0N1PMJ2B8L_2D: dc.b $4
	dc.b $EB, $4, $0, $0, $0
	dc.b $F3, $E, $0, $2, $F8
	dc.b $FB, $1, $0, $E, $F0
	dc.b $B, $C, $0, $10, $F0
DATAT0N1PMJ2B8L_2E: dc.b $4
	dc.b $F0, $C, $0, $0, $F8
	dc.b $F8, $E, $0, $4, $F0
	dc.b $F8, $1, $0, $10, $10
	dc.b $10, $4, $0, $12, $F8
DATAT0N1PMJ2B8L_2F: dc.b $3
	dc.b $F2, $E, $0, $0, $F9
	dc.b $FA, $1, $0, $C, $F1
	dc.b $A, $8, $0, $E, $F1
DATAT0N1PMJ2B8L_30: dc.b $3
	dc.b $F0, $F, $0, $0, $F8
	dc.b $F8, $2, $0, $10, $F0
	dc.b $10, $4, $0, $13, $F8
DATAT0N1PMJ2B8L_31: dc.b $4
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $D, $0, $3, $F3
	dc.b $4, $8, $0, $B, $F3
	dc.b $C, $4, $0, $E, $FB
DATAT0N1PMJ2B8L_32: dc.b $2
	dc.b $EA, $4, $0, $0, $FB
	dc.b $F2, $F, $0, $2, $F3
DATAT0N1PMJ2B8L_33: dc.b $3
	dc.b $ED, $9, $0, $0, $F4
	dc.b $FD, $C, $0, $6, $F4
	dc.b $5, $8, $0, $A, $F4
DATAT0N1PMJ2B8L_34: dc.b $3
	dc.b $EF, $8, $0, $0, $F3
	dc.b $F7, $E, $0, $3, $F3
	dc.b $F, $0, $0, $F, $3
DATAT0N1PMJ2B8L_35: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $D, $0, $3, $F4
	dc.b $A, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_36: dc.b $3
	dc.b $EC, $4, $0, $0, $FB
	dc.b $F4, $D, $0, $2, $F3
	dc.b $4, $9, $0, $A, $F3
DATAT0N1PMJ2B8L_37: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $8, $0, $10, $F2
DATAT0N1PMJ2B8L_38: dc.b $3
	dc.b $EB, $5, $0, $0, $FB
	dc.b $FB, $C, $0, $4, $F3
	dc.b $3, $9, $0, $8, $F3
DATAT0N1PMJ2B8L_39: dc.b $2
	dc.b $F2, $E, $0, $0, $F3
	dc.b $A, $8, $0, $C, $F3
DATAT0N1PMJ2B8L_3A: dc.b $2
	dc.b $F4, $D, $0, $0, $F3
	dc.b $4, $8, $0, $8, $F3
DATAT0N1PMJ2B8L_3B: dc.b $3
	dc.b $F3, $D, $0, $0, $F2
	dc.b $3, $8, $0, $8, $F2
	dc.b $B, $C, $0, $B, $F2
DATAT0N1PMJ2B8L_3C: dc.b $2
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $D, $0, $9, $F4
DATAT0N1PMJ2B8L_3D: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAT0N1PMJ2B8L_3E: dc.b $3
	dc.b $F3, $8, $0, $0, $F4
	dc.b $FB, $D, $0, $3, $F4
	dc.b $B, $4, $0, $B, $F4
DATAT0N1PMJ2B8L_3F: dc.b $2
	dc.b $F6, $D, $0, $0, $F4
	dc.b $6, $8, $0, $8, $F4
DATAT0N1PMJ2B8L_40: dc.b $3
	dc.b $F2, $8, $0, $0, $F9
	dc.b $FA, $D, $0, $3, $F1
	dc.b $A, $4, $0, $B, $F9
DATAT0N1PMJ2B8L_41: dc.b $2
	dc.b $EF, $E, $0, $0, $F3
	dc.b $7, $9, $0, $C, $F3
DATAT0N1PMJ2B8L_42: dc.b $4
	dc.b $EC, $C, $0, $0, $F4
	dc.b $F4, $8, $0, $4, $F4
	dc.b $FC, $C, $0, $7, $F4
	dc.b $4, $9, $0, $B, $F4
DATAT0N1PMJ2B8L_43: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
DATAT0N1PMJ2B8L_44: dc.b $1
	dc.b $F0, $F, $0, $0, $F4
DATAT0N1PMJ2B8L_45: dc.b $3
	dc.b $F2, $8, $0, $0, $F4
	dc.b $FA, $D, $0, $3, $F4
	dc.b $A, $0, $0, $B, $FC
DATAT0N1PMJ2B8L_46: dc.b $2
	dc.b $F1, $9, $0, $0, $F3
	dc.b $1, $D, $0, $6, $F3
DATAT0N1PMJ2B8L_47: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $E, $0, $6, $F3
DATAT0N1PMJ2B8L_48: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATAT0N1PMJ2B8L_49: dc.b $3
	dc.b $ED, $F, $0, $0, $F1
	dc.b $F5, $2, $0, $10, $E9
	dc.b $D, $4, $0, $13, $F9
DATAT0N1PMJ2B8L_4A: dc.b $3
	dc.b $F0, $E, $0, $0, $EE
	dc.b $8, $8, $0, $C, $EE
	dc.b $10, $0, $0, $F, $EE
DATAT0N1PMJ2B8L_4B: dc.b $2
	dc.b $F4, $A, $0, $0, $F4
	dc.b $C, $4, $0, $9, $F4
DATAT0N1PMJ2B8L_4C: dc.b $2
	dc.b $F5, $E, $0, $0, $F0
	dc.b $D, $C, $0, $C, $F0
DATAT0N1PMJ2B8L_4D: dc.b $1
	dc.b $F4, $E, $0, $0, $F3
DATAT0N1PMJ2B8L_4E: dc.b $3
	dc.b $ED, $8, $0, $0, $F8
	dc.b $F5, $E, $0, $3, $F0
	dc.b $F5, $1, $0, $F, $10
DATAT0N1PMJ2B8L_4F: dc.b $2
	dc.b $ED, $C, $0, $0, $F6
	dc.b $F5, $E, $0, $4, $EE
DATAT0N1PMJ2B8L_50: dc.b $3
	dc.b $EE, $0, $0, $0, $4
	dc.b $F6, $E, $0, $1, $EC
	dc.b $F6, $1, $0, $D, $C
DATAT0N1PMJ2B8L_51: dc.b $3
	dc.b $EC, $4, $0, $0, $1
	dc.b $F4, $A, $0, $2, $F1
	dc.b $F4, $5, $0, $B, $9
DATAT0N1PMJ2B8L_52: dc.b $3
	dc.b $EF, $4, $0, $0, $F8
	dc.b $F7, $D, $0, $2, $F0
	dc.b $7, $4, $0, $A, $F8
DATAT0N1PMJ2B8L_53: dc.b $3
	dc.b $EE, $8, $0, $0, $F0
	dc.b $F6, $D, $0, $3, $F0
	dc.b $6, $8, $0, $B, $F8
DATAT0N1PMJ2B8L_54: dc.b $2
	dc.b $F0, $E, $0, $0, $F0
	dc.b $8, $8, $0, $C, $F0
DATAT0N1PMJ2B8L_55: dc.b $3
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $A, $0, $7, $F4
DATAT0N1PMJ2B8L_56: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATAT0N1PMJ2B8L_57: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $F3
DATAT0N1PMJ2B8L_58: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAT0N1PMJ2B8L_59: dc.b $3
	dc.b $EC, $8, $0, $0, $F2
	dc.b $F4, $D, $0, $3, $F2
	dc.b $4, $9, $0, $B, $F2
DATAT0N1PMJ2B8L_5A: dc.b $2
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $8, $0, $C, $F2
DATAT0N1PMJ2B8L_5B: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $8, $0, $C, $F3
DATAT0N1PMJ2B8L_5C: dc.b $2
	dc.b $F5, $E, $0, $0, $E3
	dc.b $F5, $A, $0, $C, $3
DATAT0N1PMJ2B8L_5D: dc.b $2
	dc.b $F5, $E, $0, $0, $EA
	dc.b $F5, $2, $0, $C, $A
DATAT0N1PMJ2B8L_5E: dc.b $2
	dc.b $F5, $E, $0, $0, $EA
	dc.b $F5, $2, $0, $C, $A
DATAT0N1PMJ2B8L_5F: dc.b $2
	dc.b $F5, $E, $0, $0, $E4
	dc.b $F5, $A, $0, $C, $4
DATAT0N1PMJ2B8L_60: dc.b $1
	dc.b $F5, $E, $0, $0, $F2
DATAT0N1PMJ2B8L_61: dc.b $1
	dc.b $F5, $E, $0, $0, $E8
DATAT0N1PMJ2B8L_62: dc.b $3
	dc.b $F5, $C, $0, $0, $EF
	dc.b $FD, $D, $0, $4, $E7
	dc.b $FD, $5, $0, $C, $7
DATAT0N1PMJ2B8L_63: dc.b $2
	dc.b $E3, $B, $0, $0, $F5
	dc.b $3, $A, $0, $C, $F5
DATAT0N1PMJ2B8L_64: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAT0N1PMJ2B8L_65: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
DATAT0N1PMJ2B8L_66: dc.b $2
	dc.b $E5, $B, $0, $0, $F5
	dc.b $5, $A, $0, $C, $F5
DATAT0N1PMJ2B8L_67: dc.b $1
	dc.b $F0, $B, $0, $0, $F5
DATAT0N1PMJ2B8L_68: dc.b $1
	dc.b $F5, $B, $0, $0, $F5
DATAT0N1PMJ2B8L_69: dc.b $3
	dc.b $E8, $4, $0, $0, $FB
	dc.b $F0, $9, $0, $2, $F3
	dc.b $0, $D, $0, $8, $F3
DATAT0N1PMJ2B8L_6A: dc.b $2
	dc.b $EF, $A, $0, $0, $F5
	dc.b $7, $4, $0, $9, $FD
DATAT0N1PMJ2B8L_6B: dc.b $2
	dc.b $F5, $8, $0, $0, $F3
	dc.b $FD, $D, $0, $3, $F3
DATAT0N1PMJ2B8L_6C: dc.b $3
	dc.b $EC, $4, $0, $0, $FA
	dc.b $F4, $E, $0, $2, $EA
	dc.b $F4, $1, $0, $E, $A
DATAT0N1PMJ2B8L_6D: dc.b $2
	dc.b $F1, $F, $0, $0, $F2
	dc.b $F9, $2, $0, $10, $EA
DATAT0N1PMJ2B8L_6E: dc.b $3
	dc.b $EE, $0, $0, $0, $FF
	dc.b $F6, $A, $0, $1, $EF
	dc.b $F6, $5, $0, $A, $7
DATAT0N1PMJ2B8L_6F: dc.b $4
	dc.b $EF, $8, $0, $0, $F9
	dc.b $F7, $C, $0, $3, $F1
	dc.b $FF, $8, $0, $7, $F1
	dc.b $7, $C, $0, $A, $F1
DATAT0N1PMJ2B8L_70: dc.b $2
	dc.b $ED, $4, $0, $0, $FE
	dc.b $F5, $A, $0, $2, $F6
DATAT0N1PMJ2B8L_71: dc.b $1
	dc.b $ED, $F, $0, $0, $EF
DATAT0N1PMJ2B8L_72: dc.b $2
	dc.b $EC, $7, $0, $0, $F0
	dc.b $F4, $A, $0, $8, $0
DATAT0N1PMJ2B8L_73: dc.b $3
	dc.b $EF, $4, $0, $0, $FE
	dc.b $F7, $1, $0, $2, $EE
	dc.b $F7, $E, $0, $4, $F6
DATAT0N1PMJ2B8L_74: dc.b $2
	dc.b $F0, $F, $0, $0, $EE
	dc.b $F8, $1, $0, $10, $E
DATAT0N1PMJ2B8L_75: dc.b $2
	dc.b $ED, $0, $0, $0, $FB
	dc.b $F5, $E, $0, $1, $F3
DATAT0N1PMJ2B8L_76: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $E, $0, $3, $F1
	dc.b $F8, $0, $0, $F, $E9
DATAT0N1PMJ2B8L_77: dc.b $2
	dc.b $ED, $4, $0, $0, $F7
	dc.b $F5, $E, $0, $2, $EF
DATAT0N1PMJ2B8L_78: dc.b $3
	dc.b $E6, $C, $0, $0, $F1
	dc.b $EE, $A, $0, $4, $F1
	dc.b $6, $D, $0, $D, $F9
DATAT0N1PMJ2B8L_79: dc.b $4
	dc.b $EC, $8, $0, $0, $E5
	dc.b $F4, $D, $0, $3, $E5
	dc.b $F4, $6, $0, $B, $5
	dc.b $4, $8, $0, $11, $ED
DATAT0N1PMJ2B8L_7A: dc.b $3
	dc.b $F0, $0, $0, $0, $E6
	dc.b $F8, $E, $0, $1, $E6
	dc.b $E8, $7, $0, $D, $6
DATAT0N1PMJ2B8L_7B: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $4, $0, $3, $FC
	dc.b $FC, $8, $0, $5, $F4
	dc.b $4, $E, $0, $8, $EC
DATAT0N1PMJ2B8L_7C: dc.b $3
	dc.b $13, $C, $18, $0, $F0
	dc.b $FB, $A, $18, $4, $F8
	dc.b $EB, $D, $18, $D, $E8
DATAT0N1PMJ2B8L_7D: dc.b $4
	dc.b $E, $8, $18, $0, $3
	dc.b $FE, $D, $18, $3, $FB
	dc.b $F6, $6, $18, $B, $EB
	dc.b $F6, $8, $18, $11, $FB
DATAT0N1PMJ2B8L_7E: dc.b $3
	dc.b $8, $0, $18, $0, $13
	dc.b $F0, $E, $18, $1, $FB
	dc.b $F8, $7, $18, $D, $EB
DATAT0N1PMJ2B8L_7F: dc.b $4
	dc.b $E, $8, $18, $0, $F5
	dc.b $6, $4, $18, $3, $F5
	dc.b $FE, $8, $18, $5, $F5
	dc.b $E6, $E, $18, $8, $F5
DATAT0N1PMJ2B8L_80: dc.b $3
	dc.b $E8, $F, $0, $0, $EE
	dc.b $E8, $0, $0, $10, $E
	dc.b $8, $9, $0, $11, $EE
DATAT0N1PMJ2B8L_81: dc.b $4
	dc.b $E1, $0, $0, $0, $FF
	dc.b $E9, $C, $0, $1, $EF
	dc.b $F1, $B, $0, $5, $EF
	dc.b $11, $8, $0, $11, $EF
DATAT0N1PMJ2B8L_82: dc.b $3
	dc.b $E1, $4, $0, $0, $F4
	dc.b $E9, $E, $0, $2, $F4
	dc.b $1, $A, $0, $E, $F4
DATAT0N1PMJ2B8L_83: dc.b $2
	dc.b $E7, $F, $0, $0, $EE
	dc.b $7, $9, $0, $10, $F6
DATAT0N1PMJ2B8L_84: dc.b $4
	dc.b $E2, $4, $0, $0, $FC
	dc.b $EA, $9, $0, $2, $F4
	dc.b $FA, $C, $0, $8, $F4
	dc.b $2, $A, $0, $C, $F4
DATAT0N1PMJ2B8L_85: dc.b $4
	dc.b $E2, $4, $0, $0, $F4
	dc.b $EA, $C, $0, $2, $F4
	dc.b $F2, $A, $0, $6, $F4
	dc.b $A, $5, $0, $F, $FC
DATAT0N1PMJ2B8L_86: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_87: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_88: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_89: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_8A: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_8B: dc.b $3
	dc.b $F8, $8, $0, $0, $FC
	dc.b $0, $D, $0, $3, $F4
	dc.b $10, $8, $0, $B, $F4
DATAT0N1PMJ2B8L_8C: dc.b $3
	dc.b $EF, $B, $0, $0, $F0
	dc.b $EF, $6, $0, $C, $8
	dc.b $F, $4, $0, $12, $F8
DATAT0N1PMJ2B8L_8D: dc.b $4
	dc.b $EB, $A, $0, $0, $F2
	dc.b $EB, $5, $0, $9, $A
	dc.b $3, $D, $0, $D, $F2
	dc.b $3, $0, $0, $15, $12
DATAT0N1PMJ2B8L_8E: dc.b $3
	dc.b $E8, $4, $0, $0, $F6
	dc.b $F0, $A, $0, $2, $F6
	dc.b $8, $5, $0, $B, $F6
DATAT0N1PMJ2B8L_8F: dc.b $3
	dc.b $F3, $1, $0, $0, $E7
	dc.b $F3, $E, $0, $2, $EF
	dc.b $B, $4, $0, $E, $FF
DATAT0N1PMJ2B8L_90: dc.b $4
	dc.b $E6, $4, $0, $0, $F9
	dc.b $EE, $A, $0, $2, $F1
	dc.b $6, $9, $0, $B, $F9
	dc.b $16, $4, $0, $11, $F9
DATAT0N1PMJ2B8L_91: dc.b $2
	dc.b $E6, $B, $0, $0, $F2
	dc.b $6, $9, $0, $C, $FA
DATAT0N1PMJ2B8L_92: dc.b $3
	dc.b $E6, $A, $0, $0, $F2
	dc.b $FE, $C, $0, $9, $F2
	dc.b $6, $5, $0, $D, $2
DATAT0N1PMJ2B8L_93: dc.b $3
	dc.b $E6, $A, $0, $0, $F2
	dc.b $FE, $C, $0, $9, $F2
	dc.b $6, $4, $0, $D, $2
DATAT0N1PMJ2B8L_94: dc.b $4
	dc.b $E9, $D, $0, $0, $F1
	dc.b $EB, $4, $0, $8, $F4
	dc.b $F3, $B, $0, $A, $F4
	dc.b $13, $8, $0, $16, $F4
DATAT0N1PMJ2B8L_95: dc.b $4
	dc.b $E9, $9, $0, $0, $F4
	dc.b $EB, $4, $0, $6, $F4
	dc.b $F3, $B, $0, $8, $F4
	dc.b $13, $8, $0, $14, $F4
DATAT0N1PMJ2B8L_96: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_97: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_98: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_99: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_9A: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_9B: dc.b $2
	dc.b $F4, $8, $0, $0, $F3
	dc.b $FC, $E, $0, $3, $F3
DATAT0N1PMJ2B8L_9C: dc.b $2
	dc.b $FC, $8, $0, $0, $F5
	dc.b $4, $D, $0, $3, $F5
DATAT0N1PMJ2B8L_9D: dc.b $2
	dc.b $EC, $4, $0, $0, $F8
	dc.b $F4, $F, $0, $2, $F0
DATAT0N1PMJ2B8L_9E: dc.b $4
	dc.b $EC, $8, $0, $0, $EE
	dc.b $F4, $F, $0, $3, $F6
	dc.b $F4, $0, $0, $13, $EE
	dc.b $FC, $5, $0, $14, $E6
DATAT0N1PMJ2B8L_9F: dc.b $4
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $E, $0, $3, $F0
	dc.b $FC, $1, $0, $F, $10
	dc.b $C, $8, $0, $11, $F0
DATAT0N1PMJ2B8L_A0: dc.b $4
	dc.b $EC, $8, $0, $0, $F7
	dc.b $F4, $E, $0, $3, $EF
	dc.b $F4, $6, $0, $F, $F
	dc.b $C, $8, $0, $15, $EF
DATAT0N1PMJ2B8L_A1: dc.b $4
	dc.b $E4, $0, $0, $0, $F6
	dc.b $EC, $E, $0, $1, $EE
	dc.b $EC, $7, $0, $D, $E
	dc.b $4, $9, $0, $15, $EE
DATAT0N1PMJ2B8L_A2: dc.b $4
	dc.b $E8, $E, $0, $0, $F9
	dc.b $F0, $1, $0, $C, $19
	dc.b $0, $4, $0, $E, $F9
	dc.b $8, $9, $0, $10, $F1
DATAT0N1PMJ2B8L_A3: dc.b $4
	dc.b $E6, $0, $0, $0, $FE
	dc.b $EE, $E, $0, $1, $EE
	dc.b $F6, $5, $0, $D, $E
	dc.b $6, $9, $0, $11, $EE
DATAT0N1PMJ2B8L_A4: dc.b $4
	dc.b $F1, $E, $0, $0, $F1
	dc.b $F1, $1, $0, $C, $11
	dc.b $9, $8, $0, $E, $F1
	dc.b $11, $4, $0, $11, $F9
DATAT0N1PMJ2B8L_A5: dc.b $4
	dc.b $E4, $4, $0, $0, $F1
	dc.b $EC, $1, $0, $2, $11
	dc.b $EC, $E, $0, $4, $F1
	dc.b $4, $9, $0, $10, $F1
DATAT0N1PMJ2B8L_A6: dc.b $4
	dc.b $EC, $6, $0, $0, $11
	dc.b $EC, $E, $0, $6, $F1
	dc.b $4, $8, $0, $12, $F9
	dc.b $C, $8, $0, $15, $F1
DATAT0N1PMJ2B8L_A7: dc.b $4
	dc.b $EC, $E, $0, $0, $F6
	dc.b $F4, $1, $0, $C, $16
	dc.b $4, $9, $0, $E, $EE
	dc.b $4, $4, $0, $14, $6
DATAT0N1PMJ2B8L_A8: dc.b $4
	dc.b $EC, $1, $0, $0, $16
	dc.b $EC, $D, $0, $2, $F6
	dc.b $FC, $A, $0, $A, $EE
	dc.b $FC, $5, $0, $13, $6
DATAT0N1PMJ2B8L_A9: dc.b $4
	dc.b $E4, $9, $0, $0, $F9
	dc.b $C, $4, $0, $6, $F9
	dc.b $F4, $E, $0, $8, $E9
	dc.b $F4, $A, $0, $14, $9
DATAT0N1PMJ2B8L_AA: dc.b $4
	dc.b $E4, $4, $0, $0, $3
	dc.b $C, $4, $0, $2, $FB
	dc.b $EC, $F, $0, $4, $FB
	dc.b $F4, $6, $0, $14, $EB
DATAT0N1PMJ2B8L_AB: dc.b $4
	dc.b $EE, $D, $0, $0, $F3
	dc.b $EE, $1, $0, $8, $EB
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATAT0N1PMJ2B8L_AC: dc.b $4
	dc.b $EE, $D, $0, $0, $EB
	dc.b $EE, $1, $0, $8, $B
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATAT0N1PMJ2B8L_AD: dc.b $4
	dc.b $EE, $D, $0, $0, $EB
	dc.b $EE, $1, $0, $8, $B
	dc.b $FE, $9, $0, $A, $F3
	dc.b $E, $C, $0, $10, $F3
DATAT0N1PMJ2B8L_AE: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAT0N1PMJ2B8L_AF: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $0, $0, $C, $6
	dc.b $FC, $9, $0, $D, $6
DATAT0N1PMJ2B8L_B0: dc.b $3
	dc.b $EA, $C, $0, $0, $F4
	dc.b $F2, $F, $0, $4, $EC
	dc.b $F2, $0, $0, $14, $C
DATAT0N1PMJ2B8L_B1: dc.b $2
	dc.b $EC, $8, $0, $0, $F3
	dc.b $F4, $F, $0, $3, $F3
DATAT0N1PMJ2B8L_B2: dc.b $3
	dc.b $EC, $8, $0, $0, $FB
	dc.b $F4, $F, $0, $3, $F3
	dc.b $FC, $2, $0, $13, $13
DATAT0N1PMJ2B8L_B3: dc.b $2
	dc.b $EC, $4, $0, $0, $FC
	dc.b $F4, $F, $0, $2, $F4
DATAT0N1PMJ2B8L_B4: dc.b $3
	dc.b $EC, $8, $0, $0, $FC
	dc.b $F4, $F, $0, $3, $F4
	dc.b $FC, $1, $0, $13, $14
DATAT0N1PMJ2B8L_B5: dc.b $3
	dc.b $E6, $B, $0, $0, $F4
	dc.b $6, $8, $0, $C, $F4
	dc.b $E, $5, $0, $F, $F4
DATAT0N1PMJ2B8L_B6: dc.b $3
	dc.b $E6, $B, $0, $0, $F4
	dc.b $6, $8, $0, $C, $F4
	dc.b $E, $5, $0, $F, $F4
DATAT0N1PMJ2B8L_B7: dc.b $2
	dc.b $EE, $F, $0, $0, $EB
	dc.b $E, $0, $0, $10, $3
DATAT0N1PMJ2B8L_B8: dc.b $1
	dc.b $F0, $F, $0, $0, $EB
DATAT0N1PMJ2B8L_B9: dc.b $2
	dc.b $EC, $F, $0, $0, $EB
	dc.b $C, $4, $0, $10, $FB
DATAT0N1PMJ2B8L_BA: dc.b $3
	dc.b $EC, $8, $0, $0, $EB
	dc.b $F4, $E, $0, $3, $EB
	dc.b $C, $4, $0, $F, $FB
DATAT0N1PMJ2B8L_BB: dc.b $1
	dc.b $EE, $F, $0, $0, $EB
DATAT0N1PMJ2B8L_BC: dc.b $1
	dc.b $EF, $F, $0, $0, $EB
DATAT0N1PMJ2B8L_BD: dc.b $4
	dc.b $EC, $D, $0, $0, $F0
	dc.b $FC, $8, $0, $8, $F0
	dc.b $4, $4, $0, $B, $F8
	dc.b $C, $0, $0, $D, $0
DATAT0N1PMJ2B8L_BE: dc.b $2
	dc.b $EC, $E, $0, $0, $F0
	dc.b $4, $5, $0, $C, $F0
DATAT0N1PMJ2B8L_BF: dc.b $3
	dc.b $EC, $4, $0, $0, $FC
	dc.b $F4, $F, $0, $2, $F4
	dc.b $C, $0, $0, $12, $EC
DATAT0N1PMJ2B8L_C0: dc.b $3
	dc.b $F4, $C, $0, $0, $F0
	dc.b $FC, $D, $0, $4, $E8
	dc.b $FC, $5, $0, $C, $8
DATAT0N1PMJ2B8L_C1: dc.b $2
	dc.b $F4, $E, $0, $0, $F4
	dc.b $FC, $1, $0, $C, $EC
DATAT0N1PMJ2B8L_C2: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAT0N1PMJ2B8L_C3: dc.b $2
	dc.b $F4, $E, $8, $0, $EC
	dc.b $FC, $1, $8, $C, $C
DATAT0N1PMJ2B8L_C4: dc.b $3
	dc.b $F4, $C, $8, $0, $F0
	dc.b $FC, $D, $8, $4, $F8
	dc.b $FC, $5, $8, $C, $E8
DATAT0N1PMJ2B8L_C5: dc.b $2
	dc.b $F4, $E, $0, $0, $EB
	dc.b $F4, $6, $0, $C, $B
DATAT0N1PMJ2B8L_C6: dc.b $3
	dc.b $F4, $C, $0, $0, $F6
	dc.b $FC, $D, $0, $4, $EE
	dc.b $FC, $5, $0, $C, $E
DATAT0N1PMJ2B8L_C7: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
DATAT0N1PMJ2B8L_C8: dc.b $3
	dc.b $F4, $C, $8, $0, $EB
	dc.b $FC, $D, $8, $4, $F3
	dc.b $FC, $5, $8, $C, $E3
DATAT0N1PMJ2B8L_C9: dc.b $2
	dc.b $F4, $E, $8, $0, $F6
	dc.b $F4, $6, $8, $C, $E6
DATAT0N1PMJ2B8L_CA: dc.b $4
	dc.b $EF, $D, $0, $0, $F0
	dc.b $FF, $D, $0, $8, $E8
	dc.b $FF, $5, $0, $10, $8
	dc.b $F, $8, $0, $14, $E8
DATAT0N1PMJ2B8L_CB: dc.b $4
	dc.b $E8, $E, $0, $0, $F0
	dc.b $F8, $0, $0, $C, $E8
	dc.b $0, $C, $0, $D, $E8
	dc.b $8, $5, $0, $11, $F8
DATAT0N1PMJ2B8L_CC: dc.b $4
	dc.b $F3, $4, $0, $0, $FC
	dc.b $FB, $C, $0, $2, $F4
	dc.b $3, $C, $0, $6, $E4
	dc.b $3, $8, $0, $A, $4
DATAT0N1PMJ2B8L_CD: dc.b $3
	dc.b $F4, $8, $0, $0, $F8
	dc.b $FC, $E, $0, $3, $F0
	dc.b $4, $1, $0, $F, $E8
DATAT0N1PMJ2B8L_CE: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $E, $0, $7, $EC
	dc.b $FC, $0, $0, $13, $C
DATAT0N1PMJ2B8L_CF: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $E, $0, $3, $F4
	dc.b $FC, $1, $0, $F, $EC
	dc.b $C, $8, $0, $11, $EC
DATAT0N1PMJ2B8L_D0: dc.b $5
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $0, $0, $7, $EC
	dc.b $FC, $C, $0, $8, $F4
	dc.b $4, $D, $0, $C, $EC
DATAT0N1PMJ2B8L_D1: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $E, $0, $3, $F4
	dc.b $FC, $0, $0, $F, $EC
	dc.b $C, $8, $0, $10, $EC
DATAT0N1PMJ2B8L_D2: dc.b $2
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $C, $0, $C, $F2
DATAT0N1PMJ2B8L_D3: dc.b $2
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $C, $0, $C, $F2
DATAT0N1PMJ2B8L_D4: dc.b $2
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $C, $0, $C, $F2
DATAT0N1PMJ2B8L_D5: dc.b $2
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $E, $0, $6, $F4
DATAT0N1PMJ2B8L_D6: dc.b $2
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $E, $0, $6, $F4
DATAT0N1PMJ2B8L_D7: dc.b $2
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $E, $0, $6, $F4
DATAT0N1PMJ2B8L_D8: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $D, $0, $3, $F4
	dc.b $4, $8, $0, $B, $F4
	dc.b $C, $C, $0, $E, $F4
DATAT0N1PMJ2B8L_D9: dc.b $5
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $C, $0, $3, $F4
	dc.b $FC, $C, $0, $7, $F4
	dc.b $4, $8, $0, $B, $F4
	dc.b $C, $C, $0, $E, $F4
DATAT0N1PMJ2B8L_DA: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $D, $0, $3, $F4
	dc.b $4, $8, $0, $B, $F4
	dc.b $C, $C, $0, $E, $F4
DATAT0N1PMJ2B8L_DB: dc.b $4
	dc.b $EC, $8, $0, $0, $F4
	dc.b $F4, $D, $0, $3, $F4
	dc.b $4, $8, $0, $B, $F4
	dc.b $C, $C, $0, $E, $F4
DATAT0N1PMJ2B8L_DC: dc.b $3
	dc.b $EC, $8, $0, $0, $F6
	dc.b $F4, $D, $0, $3, $F6
	dc.b $4, $9, $0, $B, $F6
DATAT0N1PMJ2B8L_DD: dc.b $3
	dc.b $EC, $A, $0, $0, $F7
	dc.b $F4, $5, $0, $9, $F
	dc.b $4, $9, $0, $D, $F7
DATAT0N1PMJ2B8L_DE: dc.b $4
	dc.b $EC, $E, $0, $0, $F4
	dc.b $F4, $1, $0, $C, $14
	dc.b $4, $8, $0, $E, $F4
	dc.b $C, $C, $0, $11, $F4
DATAT0N1PMJ2B8L_DF: dc.b $3
	dc.b $ED, $9, $0, $0, $F1
	dc.b $FD, $D, $0, $6, $F1
	dc.b $D, $4, $0, $E, $F9
DATAT0N1PMJ2B8L_E0: dc.b $3
	dc.b $F0, $8, $0, $0, $F1
	dc.b $F8, $D, $0, $3, $F1
	dc.b $8, $4, $0, $B, $F9
DATAT0N1PMJ2B8L_E1: dc.b $1
	dc.b $F4, $F, $0, $0, $F0
DATAT0N1PMJ2B8L_E2: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
DATAT0N1PMJ2B8L_E3: dc.b $2
	dc.b $EF, $A, $0, $0, $F4
	dc.b $7, $D, $0, $9, $F4
DATAT0N1PMJ2B8L_E4: dc.b $4
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $8, $0, $2, $F0
	dc.b $F8, $D, $0, $5, $F0
	dc.b $8, $9, $0, $D, $F8
DATAT0N1PMJ2B8L_E5: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $9, $0, $C, $FC
DATAT0N1PMJ2B8L_E6: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $8, $0, $10, $F8
	dc.b $10, $4, $0, $13, $0
DATAT0N1PMJ2B8L_E7: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $4, $0, $C, $FC
	dc.b $10, $8, $0, $E, $F4
DATAT0N1PMJ2B8L_E8: dc.b $4
	dc.b $E8, $9, $0, $0, $F6
	dc.b $F8, $C, $0, $6, $EE
	dc.b $0, $8, $0, $A, $F6
	dc.b $8, $9, $0, $D, $EE
DATAT0N1PMJ2B8L_E9: dc.b $3
	dc.b $E8, $9, $0, $0, $F3
	dc.b $F8, $D, $0, $6, $F3
	dc.b $8, $9, $0, $E, $F3
DATAT0N1PMJ2B8L_EA: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $9, $0, $C, $F4
DATAT0N1PMJ2B8L_EB: dc.b $3
	dc.b $EC, $9, $0, $0, $F4
	dc.b $FC, $C, $0, $6, $F4
	dc.b $4, $9, $0, $A, $F4
DATAT0N1PMJ2B8L_EC: dc.b $3
	dc.b $EC, $C, $0, $0, $E9
	dc.b $F4, $2, $0, $4, $E9
	dc.b $F4, $F, $0, $7, $F1
DATAT0N1PMJ2B8L_ED: dc.b $3
	dc.b $EC, $C, $0, $0, $EA
	dc.b $F4, $F, $0, $4, $EA
	dc.b $F4, $3, $0, $14, $A
DATAT0N1PMJ2B8L_EE: dc.b $3
	dc.b $EC, $C, $0, $0, $EA
	dc.b $F4, $F, $0, $4, $EA
	dc.b $F4, $3, $0, $14, $A
DATAT0N1PMJ2B8L_EF: dc.b $3
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $E, $0, $2, $F0
	dc.b $8, $8, $0, $E, $F0
DATAT0N1PMJ2B8L_F0: dc.b $3
	dc.b $E8, $4, $0, $0, $F8
	dc.b $F0, $E, $0, $2, $F0
	dc.b $8, $4, $0, $E, $F8
DATAT0N1PMJ2B8L_F1: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATAT0N1PMJ2B8L_F2: dc.b $2
	dc.b $EB, $B, $0, $0, $F4
	dc.b $B, $0, $0, $C, $FC
DATAT0N1PMJ2B8L_F3: dc.b $2
	dc.b $E8, $B, $8, $0, $F4
	dc.b $8, $8, $8, $C, $F4
DATAT0N1PMJ2B8L_F4: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $4, $0, $F, $F8
DATAT0N1PMJ2B8L_F5: dc.b $3
	dc.b $EB, $8, $0, $0, $F0
	dc.b $F3, $E, $0, $3, $F0
	dc.b $B, $8, $0, $F, $F0
DATAT0N1PMJ2B8L_F6: dc.b $2
	dc.b $EC, $F, $0, $0, $F0
	dc.b $C, $4, $0, $10, $F8
DATAT0N1PMJ2B8L_F7: dc.b $4
	dc.b $EB, $8, $0, $0, $F8
	dc.b $F3, $D, $0, $3, $F0
	dc.b $3, $8, $0, $B, $F8
	dc.b $B, $4, $0, $E, $F8
DATAT0N1PMJ2B8L_F8: dc.b $3
	dc.b $EC, $A, $0, $0, $F4
	dc.b $4, $4, $0, $9, $FC
	dc.b $C, $4, $0, $B, $F4
DATAT0N1PMJ2B8L_F9: dc.b $4
	dc.b $EB, $8, $8, $0, $F0
	dc.b $F3, $D, $8, $3, $F0
	dc.b $3, $8, $8, $B, $F0
	dc.b $B, $4, $8, $E, $F8
DATAT0N1PMJ2B8L_FA: dc.b $2
	dc.b $EB, $E, $0, $0, $F0
	dc.b $3, $9, $0, $C, $F0
	even