; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 28 2018 11:16:22 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAS32O3PAI9Y:
	dc.w DATAS32O3PAI9Y_0-DATAS32O3PAI9Y
DATAS32O3PAI9Y_0: dc.b $2
	dc.b $F5, $D, $0, $0, $E6
	dc.b $F5, $5, $0, $8, $6
	even