; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 22 2021 19:44:56 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATANRAA9K3M9QL:
	dc.w DATANRAA9K3M9QL_0-DATANRAA9K3M9QL
DATANRAA9K3M9QL_0: dc.b $2
	dc.b $F5, $D, $0, $0, $E6
	dc.b $F5, $5, $0, $8, $6
	even