; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Apr 20 2018 16:40:29 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA1J234NW7PIY:
	dc.w $0, DATA1J234NW7PIY_1-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_2-DATA1J234NW7PIY, DATA1J234NW7PIY_3-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_4-DATA1J234NW7PIY, DATA1J234NW7PIY_5-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_6-DATA1J234NW7PIY, DATA1J234NW7PIY_7-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_8-DATA1J234NW7PIY, DATA1J234NW7PIY_9-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_A-DATA1J234NW7PIY, DATA1J234NW7PIY_B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_C-DATA1J234NW7PIY, DATA1J234NW7PIY_D-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_E-DATA1J234NW7PIY, DATA1J234NW7PIY_F-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_10-DATA1J234NW7PIY, DATA1J234NW7PIY_11-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_12-DATA1J234NW7PIY, DATA1J234NW7PIY_13-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_14-DATA1J234NW7PIY, DATA1J234NW7PIY_15-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_16-DATA1J234NW7PIY, DATA1J234NW7PIY_17-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_18-DATA1J234NW7PIY, DATA1J234NW7PIY_19-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_1A-DATA1J234NW7PIY, DATA1J234NW7PIY_1B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_1C-DATA1J234NW7PIY, DATA1J234NW7PIY_1D-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_1E-DATA1J234NW7PIY, DATA1J234NW7PIY_1F-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_20-DATA1J234NW7PIY, DATA1J234NW7PIY_21-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_22-DATA1J234NW7PIY, DATA1J234NW7PIY_23-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_24-DATA1J234NW7PIY, DATA1J234NW7PIY_25-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_26-DATA1J234NW7PIY, DATA1J234NW7PIY_27-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_28-DATA1J234NW7PIY, DATA1J234NW7PIY_29-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_2A-DATA1J234NW7PIY, DATA1J234NW7PIY_2B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_2C-DATA1J234NW7PIY, DATA1J234NW7PIY_2D-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_2E-DATA1J234NW7PIY, DATA1J234NW7PIY_2F-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_30-DATA1J234NW7PIY, DATA1J234NW7PIY_31-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_32-DATA1J234NW7PIY, DATA1J234NW7PIY_33-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_34-DATA1J234NW7PIY, DATA1J234NW7PIY_35-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_36-DATA1J234NW7PIY, DATA1J234NW7PIY_37-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_38-DATA1J234NW7PIY, DATA1J234NW7PIY_39-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_3A-DATA1J234NW7PIY, DATA1J234NW7PIY_3B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_3C-DATA1J234NW7PIY, DATA1J234NW7PIY_3D-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_3E-DATA1J234NW7PIY, DATA1J234NW7PIY_3F-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_40-DATA1J234NW7PIY, DATA1J234NW7PIY_41-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_42-DATA1J234NW7PIY, DATA1J234NW7PIY_43-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_44-DATA1J234NW7PIY, DATA1J234NW7PIY_45-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_46-DATA1J234NW7PIY, DATA1J234NW7PIY_47-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_48-DATA1J234NW7PIY, DATA1J234NW7PIY_49-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_4A-DATA1J234NW7PIY, DATA1J234NW7PIY_4B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_4C-DATA1J234NW7PIY, DATA1J234NW7PIY_4D-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_4E-DATA1J234NW7PIY, DATA1J234NW7PIY_4F-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_50-DATA1J234NW7PIY, DATA1J234NW7PIY_51-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_52-DATA1J234NW7PIY, DATA1J234NW7PIY_53-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_54-DATA1J234NW7PIY, DATA1J234NW7PIY_55-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_56-DATA1J234NW7PIY, DATA1J234NW7PIY_57-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_58-DATA1J234NW7PIY, DATA1J234NW7PIY_59-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_5A-DATA1J234NW7PIY, DATA1J234NW7PIY_5B-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_5C-DATA1J234NW7PIY, DATA1J234NW7PIY_5D-DATA1J234NW7PIY
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, $0
	dc.w DATA1J234NW7PIY_C8-DATA1J234NW7PIY, DATA1J234NW7PIY_C9-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_CA-DATA1J234NW7PIY, DATA1J234NW7PIY_CB-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_CC-DATA1J234NW7PIY, DATA1J234NW7PIY_CD-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_CE-DATA1J234NW7PIY, DATA1J234NW7PIY_CF-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_D0-DATA1J234NW7PIY, DATA1J234NW7PIY_D1-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_D2-DATA1J234NW7PIY, DATA1J234NW7PIY_D3-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_D4-DATA1J234NW7PIY, DATA1J234NW7PIY_D5-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_D6-DATA1J234NW7PIY, DATA1J234NW7PIY_D7-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_D8-DATA1J234NW7PIY, DATA1J234NW7PIY_D9-DATA1J234NW7PIY
	dc.w DATA1J234NW7PIY_DA-DATA1J234NW7PIY, DATA1J234NW7PIY_DB-DATA1J234NW7PIY
DATA1J234NW7PIY_1: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $F5, $0, $0, $C, $8
	dc.b $D, $8, $0, $D, $F8
DATA1J234NW7PIY_2: dc.b $2
	dc.b $ED, $B, $0, $0, $F1
	dc.b $D, $8, $0, $C, $F1
DATA1J234NW7PIY_3: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATA1J234NW7PIY_4: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATA1J234NW7PIY_5: dc.b $2
	dc.b $EE, $B, $0, $0, $F2
	dc.b $E, $C, $0, $C, $F2
DATA1J234NW7PIY_6: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $C, $0, $C, $F0
DATA1J234NW7PIY_7: dc.b $2
	dc.b $F5, $B, $0, $0, $F1
	dc.b $5, $1, $0, $C, $9
DATA1J234NW7PIY_8: dc.b $2
	dc.b $FC, $A, $0, $0, $E8
	dc.b $4, $5, $0, $9, $0
DATA1J234NW7PIY_9: dc.b $3
	dc.b $FC, $A, $0, $0, $E8
	dc.b $4, $1, $0, $9, $0
	dc.b $C, $0, $0, $B, $8
DATA1J234NW7PIY_A: dc.b $2
	dc.b $F0, $B, $0, $0, $F0
	dc.b $10, $8, $0, $C, $F8
DATA1J234NW7PIY_B: dc.b $3
	dc.b $ED, $B, $0, $0, $F0
	dc.b $F5, $0, $0, $C, $8
	dc.b $D, $8, $0, $D, $F8
DATA1J234NW7PIY_C: dc.b $3
	dc.b $EE, $D, $0, $0, $F0
	dc.b $FE, $9, $0, $8, $F0
	dc.b $E, $8, $0, $E, $F8
DATA1J234NW7PIY_D: dc.b $4
	dc.b $EB, $F, $0, $0, $ED
	dc.b $F3, $3, $0, $10, $D
	dc.b $B, $4, $0, $14, $ED
	dc.b $B, $0, $0, $16, $5
DATA1J234NW7PIY_E: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $F4, $0, $0, $10, $D
	dc.b $4, $1, $0, $11, $D
	dc.b $C, $C, $0, $13, $ED
DATA1J234NW7PIY_F: dc.b $3
	dc.b $ED, $B, $0, $0, $F3
	dc.b $F5, $0, $0, $C, $B
	dc.b $D, $8, $0, $D, $F3
DATA1J234NW7PIY_10: dc.b $2
	dc.b $EC, $F, $0, $0, $F2
	dc.b $C, $C, $0, $10, $F2
DATA1J234NW7PIY_11: dc.b $5
	dc.b $EB, $B, $0, $0, $F6
	dc.b $F3, $3, $0, $C, $EE
	dc.b $FB, $1, $0, $10, $E
	dc.b $B, $0, $0, $12, $F6
	dc.b $B, $0, $0, $13, $6
DATA1J234NW7PIY_12: dc.b $6
	dc.b $EC, $B, $0, $0, $F5
	dc.b $F4, $0, $0, $C, $ED
	dc.b $4, $1, $0, $D, $ED
	dc.b $4, $1, $0, $F, $D
	dc.b $C, $0, $0, $11, $F5
	dc.b $C, $0, $0, $12, $5
DATA1J234NW7PIY_13: dc.b $3
	dc.b $ED, $B, $0, $0, $F3
	dc.b $F5, $0, $0, $C, $B
	dc.b $D, $8, $0, $D, $F3
DATA1J234NW7PIY_14: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $4, $9, $0, $C, $F2
	dc.b $C, $0, $0, $12, $A
DATA1J234NW7PIY_15: dc.b $4
	dc.b $EC, $E, $0, $0, $E9
	dc.b $F4, $1, $0, $C, $9
	dc.b $4, $8, $0, $E, $F1
	dc.b $C, $5, $0, $11, $F9
DATA1J234NW7PIY_16: dc.b $6
	dc.b $ED, $E, $0, $0, $EA
	dc.b $F5, $2, $0, $C, $12
	dc.b $FD, $1, $0, $F, $A
	dc.b $5, $8, $0, $11, $F2
	dc.b $D, $4, $0, $14, $FA
	dc.b $15, $0, $0, $16, $FA
DATA1J234NW7PIY_17: dc.b $3
	dc.b $EE, $E, $0, $0, $EC
	dc.b $6, $C, $0, $C, $F4
	dc.b $E, $4, $0, $10, $4
DATA1J234NW7PIY_18: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $FC, $4, $0, $C, $C
	dc.b $4, $C, $0, $E, $F4
	dc.b $C, $5, $0, $12, $FC
DATA1J234NW7PIY_19: dc.b $4
	dc.b $EB, $F, $0, $0, $EB
	dc.b $F3, $2, $0, $10, $B
	dc.b $B, $8, $0, $13, $F3
	dc.b $13, $4, $0, $16, $FB
DATA1J234NW7PIY_1A: dc.b $4
	dc.b $EC, $E, $0, $0, $EC
	dc.b $F4, $6, $0, $C, $C
	dc.b $4, $8, $0, $12, $F4
	dc.b $C, $5, $0, $15, $F4
DATA1J234NW7PIY_1B: dc.b $3
	dc.b $EE, $E, $0, $0, $ED
	dc.b $6, $C, $0, $C, $F5
	dc.b $E, $8, $0, $10, $FD
DATA1J234NW7PIY_1C: dc.b $4
	dc.b $EE, $E, $0, $0, $EA
	dc.b $FE, $5, $0, $C, $A
	dc.b $6, $8, $0, $10, $F2
	dc.b $E, $8, $0, $13, $FA
DATA1J234NW7PIY_1D: dc.b $6
	dc.b $EC, $D, $0, $0, $F3
	dc.b $F4, $2, $0, $8, $EB
	dc.b $FC, $9, $0, $B, $F3
	dc.b $4, $1, $0, $11, $B
	dc.b $C, $0, $0, $13, $F3
	dc.b $C, $0, $0, $14, $3
DATA1J234NW7PIY_1E: dc.b $7
	dc.b $EC, $3, $0, $0, $F4
	dc.b $EC, $5, $0, $4, $4
	dc.b $F4, $2, $0, $8, $EC
	dc.b $F4, $2, $0, $B, $FC
	dc.b $FC, $2, $0, $E, $4
	dc.b $4, $1, $0, $11, $C
	dc.b $C, $0, $0, $13, $F4
DATA1J234NW7PIY_1F: dc.b $3
	dc.b $F3, $E, $0, $0, $ED
	dc.b $F3, $2, $0, $C, $D
	dc.b $B, $0, $0, $F, $F5
DATA1J234NW7PIY_20: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $F2, $3, $0, $C, $C
	dc.b $A, $8, $0, $10, $F4
DATA1J234NW7PIY_21: dc.b $5
	dc.b $ED, $D, $0, $0, $F3
	dc.b $F5, $2, $0, $8, $EB
	dc.b $FD, $9, $0, $B, $F3
	dc.b $5, $1, $0, $11, $B
	dc.b $D, $4, $0, $13, $FB
DATA1J234NW7PIY_22: dc.b $6
	dc.b $EC, $3, $0, $0, $F4
	dc.b $EC, $5, $0, $4, $4
	dc.b $F4, $2, $0, $8, $EC
	dc.b $F4, $2, $0, $B, $FC
	dc.b $FC, $2, $0, $E, $4
	dc.b $4, $1, $0, $11, $C
DATA1J234NW7PIY_23: dc.b $3
	dc.b $F3, $E, $0, $0, $ED
	dc.b $F3, $2, $0, $C, $D
	dc.b $B, $0, $0, $F, $F5
DATA1J234NW7PIY_24: dc.b $2
	dc.b $F2, $F, $0, $0, $EC
	dc.b $F2, $3, $0, $10, $C
DATA1J234NW7PIY_25: dc.b $4
	dc.b $EF, $B, $0, $0, $EC
	dc.b $F7, $9, $0, $C, $4
	dc.b $7, $0, $0, $12, $4
	dc.b $F, $8, $0, $13, $EC
DATA1J234NW7PIY_26: dc.b $5
	dc.b $E9, $B, $0, $0, $F5
	dc.b $F9, $3, $0, $C, $ED
	dc.b $F9, $5, $0, $10, $D
	dc.b $9, $8, $0, $14, $F5
	dc.b $11, $0, $0, $17, $F5
DATA1J234NW7PIY_27: dc.b $3
	dc.b $EE, $5, $0, $0, $6
	dc.b $F6, $B, $0, $4, $EE
	dc.b $FE, $1, $0, $10, $6
DATA1J234NW7PIY_28: dc.b $6
	dc.b $EC, $7, $0, $0, $FD
	dc.b $F4, $3, $0, $8, $F5
	dc.b $F4, $5, $0, $C, $D
	dc.b $FC, $2, $0, $10, $ED
	dc.b $C, $4, $0, $13, $FD
	dc.b $14, $0, $0, $15, $F5
DATA1J234NW7PIY_29: dc.b $5
	dc.b $EE, $B, $0, $0, $F3
	dc.b $F6, $3, $0, $C, $EB
	dc.b $F6, $5, $0, $10, $B
	dc.b $6, $0, $0, $14, $B
	dc.b $E, $8, $0, $15, $F3
DATA1J234NW7PIY_2A: dc.b $5
	dc.b $EA, $B, $0, $0, $F4
	dc.b $FA, $2, $0, $C, $EC
	dc.b $FA, $5, $0, $F, $C
	dc.b $A, $4, $0, $13, $F4
	dc.b $12, $0, $0, $15, $F4
DATA1J234NW7PIY_2B: dc.b $3
	dc.b $ED, $5, $0, $0, $6
	dc.b $F5, $B, $0, $4, $EE
	dc.b $FD, $1, $0, $10, $6
DATA1J234NW7PIY_2C: dc.b $5
	dc.b $ED, $A, $0, $0, $FE
	dc.b $F5, $7, $0, $9, $EE
	dc.b $5, $4, $0, $11, $FE
	dc.b $D, $0, $0, $13, $FE
	dc.b $15, $0, $0, $14, $F6
DATA1J234NW7PIY_2D: dc.b $3
	dc.b $F1, $B, $0, $0, $F9
	dc.b $F9, $3, $0, $C, $F1
	dc.b $11, $8, $0, $10, $F9
DATA1J234NW7PIY_2E: dc.b $3
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $10, $8, $0, $10, $F9
DATA1J234NW7PIY_2F: dc.b $2
	dc.b $F1, $F, $0, $0, $F2
	dc.b $11, $8, $0, $10, $F2
DATA1J234NW7PIY_30: dc.b $3
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $3, $0, $C, $F1
	dc.b $10, $8, $0, $10, $F9
DATA1J234NW7PIY_31: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $FC, $1, $0, $C, $12
	dc.b $4, $9, $0, $E, $FA
DATA1J234NW7PIY_32: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $FC, $1, $0, $C, $12
	dc.b $4, $9, $0, $E, $FA
DATA1J234NW7PIY_33: dc.b $3
	dc.b $EC, $E, $0, $0, $F2
	dc.b $FC, $1, $0, $C, $12
	dc.b $4, $9, $0, $E, $FA
DATA1J234NW7PIY_34: dc.b $5
	dc.b $EB, $A, $0, $0, $F3
	dc.b $F3, $3, $0, $9, $B
	dc.b $FB, $1, $0, $D, $13
	dc.b $3, $5, $0, $F, $FB
	dc.b $13, $0, $0, $13, $FB
DATA1J234NW7PIY_35: dc.b $3
	dc.b $EF, $E, $0, $0, $F1
	dc.b $EF, $3, $0, $C, $11
	dc.b $7, $8, $0, $10, $F9
DATA1J234NW7PIY_36: dc.b $3
	dc.b $EF, $E, $0, $0, $F0
	dc.b $EF, $3, $0, $C, $10
	dc.b $7, $8, $0, $10, $F8
DATA1J234NW7PIY_37: dc.b $3
	dc.b $EF, $E, $0, $0, $F1
	dc.b $F7, $2, $0, $C, $11
	dc.b $7, $8, $0, $F, $F9
DATA1J234NW7PIY_38: dc.b $3
	dc.b $EF, $E, $0, $0, $F0
	dc.b $EF, $3, $0, $C, $10
	dc.b $7, $8, $0, $10, $F8
DATA1J234NW7PIY_39: dc.b $3
	dc.b $EC, $F, $0, $0, $F4
	dc.b $F4, $2, $0, $10, $EC
	dc.b $C, $0, $0, $13, $F4
DATA1J234NW7PIY_3A: dc.b $3
	dc.b $EC, $B, $0, $0, $FB
	dc.b $F4, $6, $0, $C, $EB
	dc.b $C, $0, $0, $12, $F3
DATA1J234NW7PIY_3B: dc.b $4
	dc.b $ED, $E, $0, $0, $F4
	dc.b $F5, $2, $0, $C, $EC
	dc.b $5, $8, $0, $F, $F4
	dc.b $D, $0, $0, $12, $F4
DATA1J234NW7PIY_3C: dc.b $4
	dc.b $ED, $B, $0, $0, $FB
	dc.b $F5, $6, $0, $C, $EB
	dc.b $FD, $0, $0, $12, $13
	dc.b $D, $0, $0, $13, $F3
DATA1J234NW7PIY_3D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_3E: dc.b $2
	dc.b $F1, $E, $0, $0, $F1
	dc.b $9, $8, $0, $C, $F1
DATA1J234NW7PIY_3F: dc.b $1
	dc.b $F1, $F, $0, $0, $F2
DATA1J234NW7PIY_40: dc.b $2
	dc.b $F2, $E, $0, $0, $F1
	dc.b $A, $8, $0, $C, $F1
DATA1J234NW7PIY_41: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_42: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_43: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_44: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_45: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_46: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_47: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA1J234NW7PIY_48: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $8, $1, $0, $C, $ED
	dc.b $10, $8, $0, $E, $F5
DATA1J234NW7PIY_49: dc.b $2
	dc.b $EF, $F, $0, $0, $F2
	dc.b $F, $4, $0, $10, $F2
DATA1J234NW7PIY_4A: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $8, $1, $0, $C, $ED
	dc.b $10, $4, $0, $E, $F5
DATA1J234NW7PIY_4B: dc.b $2
	dc.b $F0, $B, $0, $0, $F4
	dc.b $10, $4, $0, $C, $F4
DATA1J234NW7PIY_4C: dc.b $1
	dc.b $F4, $B, $0, $0, $F7
DATA1J234NW7PIY_4D: dc.b $2
	dc.b $FA, $E, $0, $0, $F5
	dc.b $12, $8, $0, $C, $F5
DATA1J234NW7PIY_4E: dc.b $3
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $C
	dc.b $C, $8, $0, $10, $F4
DATA1J234NW7PIY_4F: dc.b $3
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
	dc.b $C, $8, $0, $F, $F4
DATA1J234NW7PIY_50: dc.b $3
	dc.b $EE, $E, $0, $0, $E8
	dc.b $EE, $3, $0, $C, $8
	dc.b $F6, $2, $0, $10, $10
DATA1J234NW7PIY_51: dc.b $3
	dc.b $EF, $E, $0, $0, $E8
	dc.b $EF, $2, $0, $C, $8
	dc.b $F7, $1, $0, $F, $10
DATA1J234NW7PIY_52: dc.b $4
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F8, $0, $0, $C, $C
	dc.b $8, $8, $0, $D, $F4
	dc.b $10, $4, $0, $10, $F4
DATA1J234NW7PIY_53: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATA1J234NW7PIY_54: dc.b $3
	dc.b $F4, $E, $0, $0, $F7
	dc.b $F4, $1, $0, $C, $17
	dc.b $FC, $1, $0, $E, $EF
DATA1J234NW7PIY_55: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $F4, $5, $0, $8, $A
	dc.b $4, $C, $0, $C, $F2
DATA1J234NW7PIY_56: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $5, $0, $8, $4
	dc.b $4, $8, $0, $C, $EC
DATA1J234NW7PIY_57: dc.b $3
	dc.b $F4, $D, $0, $0, $E5
	dc.b $FC, $1, $0, $8, $5
	dc.b $4, $8, $0, $A, $ED
DATA1J234NW7PIY_58: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $1, $0, $8, $F4
	dc.b $4, $8, $0, $A, $FC
DATA1J234NW7PIY_59: dc.b $3
	dc.b $F5, $E, $0, $0, $F7
	dc.b $F5, $1, $0, $C, $17
	dc.b $FD, $1, $0, $E, $EF
DATA1J234NW7PIY_5A: dc.b $5
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $3, $0, $C, $ED
	dc.b $FF, $1, $0, $10, $D
	dc.b $F, $0, $0, $12, $F5
	dc.b $F, $0, $0, $13, $5
DATA1J234NW7PIY_5B: dc.b $2
	dc.b $EA, $B, $0, $0, $F4
	dc.b $A, $5, $0, $C, $F4
DATA1J234NW7PIY_5C: dc.b $7
	dc.b $EA, $E, $0, $0, $ED
	dc.b $EA, $1, $0, $C, $D
	dc.b $2, $9, $0, $E, $F5
	dc.b $A, $1, $0, $14, $ED
	dc.b $A, $1, $0, $16, $D
	dc.b $12, $0, $0, $18, $F5
	dc.b $12, $0, $0, $19, $5
DATA1J234NW7PIY_5D: dc.b $6
	dc.b $ED, $D, $0, $0, $ED
	dc.b $ED, $1, $0, $8, $D
	dc.b $FD, $6, $0, $A, $F5
	dc.b $5, $1, $0, $10, $ED
	dc.b $5, $1, $0, $12, $5
	dc.b $D, $0, $0, $14, $D
DATA1J234NW7PIY_C8: dc.b $4
	dc.b $EC, $B, $0, $0, $F9
	dc.b $F4, $3, $0, $C, $F1
	dc.b $FC, $1, $0, $10, $11
	dc.b $C, $8, $0, $12, $F9
DATA1J234NW7PIY_C9: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $4, $0, $0, $10, $12
	dc.b $C, $C, $0, $11, $F2
DATA1J234NW7PIY_CA: dc.b $3
	dc.b $ED, $B, $0, $0, $F8
	dc.b $FD, $1, $0, $C, $F0
	dc.b $D, $8, $0, $E, $F8
DATA1J234NW7PIY_CB: dc.b $2
	dc.b $ED, $F, $0, $0, $F5
	dc.b $D, $8, $0, $10, $F5
DATA1J234NW7PIY_CC: dc.b $5
	dc.b $EA, $A, $0, $0, $E1
	dc.b $F2, $6, $0, $9, $F9
	dc.b $2, $5, $0, $F, $E9
	dc.b $A, $1, $0, $13, $F9
	dc.b $12, $0, $0, $15, $F1
DATA1J234NW7PIY_CD: dc.b $5
	dc.b $E9, $A, $0, $0, $E5
	dc.b $F1, $2, $0, $9, $FD
	dc.b $F9, $1, $0, $C, $5
	dc.b $1, $6, $0, $E, $ED
	dc.b $11, $0, $0, $14, $FD
DATA1J234NW7PIY_CE: dc.b $3
	dc.b $EB, $F, $0, $0, $EA
	dc.b $B, $8, $0, $10, $EA
	dc.b $13, $4, $0, $13, $F2
DATA1J234NW7PIY_CF: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $C, $0, $C, $F6
DATA1J234NW7PIY_D0: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $C, $0, $C, $F6
DATA1J234NW7PIY_D1: dc.b $2
	dc.b $EE, $B, $0, $0, $F6
	dc.b $E, $C, $0, $C, $F6
DATA1J234NW7PIY_D2: dc.b $3
	dc.b $F2, $E, $0, $0, $EE
	dc.b $FA, $2, $0, $C, $E
	dc.b $A, $5, $0, $F, $FE
DATA1J234NW7PIY_D3: dc.b $3
	dc.b $F2, $E, $0, $0, $EE
	dc.b $FA, $2, $0, $C, $E
	dc.b $A, $5, $0, $F, $FE
DATA1J234NW7PIY_D4: dc.b $3
	dc.b $F2, $E, $0, $0, $EE
	dc.b $FA, $2, $0, $C, $E
	dc.b $A, $5, $0, $F, $FE
DATA1J234NW7PIY_D5: dc.b $3
	dc.b $F2, $E, $0, $0, $EE
	dc.b $FA, $2, $0, $C, $E
	dc.b $A, $5, $0, $F, $FE
DATA1J234NW7PIY_D6: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_D7: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_D8: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_D9: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_DA: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA1J234NW7PIY_DB: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
	even