; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri May 04 2018 20:29:34 GMT-0400 (Eastern Daylight Time)
; ================================================================================

Metal_Map:
	dc.w $0, Metal_Map_1-Metal_Map
	dc.w Metal_Map_2-Metal_Map, Metal_Map_3-Metal_Map
	dc.w Metal_Map_4-Metal_Map, Metal_Map_5-Metal_Map
	dc.w Metal_Map_6-Metal_Map, Metal_Map_7-Metal_Map
	dc.w Metal_Map_8-Metal_Map, Metal_Map_9-Metal_Map
	dc.w Metal_Map_A-Metal_Map, Metal_Map_B-Metal_Map
	dc.w Metal_Map_C-Metal_Map, Metal_Map_D-Metal_Map
	dc.w Metal_Map_E-Metal_Map, Metal_Map_F-Metal_Map
	dc.w Metal_Map_10-Metal_Map, Metal_Map_11-Metal_Map
	dc.w Metal_Map_12-Metal_Map, Metal_Map_13-Metal_Map
	dc.w Metal_Map_14-Metal_Map, Metal_Map_15-Metal_Map
	dc.w Metal_Map_16-Metal_Map, Metal_Map_17-Metal_Map
	dc.w Metal_Map_18-Metal_Map, Metal_Map_19-Metal_Map
	dc.w Metal_Map_1A-Metal_Map, Metal_Map_1B-Metal_Map
	dc.w Metal_Map_1C-Metal_Map, Metal_Map_1D-Metal_Map
	dc.w Metal_Map_1E-Metal_Map, Metal_Map_1F-Metal_Map
	dc.w Metal_Map_20-Metal_Map, Metal_Map_21-Metal_Map
	dc.w Metal_Map_22-Metal_Map, Metal_Map_23-Metal_Map
	dc.w Metal_Map_24-Metal_Map, Metal_Map_25-Metal_Map
	dc.w Metal_Map_26-Metal_Map, Metal_Map_27-Metal_Map
	dc.w Metal_Map_28-Metal_Map, Metal_Map_29-Metal_Map
	dc.w Metal_Map_2A-Metal_Map, Metal_Map_2B-Metal_Map
	dc.w Metal_Map_2C-Metal_Map, Metal_Map_2D-Metal_Map
	dc.w Metal_Map_2E-Metal_Map, Metal_Map_2F-Metal_Map
	dc.w Metal_Map_30-Metal_Map, Metal_Map_31-Metal_Map
	dc.w Metal_Map_32-Metal_Map, $0
	dc.w $0, $0
	dc.w $0, Metal_Map_37-Metal_Map
	dc.w Metal_Map_38-Metal_Map, Metal_Map_39-Metal_Map
	dc.w Metal_Map_3A-Metal_Map, Metal_Map_3B-Metal_Map
	dc.w Metal_Map_3C-Metal_Map, Metal_Map_3D-Metal_Map
	dc.w Metal_Map_3E-Metal_Map, Metal_Map_3F-Metal_Map
	dc.w Metal_Map_40-Metal_Map, Metal_Map_41-Metal_Map
	dc.w Metal_Map_42-Metal_Map, $0
	dc.w $0, Metal_Map_45-Metal_Map
	dc.w Metal_Map_46-Metal_Map, Metal_Map_47-Metal_Map
	dc.w Metal_Map_48-Metal_Map, $0
	dc.w $0, $0
	dc.w Metal_Map_4C-Metal_Map, Metal_Map_4D-Metal_Map
	dc.w $0, $0
	dc.w $0, $0
	dc.w $0, Metal_Map_53-Metal_Map
	dc.w Metal_Map_54-Metal_Map, Metal_Map_55-Metal_Map
	dc.w Metal_Map_56-Metal_Map, Metal_Map_57-Metal_Map
	dc.w Metal_Map_58-Metal_Map, Metal_Map_59-Metal_Map
	dc.w Metal_Map_5A-Metal_Map, Metal_Map_5B-Metal_Map
	dc.w Metal_Map_5C-Metal_Map, Metal_Map_5D-Metal_Map
	dc.w Metal_Map_5E-Metal_Map, Metal_Map_5F-Metal_Map
	dc.w Metal_Map_60-Metal_Map, Metal_Map_61-Metal_Map
	dc.w Metal_Map_62-Metal_Map, Metal_Map_63-Metal_Map
	dc.w Metal_Map_64-Metal_Map, Metal_Map_65-Metal_Map
	dc.w Metal_Map_66-Metal_Map, Metal_Map_67-Metal_Map
	dc.w Metal_Map_68-Metal_Map, Metal_Map_69-Metal_Map
	dc.w Metal_Map_6A-Metal_Map, Metal_Map_6B-Metal_Map
	dc.w Metal_Map_6C-Metal_Map, Metal_Map_6D-Metal_Map
	dc.w Metal_Map_6E-Metal_Map, Metal_Map_6F-Metal_Map
	dc.w Metal_Map_70-Metal_Map, Metal_Map_71-Metal_Map
	dc.w Metal_Map_72-Metal_Map, Metal_Map_73-Metal_Map
	dc.w Metal_Map_74-Metal_Map, Metal_Map_75-Metal_Map
	dc.w Metal_Map_76-Metal_Map, Metal_Map_77-Metal_Map
	dc.w Metal_Map_78-Metal_Map, Metal_Map_79-Metal_Map
	dc.w Metal_Map_7A-Metal_Map, Metal_Map_7B-Metal_Map
	dc.w Metal_Map_7C-Metal_Map, Metal_Map_7D-Metal_Map
Metal_Map_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
Metal_Map_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Metal_Map_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Metal_Map_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Metal_Map_5: dc.b $5
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
	dc.b $F4, $0, $0, $F, $E8
	dc.b $F4, $0, $0, $10, $8
Metal_Map_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
Metal_Map_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
Metal_Map_8: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $FE, $0, $0, $9, $8
	dc.b $ED, $9, $0, $A, $F3
Metal_Map_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
Metal_Map_A: dc.b $3
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
	dc.b $FD, $0, $0, $12, $8
Metal_Map_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EB
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
Metal_Map_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
Metal_Map_D: dc.b $6
	dc.b $EE, $9, $0, $0, $EC
	dc.b $ED, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
Metal_Map_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
Metal_Map_F: dc.b $7
	dc.b $ED, $9, $0, $0, $E9
	dc.b $FB, $D, $0, $6, $F3
	dc.b $B, $8, $0, $E, $F3
	dc.b $13, $4, $0, $11, $FB
	dc.b $ED, $1, $0, $13, $1
	dc.b $F3, $0, $0, $15, $3
	dc.b $F3, $0, $0, $16, $B
Metal_Map_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
Metal_Map_11: dc.b $5
	dc.b $EE, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
Metal_Map_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $ED, $9, $0, $8, $FB
	dc.b $FD, $4, $0, $E, $FB
	dc.b $5, $9, $0, $10, $FB
Metal_Map_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $ED, $B, $0, $8, $FC
Metal_Map_14: dc.b $2
	dc.b $F3, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
Metal_Map_15: dc.b $4
	dc.b $F3, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
Metal_Map_16: dc.b $2
	dc.b $F3, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
Metal_Map_17: dc.b $3
	dc.b $F6, $7, $0, $0, $ED
	dc.b $EE, $0, $0, $8, $FD
	dc.b $F5, $A, $0, $9, $FD
Metal_Map_18: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $FD, $0, $0, $13, $13
Metal_Map_19: dc.b $5
	dc.b $FC, $6, $0, $0, $ED
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
Metal_Map_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
Metal_Map_1B: dc.b $7
	dc.b $ED, $8, $0, $0, $F3
	dc.b $F5, $D, $0, $3, $FB
	dc.b $5, $8, $0, $B, $FB
	dc.b $FF, $1, $0, $E, $EB
	dc.b $FF, $2, $0, $10, $F3
	dc.b $F7, $4, $0, $13, $EB
	dc.b $F4, $0, $0, $15, $F3
Metal_Map_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
Metal_Map_1D: dc.b $4
	dc.b $FB, $6, $0, $0, $EE
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
Metal_Map_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Metal_Map_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F3
	dc.b $FE, $E, $0, $6, $EC
Metal_Map_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Metal_Map_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F3
	dc.b $FE, $E, $0, $6, $EC
Metal_Map_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
Metal_Map_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
Metal_Map_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
Metal_Map_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
Metal_Map_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Metal_Map_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Metal_Map_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Metal_Map_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Metal_Map_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
Metal_Map_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
Metal_Map_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
Metal_Map_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
Metal_Map_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Metal_Map_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Metal_Map_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Metal_Map_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Metal_Map_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Metal_Map_37: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
Metal_Map_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
Metal_Map_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
Metal_Map_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
Metal_Map_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
Metal_Map_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
Metal_Map_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
Metal_Map_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
Metal_Map_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
Metal_Map_40: dc.b $4
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
	dc.b $F0, $0, $0, $F, $E8
Metal_Map_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
Metal_Map_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
Metal_Map_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Metal_Map_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Metal_Map_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Metal_Map_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Metal_Map_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
Metal_Map_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
Metal_Map_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
Metal_Map_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
Metal_Map_55: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $FA, $1, $0, $C, $C
	dc.b $A, $C, $0, $E, $F4
Metal_Map_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
Metal_Map_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
Metal_Map_58: dc.b $2
	dc.b $0, $2, $0, $0, $F3
	dc.b $F8, $B, $0, $3, $FB
Metal_Map_59: dc.b $1
	dc.b $F8, $F, $0, $0, $F3
Metal_Map_5A: dc.b $1
	dc.b $F8, $F, $0, $0, $F3
Metal_Map_5B: dc.b $1
	dc.b $F8, $F, $0, $0, $F3
Metal_Map_5C: dc.b $1
	dc.b $F8, $F, $0, $0, $F3
Metal_Map_5D: dc.b $1
	dc.b $F8, $F, $0, $0, $F3
Metal_Map_5E: dc.b $5
	dc.b $F0, $F, $0, $0, $E4
	dc.b $F8, $0, $0, $10, $4
	dc.b $0, $0, $0, $11, $4
	dc.b $8, $0, $0, $12, $4
	dc.b $F0, $0, $0, $13, $4
Metal_Map_5F: dc.b $5
	dc.b $F0, $F, $0, $0, $E4
	dc.b $F8, $0, $0, $10, $4
	dc.b $0, $0, $0, $11, $4
	dc.b $8, $0, $0, $12, $4
	dc.b $F0, $0, $0, $13, $4
Metal_Map_60: dc.b $5
	dc.b $F0, $F, $0, $0, $E4
	dc.b $F8, $0, $0, $10, $4
	dc.b $0, $0, $0, $11, $4
	dc.b $8, $0, $0, $12, $4
	dc.b $F0, $0, $0, $13, $4
Metal_Map_61: dc.b $5
	dc.b $F0, $F, $0, $0, $E4
	dc.b $F8, $0, $0, $10, $4
	dc.b $0, $0, $0, $11, $4
	dc.b $8, $0, $0, $12, $4
	dc.b $F0, $0, $0, $13, $4
Metal_Map_62: dc.b $5
	dc.b $F3, $F, $18, $0, $EB
	dc.b $EB, $0, $18, $10, $F3
	dc.b $EB, $0, $18, $11, $FB
	dc.b $EB, $0, $18, $12, $3
	dc.b $EB, $0, $18, $13, $EB
Metal_Map_63: dc.b $5
	dc.b $F3, $F, $18, $0, $EB
	dc.b $EB, $0, $18, $10, $F3
	dc.b $EB, $0, $18, $11, $FB
	dc.b $EB, $0, $18, $12, $3
	dc.b $EB, $0, $18, $13, $EB
Metal_Map_64: dc.b $5
	dc.b $F3, $F, $18, $0, $EB
	dc.b $EB, $0, $18, $10, $F3
	dc.b $EB, $0, $18, $11, $FB
	dc.b $EB, $0, $18, $12, $3
	dc.b $EB, $0, $18, $13, $EB
Metal_Map_65: dc.b $5
	dc.b $F3, $F, $18, $0, $EB
	dc.b $EB, $0, $18, $10, $F3
	dc.b $EB, $0, $18, $11, $FB
	dc.b $EB, $0, $18, $12, $3
	dc.b $EB, $0, $18, $13, $EB
Metal_Map_66: dc.b $5
	dc.b $F0, $F, $18, $0, $E8
	dc.b $E8, $0, $18, $10, $F0
	dc.b $E8, $0, $18, $11, $F8
	dc.b $E8, $0, $18, $12, $0
	dc.b $E8, $0, $18, $13, $E8
Metal_Map_67: dc.b $5
	dc.b $F0, $F, $0, $0, $E8
	dc.b $E8, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
	dc.b $E8, $0, $0, $12, $0
	dc.b $E8, $0, $0, $13, $E8
Metal_Map_68: dc.b $5
	dc.b $F0, $F, $0, $0, $E8
	dc.b $E8, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
	dc.b $E8, $0, $0, $12, $0
	dc.b $E8, $0, $0, $13, $E8
Metal_Map_69: dc.b $5
	dc.b $F0, $F, $0, $0, $E8
	dc.b $E8, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
	dc.b $E8, $0, $0, $12, $0
	dc.b $E8, $0, $0, $13, $E8
Metal_Map_6A: dc.b $4
	dc.b $E8, $F, $18, $0, $F4
	dc.b $F8, $0, $18, $10, $EC
	dc.b $F0, $0, $18, $11, $EC
	dc.b $E8, $0, $18, $12, $EC
Metal_Map_6B: dc.b $4
	dc.b $E8, $F, $18, $0, $F4
	dc.b $F8, $0, $18, $10, $EC
	dc.b $F0, $0, $18, $11, $EC
	dc.b $E8, $0, $18, $12, $EC
Metal_Map_6C: dc.b $4
	dc.b $E8, $F, $18, $0, $F4
	dc.b $F8, $0, $18, $10, $EC
	dc.b $F0, $0, $18, $11, $EC
	dc.b $E8, $0, $18, $12, $EC
Metal_Map_6D: dc.b $4
	dc.b $E8, $F, $18, $0, $F4
	dc.b $F8, $0, $18, $10, $EC
	dc.b $F0, $0, $18, $11, $EC
	dc.b $E8, $0, $18, $12, $EC
Metal_Map_6E: dc.b $1
	dc.b $EE, $B, $0, $0, $F4
Metal_Map_6F: dc.b $3
	dc.b $E9, $B, $0, $0, $F4
	dc.b $9, $9, $0, $C, $F4
	dc.b $F9, $0, $0, $12, $C
Metal_Map_70: dc.b $4
	dc.b $F9, $D, $0, $0, $EC
	dc.b $E9, $9, $0, $8, $F4
	dc.b $9, $8, $0, $E, $F4
	dc.b $11, $0, $0, $11, $F4
Metal_Map_71: dc.b $5
	dc.b $E9, $B, $0, $0, $F3
	dc.b $9, $8, $0, $C, $F3
	dc.b $11, $0, $0, $F, $F3
	dc.b $1, $0, $0, $10, $EC
	dc.b $ED, $0, $0, $11, $B
Metal_Map_72: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $C, $0, $C, $F4
Metal_Map_73: dc.b $2
	dc.b $9, $D, $0, $0, $F0
	dc.b $E9, $B, $0, $8, $F8
Metal_Map_74: dc.b $2
	dc.b $EC, $F, $0, $0, $F3
	dc.b $C, $C, $0, $10, $F3
Metal_Map_75: dc.b $2
	dc.b $F9, $F, $0, $0, $F0
	dc.b $E9, $9, $0, $10, $F8
Metal_Map_76: dc.b $2
	dc.b $F9, $F, $0, $0, $F0
	dc.b $E9, $9, $0, $10, $F8
Metal_Map_77: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_78: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_79: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_7A: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_7B: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_7C: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Metal_Map_7D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
	even