; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 22 2021 19:45:32 GMT-0500 (Eastern Standard Time)
; ================================================================================

MightyMap:
	dc.w $0, MightyMap_1-MightyMap
	dc.w MightyMap_2-MightyMap, MightyMap_3-MightyMap
	dc.w MightyMap_4-MightyMap, MightyMap_5-MightyMap
	dc.w MightyMap_6-MightyMap, MightyMap_7-MightyMap
	dc.w MightyMap_8-MightyMap, MightyMap_9-MightyMap
	dc.w MightyMap_A-MightyMap, MightyMap_B-MightyMap
	dc.w MightyMap_C-MightyMap, MightyMap_D-MightyMap
	dc.w MightyMap_E-MightyMap, MightyMap_F-MightyMap
	dc.w MightyMap_10-MightyMap, MightyMap_11-MightyMap
	dc.w MightyMap_12-MightyMap, MightyMap_13-MightyMap
	dc.w MightyMap_14-MightyMap, MightyMap_15-MightyMap
	dc.w MightyMap_16-MightyMap, MightyMap_17-MightyMap
	dc.w MightyMap_18-MightyMap, MightyMap_19-MightyMap
	dc.w MightyMap_1A-MightyMap, MightyMap_1B-MightyMap
	dc.w MightyMap_1C-MightyMap, MightyMap_1D-MightyMap
	dc.w MightyMap_1E-MightyMap, MightyMap_1F-MightyMap
	dc.w MightyMap_20-MightyMap, MightyMap_21-MightyMap
	dc.w MightyMap_22-MightyMap, MightyMap_23-MightyMap
	dc.w MightyMap_24-MightyMap, MightyMap_25-MightyMap
	dc.w MightyMap_26-MightyMap, MightyMap_27-MightyMap
	dc.w MightyMap_28-MightyMap, MightyMap_29-MightyMap
	dc.w MightyMap_2A-MightyMap, MightyMap_2B-MightyMap
	dc.w MightyMap_2C-MightyMap, MightyMap_2D-MightyMap
	dc.w MightyMap_2E-MightyMap, MightyMap_2F-MightyMap
	dc.w MightyMap_30-MightyMap, MightyMap_31-MightyMap
	dc.w MightyMap_32-MightyMap, MightyMap_33-MightyMap
	dc.w MightyMap_34-MightyMap, MightyMap_35-MightyMap
	dc.w MightyMap_36-MightyMap, MightyMap_37-MightyMap
	dc.w MightyMap_38-MightyMap, MightyMap_39-MightyMap
	dc.w MightyMap_3A-MightyMap, MightyMap_3B-MightyMap
	dc.w MightyMap_3C-MightyMap, MightyMap_3D-MightyMap
	dc.w MightyMap_3E-MightyMap, MightyMap_3F-MightyMap
	dc.w MightyMap_40-MightyMap, MightyMap_41-MightyMap
	dc.w MightyMap_42-MightyMap, MightyMap_43-MightyMap
	dc.w MightyMap_44-MightyMap, MightyMap_45-MightyMap
	dc.w MightyMap_46-MightyMap, MightyMap_47-MightyMap
	dc.w MightyMap_48-MightyMap, MightyMap_49-MightyMap
	dc.w MightyMap_4A-MightyMap, MightyMap_4B-MightyMap
	dc.w MightyMap_4C-MightyMap, MightyMap_4D-MightyMap
	dc.w MightyMap_4E-MightyMap, MightyMap_4F-MightyMap
	dc.w MightyMap_50-MightyMap, MightyMap_51-MightyMap
	dc.w MightyMap_52-MightyMap, MightyMap_53-MightyMap
	dc.w MightyMap_54-MightyMap, MightyMap_55-MightyMap
	dc.w MightyMap_56-MightyMap, MightyMap_57-MightyMap
	dc.w MightyMap_58-MightyMap, MightyMap_59-MightyMap
	dc.w MightyMap_5A-MightyMap, MightyMap_5B-MightyMap
	dc.w MightyMap_5C-MightyMap, MightyMap_5D-MightyMap
	dc.w MightyMap_5E-MightyMap, MightyMap_5F-MightyMap
	dc.w MightyMap_60-MightyMap, MightyMap_61-MightyMap
	dc.w MightyMap_62-MightyMap, MightyMap_63-MightyMap
	dc.w MightyMap_64-MightyMap, MightyMap_65-MightyMap
	dc.w MightyMap_66-MightyMap, MightyMap_67-MightyMap
	dc.w MightyMap_68-MightyMap, MightyMap_69-MightyMap
	dc.w MightyMap_6A-MightyMap, MightyMap_6B-MightyMap
	dc.w MightyMap_6C-MightyMap, MightyMap_6D-MightyMap
	dc.w MightyMap_6E-MightyMap
MightyMap_1: dc.b $2
	dc.b $EE, $B, $0, $0, $F4
	dc.b $E, $C, $0, $C, $F4
MightyMap_2: dc.b $2
	dc.b $EF, $B, $0, $0, $F2
	dc.b $F, $C, $0, $C, $F2
MightyMap_3: dc.b $2
	dc.b $EF, $B, $0, $0, $F2
	dc.b $F, $C, $0, $C, $F2
MightyMap_4: dc.b $3
	dc.b $EF, $B, $0, $0, $F2
	dc.b $7, $1, $0, $C, $A
	dc.b $F, $8, $0, $E, $F2
MightyMap_5: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $D, $C, $0, $C, $F3
MightyMap_6: dc.b $3
	dc.b $EE, $B, $0, $0, $F7
	dc.b $F6, $3, $0, $C, $EF
	dc.b $FE, $1, $0, $10, $F
MightyMap_7: dc.b $4
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $0, $0, $C, $D
	dc.b $7, $1, $0, $D, $D
	dc.b $F, $8, $0, $F, $F5
MightyMap_8: dc.b $2
	dc.b $F0, $B, $0, $0, $F5
	dc.b $10, $4, $0, $C, $F5
MightyMap_9: dc.b $5
	dc.b $EE, $B, $0, $0, $F6
	dc.b $FE, $2, $0, $C, $EE
	dc.b $FE, $1, $0, $F, $E
	dc.b $E, $0, $0, $11, $F6
	dc.b $E, $0, $0, $12, $6
MightyMap_A: dc.b $3
	dc.b $EF, $B, $0, $0, $F6
	dc.b $FF, $1, $0, $C, $EE
	dc.b $F, $8, $0, $E, $F6
MightyMap_B: dc.b $3
	dc.b $F0, $B, $0, $0, $F4
	dc.b $F8, $0, $0, $C, $C
	dc.b $10, $4, $0, $D, $F4
MightyMap_C: dc.b $4
	dc.b $ED, $E, $0, $0, $F1
	dc.b $ED, $2, $0, $C, $11
	dc.b $5, $8, $0, $F, $F1
	dc.b $D, $5, $0, $12, $F9
MightyMap_D: dc.b $3
	dc.b $EE, $B, $0, $0, $F2
	dc.b $F6, $6, $0, $C, $A
	dc.b $E, $4, $0, $12, $FA
MightyMap_E: dc.b $3
	dc.b $ED, $B, $0, $0, $F5
	dc.b $FD, $2, $0, $C, $D
	dc.b $D, $4, $0, $F, $FD
MightyMap_F: dc.b $4
	dc.b $EC, $B, $0, $0, $F3
	dc.b $F4, $1, $0, $C, $B
	dc.b $C, $8, $0, $E, $F3
	dc.b $14, $4, $0, $11, $FB
MightyMap_10: dc.b $4
	dc.b $ED, $A, $0, $0, $F4
	dc.b $FD, $2, $0, $9, $C
	dc.b $5, $4, $0, $C, $FC
	dc.b $D, $0, $0, $E, $FC
MightyMap_11: dc.b $3
	dc.b $EF, $A, $0, $0, $F3
	dc.b $FF, $4, $0, $9, $B
	dc.b $7, $9, $0, $B, $FB
MightyMap_12: dc.b $3
	dc.b $ED, $F, $0, $0, $EE
	dc.b $5, $1, $0, $10, $E
	dc.b $D, $4, $0, $12, $FE
MightyMap_13: dc.b $3
	dc.b $ED, $7, $0, $0, $EF
	dc.b $ED, $7, $0, $8, $7
	dc.b $F5, $2, $0, $10, $FF
MightyMap_14: dc.b $2
	dc.b $F3, $E, $0, $0, $F0
	dc.b $FB, $1, $0, $C, $10
MightyMap_15: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $EE, $1, $0, $10, $E
	dc.b $6, $0, $0, $12, $E
	dc.b $E, $0, $0, $13, $FE
MightyMap_16: dc.b $3
	dc.b $F3, $E, $0, $0, $EF
	dc.b $F3, $1, $0, $C, $F
	dc.b $B, $4, $0, $E, $FF
MightyMap_17: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $F9, $2, $0, $C, $10
	dc.b $9, $8, $0, $F, $F8
MightyMap_18: dc.b $5
	dc.b $ED, $B, $0, $0, $ED
	dc.b $F5, $5, $0, $C, $5
	dc.b $FD, $0, $0, $10, $15
	dc.b $5, $0, $0, $11, $5
	dc.b $D, $8, $0, $12, $ED
MightyMap_19: dc.b $4
	dc.b $E9, $B, $0, $0, $F6
	dc.b $F1, $3, $0, $C, $EE
	dc.b $F1, $1, $0, $10, $E
	dc.b $9, $4, $0, $12, $F6
MightyMap_1A: dc.b $3
	dc.b $ED, $9, $0, $0, $FD
	dc.b $F5, $6, $0, $6, $ED
	dc.b $FD, $5, $0, $C, $FD
MightyMap_1B: dc.b $4
	dc.b $ED, $7, $0, $0, $F4
	dc.b $F5, $2, $0, $8, $EC
	dc.b $F5, $9, $0, $B, $4
	dc.b $5, $4, $0, $11, $4
MightyMap_1C: dc.b $4
	dc.b $ED, $8, $0, $0, $FD
	dc.b $F5, $D, $0, $3, $ED
	dc.b $FD, $0, $0, $B, $D
	dc.b $5, $8, $0, $C, $ED
MightyMap_1D: dc.b $4
	dc.b $EB, $A, $0, $0, $FF
	dc.b $F3, $7, $0, $9, $EF
	dc.b $3, $4, $0, $11, $FF
	dc.b $B, $0, $0, $13, $FF
MightyMap_1E: dc.b $3
	dc.b $F2, $B, $0, $0, $F6
	dc.b $FA, $3, $0, $C, $EE
	dc.b $12, $4, $0, $10, $F6
MightyMap_1F: dc.b $3
	dc.b $F1, $B, $0, $0, $F6
	dc.b $F9, $3, $0, $C, $EE
	dc.b $11, $4, $0, $10, $F6
MightyMap_20: dc.b $3
	dc.b $F2, $B, $0, $0, $F6
	dc.b $FA, $3, $0, $C, $EE
	dc.b $12, $4, $0, $10, $F6
MightyMap_21: dc.b $3
	dc.b $F1, $B, $0, $0, $F6
	dc.b $F9, $3, $0, $C, $EE
	dc.b $11, $4, $0, $10, $F6
MightyMap_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $F8, $3, $0, $C, $D
	dc.b $10, $8, $0, $10, $F5
MightyMap_23: dc.b $3
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $3, $0, $C, $D
	dc.b $F, $8, $0, $10, $F5
MightyMap_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F5
	dc.b $F8, $3, $0, $C, $D
	dc.b $10, $4, $0, $10, $FD
MightyMap_25: dc.b $3
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F7, $3, $0, $C, $D
	dc.b $F, $8, $0, $10, $F5
MightyMap_26: dc.b $3
	dc.b $F2, $E, $0, $0, $F2
	dc.b $FA, $2, $0, $C, $12
	dc.b $A, $8, $0, $F, $FA
MightyMap_27: dc.b $3
	dc.b $F2, $E, $0, $0, $F1
	dc.b $FA, $2, $0, $C, $11
	dc.b $A, $8, $0, $F, $F9
MightyMap_28: dc.b $3
	dc.b $F2, $E, $0, $0, $F2
	dc.b $FA, $2, $0, $C, $12
	dc.b $A, $8, $0, $F, $FA
MightyMap_29: dc.b $3
	dc.b $F2, $E, $0, $0, $F1
	dc.b $FA, $2, $0, $C, $11
	dc.b $A, $8, $0, $F, $F9
MightyMap_2A: dc.b $2
	dc.b $EB, $F, $0, $0, $F8
	dc.b $F3, $2, $0, $10, $F0
MightyMap_2B: dc.b $2
	dc.b $EB, $F, $0, $0, $F7
	dc.b $F3, $2, $0, $10, $EF
MightyMap_2C: dc.b $3
	dc.b $EC, $E, $0, $0, $F8
	dc.b $F4, $2, $0, $C, $F0
	dc.b $4, $8, $0, $F, $F8
MightyMap_2D: dc.b $2
	dc.b $EB, $F, $0, $0, $F7
	dc.b $F3, $2, $0, $10, $EF
MightyMap_2E: dc.b $2
	dc.b $F3, $B, $0, $0, $F3
	dc.b $FB, $1, $0, $C, $B
MightyMap_2F: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $4, $0, $C, $F3
MightyMap_30: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
MightyMap_31: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
MightyMap_32: dc.b $2
	dc.b $F3, $E, $0, $0, $F3
	dc.b $B, $8, $0, $C, $F3
MightyMap_33: dc.b $2
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
MightyMap_34: dc.b $3
	dc.b $F0, $A, $0, $0, $F8
	dc.b $F8, $2, $0, $9, $F0
	dc.b $8, $4, $0, $C, $F8
MightyMap_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F5
	dc.b $C, $8, $0, $C, $F5
MightyMap_36: dc.b $3
	dc.b $F0, $A, $0, $0, $F0
	dc.b $F8, $2, $0, $9, $8
	dc.b $8, $4, $0, $C, $F8
MightyMap_37: dc.b $3
	dc.b $F5, $A, $0, $0, $F3
	dc.b $5, $1, $0, $9, $B
	dc.b $D, $4, $0, $B, $FB
MightyMap_38: dc.b $3
	dc.b $F2, $A, $0, $0, $F0
	dc.b $FA, $3, $0, $9, $8
	dc.b $A, $0, $0, $D, $0
MightyMap_39: dc.b $2
	dc.b $FB, $E, $0, $0, $F1
	dc.b $13, $8, $0, $C, $F1
MightyMap_3A: dc.b $4
	dc.b $EC, $B, $0, $0, $E5
	dc.b $F4, $4, $0, $C, $FD
	dc.b $FC, $0, $0, $E, $FD
	dc.b $C, $8, $0, $F, $E5
MightyMap_3B: dc.b $3
	dc.b $EC, $D, $0, $0, $E5
	dc.b $FC, $A, $0, $8, $E5
	dc.b $4, $0, $0, $11, $FD
MightyMap_3C: dc.b $4
	dc.b $F4, $D, $0, $0, $F8
	dc.b $F4, $1, $0, $8, $18
	dc.b $FC, $1, $0, $A, $F0
	dc.b $4, $8, $0, $C, $F8
MightyMap_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $F4, $5, $0, $8, $A
	dc.b $4, $C, $0, $C, $F2
MightyMap_3E: dc.b $3
	dc.b $F5, $D, $0, $0, $E5
	dc.b $FD, $1, $0, $8, $5
	dc.b $5, $8, $0, $A, $ED
MightyMap_3F: dc.b $4
	dc.b $F5, $D, $0, $0, $F8
	dc.b $F5, $1, $0, $8, $18
	dc.b $FD, $1, $0, $A, $F0
	dc.b $5, $8, $0, $C, $F8
MightyMap_40: dc.b $2
	dc.b $E9, $B, $0, $0, $F3
	dc.b $9, $5, $0, $C, $F3
MightyMap_41: dc.b $2
	dc.b $F8, $E, $0, $0, $EC
	dc.b $0, $1, $0, $C, $C
MightyMap_42: dc.b $2
	dc.b $F8, $E, $0, $0, $EB
	dc.b $0, $1, $0, $C, $B
MightyMap_43: dc.b $4
	dc.b $E9, $F, $0, $0, $F0
	dc.b $F1, $1, $0, $10, $10
	dc.b $9, $8, $0, $12, $F8
	dc.b $11, $4, $0, $15, $F8
MightyMap_44: dc.b $4
	dc.b $E8, $F, $0, $0, $F0
	dc.b $E8, $1, $0, $10, $10
	dc.b $8, $8, $0, $12, $F8
	dc.b $10, $4, $0, $15, $F8
MightyMap_45: dc.b $2
	dc.b $F0, $F, $0, $0, $EE
	dc.b $10, $C, $0, $10, $EE
MightyMap_46: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
MightyMap_47: dc.b $2
	dc.b $F0, $F, $0, $0, $EF
	dc.b $10, $8, $0, $10, $EF
MightyMap_48: dc.b $2
	dc.b $EE, $B, $0, $0, $F3
	dc.b $E, $4, $0, $C, $F3
MightyMap_49: dc.b $3
	dc.b $EE, $B, $0, $0, $F3
	dc.b $F6, $3, $0, $C, $B
	dc.b $E, $8, $0, $10, $F3
MightyMap_4A: dc.b $3
	dc.b $EB, $B, $0, $0, $F2
	dc.b $B, $8, $0, $C, $F2
	dc.b $13, $4, $0, $F, $FA
MightyMap_4B: dc.b $5
	dc.b $EA, $D, $0, $0, $F2
	dc.b $EA, $1, $0, $8, $12
	dc.b $FA, $A, $0, $A, $F2
	dc.b $2, $1, $0, $13, $A
	dc.b $12, $0, $0, $15, $F2
MightyMap_4C: dc.b $5
	dc.b $E9, $D, $0, $0, $F2
	dc.b $E9, $1, $0, $8, $12
	dc.b $F9, $A, $0, $A, $F2
	dc.b $9, $0, $0, $13, $A
	dc.b $11, $0, $0, $14, $F2
MightyMap_4D: dc.b $5
	dc.b $EA, $D, $0, $0, $F4
	dc.b $EA, $1, $0, $8, $14
	dc.b $FA, $A, $0, $A, $F4
	dc.b $2, $1, $0, $13, $C
	dc.b $12, $0, $0, $15, $F4
MightyMap_4E: dc.b $3
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $8
	dc.b $C, $8, $0, $10, $F0
MightyMap_4F: dc.b $3
	dc.b $EE, $B, $0, $0, $F2
	dc.b $F6, $2, $0, $C, $A
	dc.b $E, $8, $0, $F, $F2
MightyMap_50: dc.b $2
	dc.b $F2, $7, $0, $0, $F5
	dc.b $FA, $2, $0, $8, $5
MightyMap_51: dc.b $1
	dc.b $F7, $6, $0, $0, $F9
MightyMap_52: dc.b $1
	dc.b $FB, $1, $0, $0, $FC
MightyMap_53: dc.b $4
	dc.b $F4, $D, $0, $0, $E4
	dc.b $F4, $2, $0, $8, $4
	dc.b $FC, $1, $0, $B, $C
	dc.b $4, $8, $0, $D, $EC
MightyMap_54: dc.b $3
	dc.b $F5, $D, $0, $0, $FC
	dc.b $FD, $1, $0, $8, $F4
	dc.b $5, $8, $0, $A, $FC
MightyMap_55: dc.b $3
	dc.b $F3, $E, $0, $0, $EC
	dc.b $F3, $3, $0, $C, $C
	dc.b $B, $8, $0, $10, $F4
MightyMap_56: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $FE, $1, $0, $10, $E
	dc.b $E, $4, $0, $12, $EE
	dc.b $E, $0, $0, $14, $6
MightyMap_57: dc.b $3
	dc.b $F3, $E, $0, $0, $EC
	dc.b $F3, $3, $0, $C, $C
	dc.b $B, $8, $0, $10, $F4
MightyMap_58: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_59: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_5A: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_5B: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_5C: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_5D: dc.b $2
	dc.b $F9, $E, $0, $0, $F4
	dc.b $11, $8, $0, $C, $F4
MightyMap_5E: dc.b $2
	dc.b $F3, $F, $0, $0, $F7
	dc.b $FB, $6, $0, $10, $E7
MightyMap_5F: dc.b $3
	dc.b $F4, $F, $0, $0, $F4
	dc.b $FC, $2, $0, $10, $EC
	dc.b $FC, $0, $0, $13, $14
MightyMap_60: dc.b $2
	dc.b $F3, $F, $0, $0, $F7
	dc.b $FB, $6, $0, $10, $E7
MightyMap_61: dc.b $2
	dc.b $F4, $F, $0, $0, $F5
	dc.b $FC, $1, $0, $10, $ED
MightyMap_62: dc.b $3
	dc.b $F9, $B, $0, $0, $EF
	dc.b $E9, $9, $0, $C, $F7
	dc.b $F9, $5, $0, $12, $7
MightyMap_63: dc.b $4
	dc.b $F4, $F, $0, $0, $EF
	dc.b $EC, $8, $0, $10, $F7
	dc.b $E4, $0, $0, $13, $FF
	dc.b $FC, $1, $0, $14, $F
MightyMap_64: dc.b $4
	dc.b $F4, $F, $0, $0, $EF
	dc.b $EC, $8, $0, $10, $F7
	dc.b $14, $0, $0, $13, $F7
	dc.b $F4, $2, $0, $14, $F
MightyMap_65: dc.b $4
	dc.b $FA, $E, $0, $0, $F0
	dc.b $EA, $9, $0, $C, $F8
	dc.b $E2, $0, $0, $12, $0
	dc.b $FA, $1, $0, $13, $10
MightyMap_66: dc.b $2
	dc.b $E7, $F, $0, $0, $F0
	dc.b $7, $8, $0, $10, $F8
MightyMap_67: dc.b $2
	dc.b $E7, $F, $0, $0, $F1
	dc.b $7, $8, $0, $10, $F9
MightyMap_68: dc.b $2
	dc.b $E7, $F, $0, $0, $F0
	dc.b $7, $8, $0, $10, $F8
MightyMap_69: dc.b $2
	dc.b $E7, $F, $0, $0, $F1
	dc.b $7, $4, $0, $10, $F9
MightyMap_6A: dc.b $3
	dc.b $E6, $F, $0, $0, $E8
	dc.b $6, $8, $0, $10, $F8
	dc.b $F6, $1, $0, $13, $8
MightyMap_6B: dc.b $4
	dc.b $E9, $F, $0, $0, $E9
	dc.b $F1, $0, $0, $10, $E1
	dc.b $F1, $2, $0, $11, $9
	dc.b $9, $0, $0, $14, $1
MightyMap_6C: dc.b $4
	dc.b $E6, $F, $0, $0, $E9
	dc.b $6, $4, $0, $10, $F9
	dc.b $EE, $2, $0, $12, $9
	dc.b $F6, $1, $0, $15, $11
MightyMap_6D: dc.b $3
	dc.b $E6, $F, $0, $0, $E7
	dc.b $6, $8, $0, $10, $F7
	dc.b $EE, $2, $0, $13, $7
MightyMap_6E: dc.b $1
	dc.b $F5, $F, $0, $0, $EF
	even