; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 14 2018 19:36:54 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAQOYJ58NY49:
	dc.w DATAQOYJ58NY49_0-DATAQOYJ58NY49, DATAQOYJ58NY49_1-DATAQOYJ58NY49
	dc.w DATAQOYJ58NY49_2-DATAQOYJ58NY49, DATAQOYJ58NY49_3-DATAQOYJ58NY49
	dc.w DATAQOYJ58NY49_4-DATAQOYJ58NY49
DATAQOYJ58NY49_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $C, $FC
DATAQOYJ58NY49_1: dc.b $2
	dc.b $F0, $F, $0, $E, $F0
	dc.b $10, $1, $0, $C, $FC
DATAQOYJ58NY49_2: dc.b $5
	dc.b $10, $1, $0, $C, $FC
	dc.b $F0, $0, $0, $1E, $FC
	dc.b $8, $0, $0, $1F, $FC
	dc.b $F8, $0, $0, $20, $FC
	dc.b $0, $0, $0, $20, $FC
DATAQOYJ58NY49_3: dc.b $2
	dc.b $F0, $F, $8, $E, $F0
	dc.b $10, $1, $0, $C, $FC
DATAQOYJ58NY49_4: dc.b $3
	dc.b $F0, $B, $0, $21, $E8
	dc.b $F0, $B, $0, $2D, $0
	dc.b $10, $1, $0, $C, $FC
	even