; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 14 2018 20:01:01 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5VOLMCGEKYL:
	dc.w DATA5VOLMCGEKYL_0-DATA5VOLMCGEKYL, DATA5VOLMCGEKYL_1-DATA5VOLMCGEKYL
	dc.w DATA5VOLMCGEKYL_2-DATA5VOLMCGEKYL, DATA5VOLMCGEKYL_3-DATA5VOLMCGEKYL
	dc.w DATA5VOLMCGEKYL_4-DATA5VOLMCGEKYL
DATA5VOLMCGEKYL_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $C, $FC
DATA5VOLMCGEKYL_1: dc.b $2
	dc.b $F0, $F, $0, $E, $F0
	dc.b $10, $1, $0, $C, $FC
DATA5VOLMCGEKYL_2: dc.b $5
	dc.b $10, $1, $0, $C, $FC
	dc.b $F0, $0, $0, $1E, $FC
	dc.b $8, $0, $0, $1F, $FC
	dc.b $F8, $0, $0, $20, $FC
	dc.b $0, $0, $0, $20, $FC
DATA5VOLMCGEKYL_3: dc.b $2
	dc.b $F0, $F, $8, $E, $F0
	dc.b $10, $1, $0, $C, $FC
DATA5VOLMCGEKYL_4: dc.b $3
	dc.b $F0, $B, $0, $21, $E8
	dc.b $F0, $B, $0, $2D, $0
	dc.b $10, $1, $0, $C, $FC
	even