; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat May 12 2018 15:25:41 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAZKEU3ARWEUI:
	dc.w DATAZKEU3ARWEUI_0-DATAZKEU3ARWEUI, DATAZKEU3ARWEUI_1-DATAZKEU3ARWEUI
	dc.w DATAZKEU3ARWEUI_2-DATAZKEU3ARWEUI, DATAZKEU3ARWEUI_3-DATAZKEU3ARWEUI
	dc.w DATAZKEU3ARWEUI_4-DATAZKEU3ARWEUI, DATAZKEU3ARWEUI_5-DATAZKEU3ARWEUI
	dc.w DATAZKEU3ARWEUI_6-DATAZKEU3ARWEUI
DATAZKEU3ARWEUI_0: dc.b $4
	dc.b $F0, $9, $0, $0, $E8
	dc.b $F0, $9, $8, $0, $0
	dc.b $0, $5, $0, $6, $F0
	dc.b $0, $5, $8, $6, $0
DATAZKEU3ARWEUI_1: dc.b $4
	dc.b $F0, $9, $0, $A, $E8
	dc.b $F0, $9, $0, $10, $0
	dc.b $0, $5, $0, $16, $F0
	dc.b $0, $9, $0, $1A, $0
DATAZKEU3ARWEUI_2: dc.b $4
	dc.b $EC, $9, $0, $0, $E8
	dc.b $EC, $9, $8, $0, $0
	dc.b $FC, $5, $8, $6, $0
	dc.b $FC, $6, $0, $20, $F0
DATAZKEU3ARWEUI_3: dc.b $4
	dc.b $EC, $9, $0, $A, $E8
	dc.b $EC, $9, $0, $10, $0
	dc.b $FC, $9, $0, $26, $0
	dc.b $FC, $6, $0, $2C, $F0
DATAZKEU3ARWEUI_4: dc.b $6
	dc.b $F0, $4, $0, $32, $F0
	dc.b $F0, $4, $8, $32, $0
	dc.b $F8, $9, $0, $34, $E8
	dc.b $F8, $9, $8, $34, $0
	dc.b $8, $4, $0, $3A, $F0
	dc.b $8, $4, $8, $3A, $0
DATAZKEU3ARWEUI_5: dc.b $1
	dc.b $F8, $5, $0, $3C, $F8
DATAZKEU3ARWEUI_6: dc.b $1
	dc.b $F8, $5, $0, $40, $F8
	even