; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 22 2021 16:50:20 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAZ52SC1UYDVR:
	dc.w DATAZ52SC1UYDVR_0-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_1-DATAZ52SC1UYDVR
	dc.w DATAZ52SC1UYDVR_2-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_3-DATAZ52SC1UYDVR
	dc.w DATAZ52SC1UYDVR_4-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_5-DATAZ52SC1UYDVR
	dc.w DATAZ52SC1UYDVR_6-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_7-DATAZ52SC1UYDVR
	dc.w DATAZ52SC1UYDVR_8-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_9-DATAZ52SC1UYDVR
	dc.w DATAZ52SC1UYDVR_A-DATAZ52SC1UYDVR, DATAZ52SC1UYDVR_B-DATAZ52SC1UYDVR
DATAZ52SC1UYDVR_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_1: dc.b $2
	dc.b $F2, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_2: dc.b $2
	dc.b $F2, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_3: dc.b $2
	dc.b $F2, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_4: dc.b $2
	dc.b $F2, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_5: dc.b $2
	dc.b $F2, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_6: dc.b $2
	dc.b $F2, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_7: dc.b $2
	dc.b $F2, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_8: dc.b $2
	dc.b $F2, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_9: dc.b $2
	dc.b $F2, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_A: dc.b $2
	dc.b $F2, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAZ52SC1UYDVR_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even