; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon May 07 2018 19:32:29 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA1GGKZZADPTV:
	dc.w DATA1GGKZZADPTV_0-DATA1GGKZZADPTV, DATA1GGKZZADPTV_1-DATA1GGKZZADPTV
	dc.w DATA1GGKZZADPTV_2-DATA1GGKZZADPTV, DATA1GGKZZADPTV_3-DATA1GGKZZADPTV
	dc.w DATA1GGKZZADPTV_4-DATA1GGKZZADPTV, DATA1GGKZZADPTV_5-DATA1GGKZZADPTV
	dc.w DATA1GGKZZADPTV_6-DATA1GGKZZADPTV, DATA1GGKZZADPTV_7-DATA1GGKZZADPTV
	dc.w DATA1GGKZZADPTV_8-DATA1GGKZZADPTV, DATA1GGKZZADPTV_9-DATA1GGKZZADPTV
	dc.w DATA1GGKZZADPTV_A-DATA1GGKZZADPTV, DATA1GGKZZADPTV_B-DATA1GGKZZADPTV
DATA1GGKZZADPTV_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_2: dc.b $2
	dc.b $F2, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_3: dc.b $2
	dc.b $F2, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_4: dc.b $2
	dc.b $F2, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_5: dc.b $2
	dc.b $F2, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_6: dc.b $2
	dc.b $F2, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_7: dc.b $2
	dc.b $F2, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_8: dc.b $2
	dc.b $F2, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_9: dc.b $2
	dc.b $F2, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_A: dc.b $2
	dc.b $F2, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA1GGKZZADPTV_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even