; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 29 2018 10:53:26 GMT-0400 (Eastern Daylight Time)
; ================================================================================

GHZROCK:
	dc.w GHZROCK_0-GHZROCK
GHZROCK_0: dc.b $2
	dc.b $F0, $B, $60, $0, $E8
	dc.b $F0, $B, $60, $C, $0
	even