; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 25 2018 17:30:57 GMT-0400 (Eastern Daylight Time)
; ================================================================================

Sonic_Map:
	dc.w $0, Sonic_Map_1-Sonic_Map
	dc.w Sonic_Map_2-Sonic_Map, Sonic_Map_3-Sonic_Map
	dc.w Sonic_Map_4-Sonic_Map, Sonic_Map_5-Sonic_Map
	dc.w Sonic_Map_6-Sonic_Map, Sonic_Map_7-Sonic_Map
	dc.w Sonic_Map_8-Sonic_Map, Sonic_Map_9-Sonic_Map
	dc.w Sonic_Map_A-Sonic_Map, Sonic_Map_B-Sonic_Map
	dc.w Sonic_Map_C-Sonic_Map, Sonic_Map_D-Sonic_Map
	dc.w Sonic_Map_E-Sonic_Map, Sonic_Map_F-Sonic_Map
	dc.w Sonic_Map_10-Sonic_Map, Sonic_Map_11-Sonic_Map
	dc.w Sonic_Map_12-Sonic_Map, Sonic_Map_13-Sonic_Map
	dc.w Sonic_Map_14-Sonic_Map, Sonic_Map_15-Sonic_Map
	dc.w Sonic_Map_16-Sonic_Map, Sonic_Map_17-Sonic_Map
	dc.w Sonic_Map_18-Sonic_Map, Sonic_Map_19-Sonic_Map
	dc.w Sonic_Map_1A-Sonic_Map, Sonic_Map_1B-Sonic_Map
	dc.w Sonic_Map_1C-Sonic_Map, Sonic_Map_1D-Sonic_Map
	dc.w Sonic_Map_1E-Sonic_Map, Sonic_Map_1F-Sonic_Map
	dc.w Sonic_Map_20-Sonic_Map, Sonic_Map_21-Sonic_Map
	dc.w Sonic_Map_22-Sonic_Map, Sonic_Map_23-Sonic_Map
	dc.w Sonic_Map_24-Sonic_Map, Sonic_Map_25-Sonic_Map
	dc.w Sonic_Map_26-Sonic_Map, Sonic_Map_27-Sonic_Map
	dc.w Sonic_Map_28-Sonic_Map, Sonic_Map_29-Sonic_Map
	dc.w Sonic_Map_2A-Sonic_Map, Sonic_Map_2B-Sonic_Map
	dc.w Sonic_Map_2C-Sonic_Map, Sonic_Map_2D-Sonic_Map
	dc.w Sonic_Map_2E-Sonic_Map, Sonic_Map_2F-Sonic_Map
	dc.w Sonic_Map_30-Sonic_Map, Sonic_Map_31-Sonic_Map
	dc.w Sonic_Map_32-Sonic_Map, Sonic_Map_33-Sonic_Map
	dc.w Sonic_Map_34-Sonic_Map, Sonic_Map_35-Sonic_Map
	dc.w Sonic_Map_36-Sonic_Map, Sonic_Map_37-Sonic_Map
	dc.w Sonic_Map_38-Sonic_Map, Sonic_Map_39-Sonic_Map
	dc.w Sonic_Map_3A-Sonic_Map, Sonic_Map_3B-Sonic_Map
	dc.w Sonic_Map_3C-Sonic_Map, Sonic_Map_3D-Sonic_Map
	dc.w Sonic_Map_3E-Sonic_Map, Sonic_Map_3F-Sonic_Map
	dc.w Sonic_Map_40-Sonic_Map, Sonic_Map_41-Sonic_Map
	dc.w Sonic_Map_42-Sonic_Map, Sonic_Map_43-Sonic_Map
	dc.w Sonic_Map_44-Sonic_Map, Sonic_Map_45-Sonic_Map
	dc.w Sonic_Map_46-Sonic_Map, Sonic_Map_47-Sonic_Map
	dc.w Sonic_Map_48-Sonic_Map, Sonic_Map_49-Sonic_Map
	dc.w Sonic_Map_4A-Sonic_Map, Sonic_Map_4B-Sonic_Map
	dc.w Sonic_Map_4C-Sonic_Map, Sonic_Map_4D-Sonic_Map
	dc.w Sonic_Map_4E-Sonic_Map, Sonic_Map_4F-Sonic_Map
	dc.w Sonic_Map_50-Sonic_Map, Sonic_Map_51-Sonic_Map
	dc.w Sonic_Map_52-Sonic_Map, Sonic_Map_53-Sonic_Map
	dc.w Sonic_Map_54-Sonic_Map, Sonic_Map_55-Sonic_Map
	dc.w Sonic_Map_56-Sonic_Map, Sonic_Map_57-Sonic_Map
	dc.w Sonic_Map_58-Sonic_Map, Sonic_Map_59-Sonic_Map
	dc.w Sonic_Map_5A-Sonic_Map, Sonic_Map_5B-Sonic_Map
	dc.w Sonic_Map_5C-Sonic_Map, Sonic_Map_5D-Sonic_Map
	dc.w Sonic_Map_5E-Sonic_Map, Sonic_Map_5F-Sonic_Map
	dc.w Sonic_Map_60-Sonic_Map, Sonic_Map_61-Sonic_Map
	dc.w Sonic_Map_62-Sonic_Map, Sonic_Map_63-Sonic_Map
	dc.w Sonic_Map_64-Sonic_Map, Sonic_Map_65-Sonic_Map
	dc.w Sonic_Map_66-Sonic_Map, Sonic_Map_67-Sonic_Map
	dc.w Sonic_Map_68-Sonic_Map, Sonic_Map_69-Sonic_Map
	dc.w Sonic_Map_6A-Sonic_Map, Sonic_Map_6B-Sonic_Map
	dc.w Sonic_Map_6C-Sonic_Map, Sonic_Map_6D-Sonic_Map
Sonic_Map_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
Sonic_Map_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Sonic_Map_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Sonic_Map_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
Sonic_Map_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
Sonic_Map_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
Sonic_Map_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
Sonic_Map_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
Sonic_Map_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
Sonic_Map_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
Sonic_Map_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
Sonic_Map_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
Sonic_Map_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
Sonic_Map_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
Sonic_Map_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
Sonic_Map_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
Sonic_Map_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
Sonic_Map_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
Sonic_Map_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
Sonic_Map_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
Sonic_Map_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
Sonic_Map_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
Sonic_Map_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
Sonic_Map_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
Sonic_Map_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
Sonic_Map_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
Sonic_Map_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
Sonic_Map_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
Sonic_Map_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
Sonic_Map_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Sonic_Map_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Sonic_Map_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Sonic_Map_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
Sonic_Map_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
Sonic_Map_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
Sonic_Map_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
Sonic_Map_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
Sonic_Map_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Sonic_Map_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Sonic_Map_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Sonic_Map_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
Sonic_Map_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
Sonic_Map_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
Sonic_Map_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
Sonic_Map_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
Sonic_Map_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
Sonic_Map_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
Sonic_Map_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Sonic_Map_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
Sonic_Map_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
Sonic_Map_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
Sonic_Map_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
Sonic_Map_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
Sonic_Map_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
Sonic_Map_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
Sonic_Map_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
Sonic_Map_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
Sonic_Map_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
Sonic_Map_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
Sonic_Map_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
Sonic_Map_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
Sonic_Map_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
Sonic_Map_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Sonic_Map_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Sonic_Map_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Sonic_Map_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Sonic_Map_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
Sonic_Map_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
Sonic_Map_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
Sonic_Map_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
Sonic_Map_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
Sonic_Map_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
Sonic_Map_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
Sonic_Map_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
Sonic_Map_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
Sonic_Map_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
Sonic_Map_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
Sonic_Map_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
Sonic_Map_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
Sonic_Map_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
Sonic_Map_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
Sonic_Map_58: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_59: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_5A: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_5B: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_5C: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_5D: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
Sonic_Map_5E: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
Sonic_Map_5F: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
Sonic_Map_60: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
Sonic_Map_61: dc.b $6
	dc.b $B, $C, $0, $0, $F5
	dc.b $3, $C, $0, $4, $ED
	dc.b $3, $0, $0, $8, $D
	dc.b $FB, $C, $0, $9, $ED
	dc.b $FB, $0, $0, $D, $D
	dc.b $F3, $C, $0, $E, $F5
Sonic_Map_62: dc.b $8
	dc.b $C, $8, $0, $0, $F0
	dc.b $4, $C, $0, $3, $F0
	dc.b $4, $0, $0, $7, $10
	dc.b $FC, $C, $0, $8, $F0
	dc.b $FC, $0, $0, $C, $10
	dc.b $F4, $C, $0, $D, $F0
	dc.b $F4, $0, $0, $11, $10
	dc.b $EC, $8, $0, $12, $F8
Sonic_Map_63: dc.b $7
	dc.b $B, $C, $0, $0, $F0
	dc.b $3, $C, $0, $4, $F0
	dc.b $3, $0, $0, $8, $10
	dc.b $FB, $C, $0, $9, $F0
	dc.b $FB, $0, $0, $D, $10
	dc.b $F3, $C, $0, $E, $F0
	dc.b $EB, $C, $0, $12, $F0
Sonic_Map_64: dc.b $9
	dc.b $E, $8, $0, $0, $F0
	dc.b $6, $C, $0, $3, $F0
	dc.b $6, $0, $0, $7, $10
	dc.b $FE, $C, $0, $8, $F0
	dc.b $FE, $0, $0, $C, $10
	dc.b $F6, $C, $0, $D, $F0
	dc.b $F6, $0, $0, $11, $10
	dc.b $EE, $C, $0, $12, $F0
	dc.b $E6, $0, $0, $16, $0
Sonic_Map_65: dc.b $7
	dc.b $A, $C, $0, $0, $F0
	dc.b $2, $C, $0, $4, $F0
	dc.b $2, $0, $0, $8, $10
	dc.b $FA, $C, $0, $9, $F0
	dc.b $FA, $0, $0, $D, $10
	dc.b $F2, $C, $0, $E, $F0
	dc.b $EA, $8, $0, $12, $F8
Sonic_Map_66: dc.b $5
	dc.b $7, $8, $0, $0, $F9
	dc.b $FF, $C, $0, $3, $F1
	dc.b $F7, $C, $0, $7, $F1
	dc.b $EF, $C, $0, $B, $F1
	dc.b $E7, $C, $0, $F, $F1
Sonic_Map_67: dc.b $5
	dc.b $7, $8, $0, $0, $F8
	dc.b $FF, $C, $0, $3, $F0
	dc.b $F7, $C, $0, $7, $F0
	dc.b $EF, $C, $0, $B, $F0
	dc.b $E7, $C, $0, $F, $F0
Sonic_Map_68: dc.b $5
	dc.b $7, $8, $0, $0, $F9
	dc.b $FF, $C, $0, $3, $F1
	dc.b $F7, $C, $0, $7, $F1
	dc.b $EF, $C, $0, $B, $F1
	dc.b $E7, $C, $0, $F, $F1
Sonic_Map_69: dc.b $5
	dc.b $6, $4, $0, $0, $F8
	dc.b $FE, $C, $0, $2, $F0
	dc.b $F6, $C, $0, $6, $F0
	dc.b $EE, $C, $0, $A, $F0
	dc.b $E6, $C, $0, $E, $F0
Sonic_Map_6A: dc.b $8
	dc.b $3, $C, $0, $0, $F0
	dc.b $3, $0, $0, $4, $10
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $4, $0, $9, $8
	dc.b $F3, $C, $0, $B, $E8
	dc.b $F3, $0, $0, $F, $8
	dc.b $EB, $C, $0, $10, $E8
	dc.b $E3, $8, $0, $14, $F0
Sonic_Map_6B: dc.b $9
	dc.b $3, $C, $0, $0, $E8
	dc.b $3, $0, $0, $4, $8
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $0, $0, $9, $8
	dc.b $F3, $C, $0, $A, $E8
	dc.b $F3, $0, $0, $E, $8
	dc.b $EB, $C, $0, $F, $E8
	dc.b $EB, $0, $0, $13, $8
	dc.b $E3, $4, $0, $14, $F8
Sonic_Map_6C: dc.b $9
	dc.b $3, $C, $0, $0, $F0
	dc.b $3, $0, $0, $4, $10
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $4, $0, $9, $8
	dc.b $F3, $C, $0, $B, $E8
	dc.b $F3, $0, $0, $F, $8
	dc.b $EB, $C, $0, $10, $E8
	dc.b $EB, $0, $0, $14, $8
	dc.b $E3, $8, $0, $15, $F0
Sonic_Map_6D: dc.b $9
	dc.b $3, $C, $0, $0, $E8
	dc.b $3, $0, $0, $4, $8
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $0, $0, $9, $8
	dc.b $F3, $C, $0, $A, $E8
	dc.b $F3, $0, $0, $E, $8
	dc.b $EB, $C, $0, $F, $E8
	dc.b $EB, $0, $0, $13, $8
	dc.b $E3, $4, $0, $14, $F8
	even