; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Jan 22 2021 20:37:00 GMT-0500 (Eastern Standard Time)
; ================================================================================

Shadow_Map:
	dc.w $0, Shadow_Map_1-Shadow_Map
	dc.w Shadow_Map_2-Shadow_Map, Shadow_Map_3-Shadow_Map
	dc.w Shadow_Map_4-Shadow_Map, Shadow_Map_5-Shadow_Map
	dc.w Shadow_Map_6-Shadow_Map, Shadow_Map_7-Shadow_Map
	dc.w Shadow_Map_8-Shadow_Map, Shadow_Map_9-Shadow_Map
	dc.w Shadow_Map_A-Shadow_Map, Shadow_Map_B-Shadow_Map
	dc.w Shadow_Map_C-Shadow_Map, Shadow_Map_D-Shadow_Map
	dc.w Shadow_Map_E-Shadow_Map, Shadow_Map_F-Shadow_Map
	dc.w Shadow_Map_10-Shadow_Map, Shadow_Map_11-Shadow_Map
	dc.w Shadow_Map_12-Shadow_Map, Shadow_Map_13-Shadow_Map
	dc.w Shadow_Map_14-Shadow_Map, Shadow_Map_15-Shadow_Map
	dc.w Shadow_Map_16-Shadow_Map, Shadow_Map_17-Shadow_Map
	dc.w Shadow_Map_18-Shadow_Map, Shadow_Map_19-Shadow_Map
	dc.w Shadow_Map_1A-Shadow_Map, Shadow_Map_1B-Shadow_Map
	dc.w Shadow_Map_1C-Shadow_Map, Shadow_Map_1D-Shadow_Map
	dc.w Shadow_Map_1E-Shadow_Map, Shadow_Map_1F-Shadow_Map
	dc.w Shadow_Map_20-Shadow_Map, Shadow_Map_21-Shadow_Map
	dc.w Shadow_Map_22-Shadow_Map, Shadow_Map_23-Shadow_Map
	dc.w Shadow_Map_24-Shadow_Map, Shadow_Map_25-Shadow_Map
	dc.w Shadow_Map_26-Shadow_Map, Shadow_Map_27-Shadow_Map
	dc.w Shadow_Map_28-Shadow_Map, Shadow_Map_29-Shadow_Map
	dc.w Shadow_Map_2A-Shadow_Map, Shadow_Map_2B-Shadow_Map
	dc.w Shadow_Map_2C-Shadow_Map, Shadow_Map_2D-Shadow_Map
	dc.w Shadow_Map_2E-Shadow_Map, Shadow_Map_2F-Shadow_Map
	dc.w Shadow_Map_30-Shadow_Map, Shadow_Map_31-Shadow_Map
	dc.w Shadow_Map_32-Shadow_Map, Shadow_Map_33-Shadow_Map
	dc.w Shadow_Map_34-Shadow_Map, Shadow_Map_35-Shadow_Map
	dc.w Shadow_Map_36-Shadow_Map, Shadow_Map_37-Shadow_Map
	dc.w Shadow_Map_38-Shadow_Map, Shadow_Map_39-Shadow_Map
	dc.w Shadow_Map_3A-Shadow_Map, Shadow_Map_3B-Shadow_Map
	dc.w Shadow_Map_3C-Shadow_Map, Shadow_Map_3D-Shadow_Map
	dc.w Shadow_Map_3E-Shadow_Map, Shadow_Map_3F-Shadow_Map
	dc.w Shadow_Map_40-Shadow_Map, Shadow_Map_41-Shadow_Map
	dc.w Shadow_Map_42-Shadow_Map, Shadow_Map_43-Shadow_Map
	dc.w Shadow_Map_44-Shadow_Map, Shadow_Map_45-Shadow_Map
	dc.w Shadow_Map_46-Shadow_Map, Shadow_Map_47-Shadow_Map
	dc.w Shadow_Map_48-Shadow_Map, Shadow_Map_49-Shadow_Map
	dc.w Shadow_Map_4A-Shadow_Map, Shadow_Map_4B-Shadow_Map
	dc.w Shadow_Map_4C-Shadow_Map, Shadow_Map_4D-Shadow_Map
	dc.w Shadow_Map_4E-Shadow_Map, Shadow_Map_4F-Shadow_Map
	dc.w Shadow_Map_50-Shadow_Map, Shadow_Map_51-Shadow_Map
	dc.w Shadow_Map_52-Shadow_Map, Shadow_Map_53-Shadow_Map
	dc.w Shadow_Map_54-Shadow_Map, Shadow_Map_55-Shadow_Map
	dc.w Shadow_Map_56-Shadow_Map, Shadow_Map_57-Shadow_Map
	dc.w Shadow_Map_58-Shadow_Map, Shadow_Map_59-Shadow_Map
	dc.w Shadow_Map_5A-Shadow_Map, Shadow_Map_5B-Shadow_Map
	dc.w Shadow_Map_5C-Shadow_Map, Shadow_Map_5D-Shadow_Map
	dc.w Shadow_Map_5E-Shadow_Map, Shadow_Map_5F-Shadow_Map
	dc.w Shadow_Map_60-Shadow_Map, Shadow_Map_61-Shadow_Map
	dc.w Shadow_Map_62-Shadow_Map, Shadow_Map_63-Shadow_Map
	dc.w Shadow_Map_64-Shadow_Map, Shadow_Map_65-Shadow_Map
	dc.w Shadow_Map_66-Shadow_Map, Shadow_Map_67-Shadow_Map
	dc.w Shadow_Map_68-Shadow_Map, Shadow_Map_69-Shadow_Map
	dc.w Shadow_Map_6A-Shadow_Map
Shadow_Map_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F8
	dc.b $C, $8, $0, $E, $F8
Shadow_Map_2: dc.b $6
	dc.b $EC, $9, $0, $0, $F1
	dc.b $C, $8, $0, $6, $F9
	dc.b $FE, $0, $0, $9, $9
	dc.b $FC, $5, $0, $A, $F9
	dc.b $FC, $0, $0, $E, $F1
	dc.b $F5, $0, $0, $F, $9
Shadow_Map_3: dc.b $6
	dc.b $C, $8, $0, $0, $F9
	dc.b $FE, $0, $0, $3, $9
	dc.b $FC, $5, $0, $4, $F9
	dc.b $FC, $0, $0, $8, $F1
	dc.b $F5, $0, $0, $9, $9
	dc.b $EC, $9, $0, $A, $F1
Shadow_Map_4: dc.b $8
	dc.b $FE, $0, $0, $0, $9
	dc.b $FC, $0, $0, $1, $F1
	dc.b $F5, $0, $0, $2, $9
	dc.b $C, $8, $0, $3, $F9
	dc.b $FC, $1, $0, $6, $F9
	dc.b $FC, $1, $0, $8, $1
	dc.b $4, $0, $0, $A, $6
	dc.b $EC, $9, $0, $B, $F1
Shadow_Map_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F1
	dc.b $4, $8, $0, $9, $F8
	dc.b $C, $8, $0, $C, $F8
Shadow_Map_6: dc.b $5
	dc.b $FB, $9, $0, $0, $ED
	dc.b $FB, $6, $0, $6, $5
	dc.b $B, $4, $0, $C, $ED
	dc.b $F3, $0, $0, $E, $ED
	dc.b $EB, $9, $0, $F, $F5
Shadow_Map_7: dc.b $4
	dc.b $EC, $9, $0, $0, $F5
	dc.b $FC, $A, $0, $6, $F5
	dc.b $FC, $0, $0, $F, $D
	dc.b $C, $0, $0, $10, $D
Shadow_Map_8: dc.b $3
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
	dc.b $F7, $0, $0, $F, $B
Shadow_Map_9: dc.b $5
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $9, $0, $6, $EB
	dc.b $FD, $6, $0, $C, $3
	dc.b $D, $4, $0, $12, $EB
	dc.b $F5, $0, $0, $14, $B
Shadow_Map_A: dc.b $3
	dc.b $EC, $9, $0, $0, $F2
	dc.b $FC, $E, $0, $6, $EB
	dc.b $F6, $0, $0, $12, $A
Shadow_Map_B: dc.b $3
	dc.b $EF, $D, $0, $0, $F3
	dc.b $F, $C, $0, $8, $F3
	dc.b $FF, $9, $0, $C, $F3
Shadow_Map_C: dc.b $6
	dc.b $F2, $D, $0, $0, $EB
	dc.b $EA, $4, $0, $8, $F3
	dc.b $2, $5, $0, $A, $F3
	dc.b $12, $0, $0, $E, $FB
	dc.b $2, $0, $0, $F, $3
	dc.b $F2, $1, $0, $10, $B
Shadow_Map_D: dc.b $5
	dc.b $EB, $7, $0, $0, $F4
	dc.b $F3, $1, $0, $8, $EC
	dc.b $F3, $3, $0, $A, $4
	dc.b $FB, $5, $0, $E, $C
	dc.b $B, $0, $0, $12, $FC
Shadow_Map_E: dc.b $7
	dc.b $F9, $C, $0, $0, $E9
	dc.b $F1, $8, $0, $4, $F1
	dc.b $1, $C, $0, $7, $F1
	dc.b $E9, $0, $0, $B, $F9
	dc.b $9, $8, $0, $C, $F9
	dc.b $11, $0, $0, $F, $1
	dc.b $1, $0, $0, $10, $11
Shadow_Map_F: dc.b $5
	dc.b $EC, $B, $0, $0, $ED
	dc.b $C, $8, $0, $C, $F5
	dc.b $14, $4, $0, $F, $FD
	dc.b $F4, $5, $0, $11, $5
	dc.b $4, $0, $0, $15, $5
Shadow_Map_10: dc.b $4
	dc.b $EF, $E, $0, $0, $EB
	dc.b $E7, $0, $0, $C, $FB
	dc.b $7, $5, $0, $D, $FB
	dc.b $FF, $1, $0, $11, $B
Shadow_Map_11: dc.b $6
	dc.b $F4, $D, $0, $0, $EF
	dc.b $EC, $4, $0, $8, $F7
	dc.b $4, $C, $0, $A, $F7
	dc.b $C, $4, $0, $E, $FF
	dc.b $FC, $0, $0, $10, $F
	dc.b $4, $0, $0, $11, $17
Shadow_Map_12: dc.b $3
	dc.b $F3, $F, $0, $0, $ED
	dc.b $EB, $8, $0, $10, $F5
	dc.b $B, $0, $0, $13, $D
Shadow_Map_13: dc.b $3
	dc.b $F4, $E, $0, $0, $EC
	dc.b $EC, $0, $0, $C, $FC
	dc.b $EC, $3, $0, $D, $C
Shadow_Map_14: dc.b $3
	dc.b $F5, $E, $0, $0, $EF
	dc.b $ED, $0, $0, $C, $F7
	dc.b $FD, $1, $0, $D, $F
Shadow_Map_15: dc.b $4
	dc.b $F2, $F, $0, $0, $EC
	dc.b $EA, $4, $0, $10, $4
	dc.b $F2, $0, $0, $12, $C
	dc.b $2, $1, $0, $13, $C
Shadow_Map_16: dc.b $4
	dc.b $F5, $E, $0, $0, $EE
	dc.b $ED, $0, $0, $C, $F6
	dc.b $D, $4, $0, $D, $6
	dc.b $F5, $1, $0, $F, $E
Shadow_Map_17: dc.b $3
	dc.b $F5, $E, $0, $0, $EF
	dc.b $ED, $0, $0, $C, $F7
	dc.b $ED, $3, $0, $D, $F
Shadow_Map_18: dc.b $6
	dc.b $FD, $D, $0, $0, $EB
	dc.b $ED, $5, $0, $8, $F3
	dc.b $D, $4, $0, $C, $F3
	dc.b $F5, $0, $0, $E, $3
	dc.b $FD, $4, $0, $F, $B
	dc.b $5, $0, $0, $11, $B
Shadow_Map_19: dc.b $5
	dc.b $FD, $D, $0, $0, $EA
	dc.b $F5, $C, $0, $8, $F2
	dc.b $D, $4, $0, $C, $F2
	dc.b $E5, $5, $0, $E, $FA
	dc.b $FD, $0, $0, $12, $A
Shadow_Map_1A: dc.b $7
	dc.b $E7, $3, $0, $0, $2
	dc.b $EF, $2, $0, $4, $A
	dc.b $F7, $6, $0, $7, $F2
	dc.b $F7, $0, $0, $D, $12
	dc.b $FF, $0, $0, $E, $EA
	dc.b $7, $0, $0, $F, $2
	dc.b $F, $0, $0, $10, $FA
Shadow_Map_1B: dc.b $5
	dc.b $FA, $E, $0, $0, $EB
	dc.b $EA, $5, $0, $C, $F3
	dc.b $F2, $8, $0, $10, $3
	dc.b $FA, $4, $0, $13, $B
	dc.b $2, $0, $0, $15, $B
Shadow_Map_1C: dc.b $4
	dc.b $F3, $E, $0, $0, $EC
	dc.b $B, $8, $0, $C, $EC
	dc.b $EB, $4, $0, $F, $FC
	dc.b $FB, $4, $0, $11, $C
Shadow_Map_1D: dc.b $6
	dc.b $FA, $D, $0, $0, $ED
	dc.b $F2, $C, $0, $8, $F5
	dc.b $A, $4, $0, $C, $F5
	dc.b $EA, $4, $0, $E, $FD
	dc.b $E2, $0, $0, $10, $5
	dc.b $FA, $0, $0, $11, $D
Shadow_Map_1E: dc.b $4
	dc.b $EF, $9, $0, $0, $F4
	dc.b $FF, $E, $0, $6, $EC
	dc.b $EF, $1, $0, $12, $EC
	dc.b $FF, $0, $0, $14, $C
Shadow_Map_1F: dc.b $3
	dc.b $FE, $E, $0, $0, $F2
	dc.b $EE, $1, $0, $C, $F2
	dc.b $EE, $5, $0, $E, $FA
Shadow_Map_20: dc.b $6
	dc.b $FF, $E, $0, $0, $EE
	dc.b $EF, $1, $0, $C, $EE
	dc.b $EF, $5, $0, $E, $F6
	dc.b $EF, $1, $0, $12, $6
	dc.b $FF, $0, $0, $14, $E
	dc.b $7, $1, $0, $15, $E
Shadow_Map_21: dc.b $6
	dc.b $FF, $E, $0, $0, $ED
	dc.b $EF, $1, $0, $C, $ED
	dc.b $EF, $5, $0, $E, $F5
	dc.b $EF, $1, $0, $12, $5
	dc.b $FF, $0, $0, $14, $D
	dc.b $10, $0, $0, $15, $D
Shadow_Map_22: dc.b $2
	dc.b $EE, $9, $0, $0, $F7
	dc.b $FE, $E, $0, $6, $EF
Shadow_Map_23: dc.b $4
	dc.b $EE, $9, $0, $0, $F3
	dc.b $FE, $E, $0, $6, $EE
	dc.b $F7, $0, $0, $12, $B
	dc.b $0, $0, $0, $13, $E
Shadow_Map_24: dc.b $4
	dc.b $F0, $9, $0, $0, $F3
	dc.b $0, $E, $0, $6, $EE
	dc.b $F7, $1, $0, $12, $B
	dc.b $10, $0, $0, $14, $E
Shadow_Map_25: dc.b $4
	dc.b $F0, $9, $0, $0, $F6
	dc.b $0, $E, $0, $6, $EE
	dc.b $F0, $1, $0, $12, $EE
	dc.b $10, $0, $0, $14, $E
Shadow_Map_26: dc.b $5
	dc.b $F4, $D, $0, $0, $EC
	dc.b $EC, $4, $0, $8, $F4
	dc.b $4, $C, $0, $A, $F4
	dc.b $C, $5, $0, $E, $FC
	dc.b $C, $0, $0, $12, $C
Shadow_Map_27: dc.b $4
	dc.b $F2, $E, $0, $0, $ED
	dc.b $A, $5, $0, $C, $FD
	dc.b $F2, $3, $0, $10, $D
	dc.b $FA, $1, $0, $14, $15
Shadow_Map_28: dc.b $5
	dc.b $EE, $B, $0, $0, $F1
	dc.b $F6, $1, $0, $C, $E9
	dc.b $F6, $3, $0, $E, $9
	dc.b $6, $0, $0, $12, $11
	dc.b $E, $5, $0, $13, $F9
Shadow_Map_29: dc.b $5
	dc.b $F3, $E, $0, $0, $EC
	dc.b $B, $D, $0, $C, $F4
	dc.b $1B, $0, $0, $14, $FC
	dc.b $F3, $0, $0, $15, $C
	dc.b $3, $4, $0, $16, $C
Shadow_Map_2A: dc.b $4
	dc.b $F3, $E, $0, $0, $EE
	dc.b $EB, $0, $0, $C, $F6
	dc.b $B, $5, $0, $D, $FE
	dc.b $3, $1, $0, $11, $E
Shadow_Map_2B: dc.b $6
	dc.b $F6, $D, $0, $0, $EE
	dc.b $EE, $4, $0, $8, $F6
	dc.b $6, $C, $0, $A, $F6
	dc.b $E, $5, $0, $E, $FE
	dc.b $E, $0, $0, $12, $E
	dc.b $FE, $1, $0, $13, $16
Shadow_Map_2C: dc.b $5
	dc.b $F4, $D, $0, $0, $F0
	dc.b $EC, $4, $0, $8, $F8
	dc.b $4, $A, $0, $A, $F8
	dc.b $4, $4, $0, $13, $10
	dc.b $C, $0, $0, $15, $10
Shadow_Map_2D: dc.b $5
	dc.b $F6, $D, $0, $0, $ED
	dc.b $EE, $8, $0, $8, $F5
	dc.b $6, $D, $0, $B, $F5
	dc.b $16, $0, $0, $13, $FD
	dc.b $FE, $1, $0, $14, $15
Shadow_Map_2E: dc.b $4
	dc.b $F8, $E, $0, $0, $ED
	dc.b $F0, $4, $0, $C, $F5
	dc.b $10, $4, $0, $E, $5
	dc.b $F0, $3, $0, $10, $D
Shadow_Map_2F: dc.b $4
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F0, $8, $0, $C, $FC
	dc.b $E8, $0, $0, $F, $C
	dc.b $F8, $2, $0, $10, $C
Shadow_Map_30: dc.b $3
	dc.b $EF, $F, $0, $0, $F6
	dc.b $F7, $2, $0, $10, $EE
	dc.b $F, $4, $0, $13, $6
Shadow_Map_31: dc.b $4
	dc.b $F7, $E, $0, $0, $EE
	dc.b $EF, $4, $0, $C, $F6
	dc.b $F, $C, $0, $E, $F6
	dc.b $EF, $3, $0, $12, $E
Shadow_Map_32: dc.b $3
	dc.b $F3, $E, $0, $0, $EE
	dc.b $B, $4, $0, $C, $EE
	dc.b $F3, $3, $0, $E, $E
Shadow_Map_33: dc.b $4
	dc.b $F6, $E, $0, $0, $EE
	dc.b $EE, $4, $0, $C, $F6
	dc.b $E, $4, $0, $E, $6
	dc.b $EE, $3, $0, $10, $E
Shadow_Map_34: dc.b $3
	dc.b $F4, $F, $0, $0, $EE
	dc.b $EC, $3, $0, $10, $E
	dc.b $C, $0, $0, $14, $E
Shadow_Map_35: dc.b $3
	dc.b $F1, $7, $0, $0, $EE
	dc.b $F1, $3, $0, $8, $E
	dc.b $F9, $7, $0, $C, $FE
Shadow_Map_36: dc.b $5
	dc.b $E9, $6, $0, $0, $1
	dc.b $F1, $7, $0, $6, $F1
	dc.b $F1, $1, $0, $E, $11
	dc.b $F9, $1, $0, $10, $E9
	dc.b $1, $0, $0, $12, $1
Shadow_Map_37: dc.b $4
	dc.b $E8, $E, $0, $0, $EF
	dc.b $0, $9, $0, $C, $EF
	dc.b $E0, $4, $0, $12, $F7
	dc.b $F0, $1, $0, $14, $F
Shadow_Map_38: dc.b $5
	dc.b $F4, $E, $0, $0, $EB
	dc.b $EC, $C, $0, $C, $F3
	dc.b $C, $4, $0, $10, $F3
	dc.b $E4, $0, $0, $12, $3
	dc.b $F4, $5, $0, $13, $B
Shadow_Map_39: dc.b $5
	dc.b $E9, $F, $0, $0, $EC
	dc.b $9, $4, $0, $10, $F4
	dc.b $E1, $0, $0, $12, $4
	dc.b $E9, $3, $0, $13, $C
	dc.b $F9, $0, $0, $17, $14
Shadow_Map_3A: dc.b $5
	dc.b $FF, $C, $0, $0, $E7
	dc.b $EF, $D, $0, $4, $EF
	dc.b $7, $8, $0, $C, $EF
	dc.b $E7, $4, $0, $F, $FF
	dc.b $EF, $1, $0, $11, $F
Shadow_Map_3B: dc.b $6
	dc.b $E1, $4, $0, $0, $FA
	dc.b $E9, $6, $0, $2, $2
	dc.b $F1, $7, $0, $8, $F2
	dc.b $F1, $1, $0, $10, $12
	dc.b $F9, $1, $0, $12, $EA
	dc.b $1, $0, $0, $14, $2
Shadow_Map_3C: dc.b $5
	dc.b $E1, $4, $0, $0, $FA
	dc.b $E9, $7, $0, $2, $2
	dc.b $F1, $7, $0, $A, $F2
	dc.b $F1, $1, $0, $12, $12
	dc.b $F9, $1, $0, $14, $EA
Shadow_Map_3D: dc.b $5
	dc.b $E1, $4, $0, $0, $FA
	dc.b $E9, $7, $0, $2, $2
	dc.b $F1, $7, $0, $A, $F2
	dc.b $F9, $1, $0, $12, $EA
	dc.b $F9, $1, $0, $14, $12
Shadow_Map_3E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Shadow_Map_3F: dc.b $1
	dc.b $EF, $F, $0, $0, $EF
Shadow_Map_40: dc.b $1
	dc.b $EF, $F, $0, $0, $EF
Shadow_Map_41: dc.b $1
	dc.b $F1, $F, $0, $0, $EF
Shadow_Map_42: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
Shadow_Map_43: dc.b $4
	dc.b $F4, $D, $0, $0, $EE
	dc.b $EC, $8, $0, $8, $F6
	dc.b $4, $C, $0, $B, $F6
	dc.b $C, $8, $0, $F, $FE
Shadow_Map_44: dc.b $5
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $F9, $0, $0, $10, $E8
	dc.b $ED, $1, $0, $11, $8
Shadow_Map_45: dc.b $8
	dc.b $F4, $4, $0, $0, $0
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
	dc.b $F4, $0, $0, $E, $F8
	dc.b $C, $0, $0, $F, $EC
	dc.b $C, $0, $0, $10, $C
	dc.b $FC, $0, $0, $11, $EC
Shadow_Map_46: dc.b $3
	dc.b $EC, $8, $8, $0, $E3
	dc.b $F7, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
Shadow_Map_47: dc.b $3
	dc.b $EC, $E, $8, $0, $E0
	dc.b $4, $D, $8, $C, $E0
	dc.b $5, $0, $18, $14, $0
Shadow_Map_48: dc.b $3
	dc.b $F3, $D, $0, $0, $FC
	dc.b $FB, $5, $0, $8, $EC
	dc.b $3, $8, $0, $C, $FC
Shadow_Map_49: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $0, $9, $0
Shadow_Map_4A: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
Shadow_Map_4B: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
Shadow_Map_4C: dc.b $5
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
	dc.b $10, $0, $0, $F, $0
	dc.b $F0, $0, $0, $10, $8
Shadow_Map_4D: dc.b $3
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $2, $0, $C, $8
	dc.b $FF, $5, $0, $F, $10
Shadow_Map_4E: dc.b $3
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $2, $0, $C, $8
	dc.b $FF, $5, $0, $F, $10
Shadow_Map_4F: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Shadow_Map_50: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Shadow_Map_51: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
Shadow_Map_52: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
Shadow_Map_53: dc.b $8
	dc.b $F8, $9, $0, $0, $F4
	dc.b $8, $C, $0, $6, $F4
	dc.b $10, $0, $0, $A, $F4
	dc.b $E8, $D, $0, $B, $F4
	dc.b $F0, $0, $0, $13, $EC
	dc.b $F8, $0, $0, $14, $C
	dc.b $10, $0, $0, $15, $C
	dc.b $0, $0, $0, $16, $C
Shadow_Map_54: dc.b $8
	dc.b $E9, $D, $8, $0, $FB
	dc.b $E9, $1, $8, $8, $F3
	dc.b $F9, $9, $8, $A, $FB
	dc.b $F9, $0, $8, $10, $F3
	dc.b $8, $C, $0, $11, $F4
	dc.b $10, $0, $0, $15, $F4
	dc.b $10, $0, $0, $16, $C
	dc.b $0, $0, $0, $17, $F4
Shadow_Map_55: dc.b $3
	dc.b $F3, $D, $8, $0, $E4
	dc.b $FB, $5, $8, $8, $4
	dc.b $3, $8, $8, $C, $EC
Shadow_Map_56: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
Shadow_Map_57: dc.b $3
	dc.b $F8, $E, $0, $0, $EC
	dc.b $F3, $1, $0, $C, $C
	dc.b $F0, $C, $0, $E, $EC
Shadow_Map_58: dc.b $5
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
	dc.b $4, $1, $0, $12, $B
	dc.b $FC, $0, $0, $14, $B
	dc.b $F4, $0, $0, $15, $EB
Shadow_Map_59: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F3, $1, $0, $10, $C
Shadow_Map_5A: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $F4, $8, $0, $9, $FC
	dc.b $FC, $1, $0, $C, $C
Shadow_Map_5B: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $F4, $8, $0, $9, $FC
	dc.b $FC, $1, $0, $C, $C
Shadow_Map_5C: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $F4, $8, $0, $9, $FC
	dc.b $FC, $1, $0, $C, $C
Shadow_Map_5D: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $F4, $8, $0, $9, $FC
	dc.b $FC, $1, $0, $C, $C
Shadow_Map_5E: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $FC, $1, $0, $9, $C
	dc.b $F4, $8, $0, $B, $FC
Shadow_Map_5F: dc.b $3
	dc.b $FC, $A, $0, $0, $F4
	dc.b $FC, $1, $0, $9, $C
	dc.b $F4, $8, $0, $B, $FC
Shadow_Map_60: dc.b $3
	dc.b $E8, $B, $0, $0, $EE
	dc.b $8, $5, $0, $C, $F6
	dc.b $F8, $5, $0, $10, $6
Shadow_Map_61: dc.b $5
	dc.b $FC, $C, $0, $0, $E8
	dc.b $E4, $A, $0, $4, $F0
	dc.b $C, $8, $0, $D, $F0
	dc.b $4, $4, $0, $10, $F8
	dc.b $F4, $1, $0, $12, $8
Shadow_Map_62: dc.b $4
	dc.b $E8, $E, $0, $0, $F0
	dc.b $F8, $1, $0, $C, $E8
	dc.b $0, $6, $0, $E, $F8
	dc.b $10, $0, $0, $14, $8
Shadow_Map_63: dc.b $6
	dc.b $F0, $D, $0, $0, $EC
	dc.b $E8, $8, $0, $8, $F4
	dc.b $0, $5, $0, $B, $F4
	dc.b $10, $4, $0, $F, $FC
	dc.b $8, $0, $0, $11, $4
	dc.b $F0, $1, $0, $12, $C
Shadow_Map_64: dc.b $3
	dc.b $ED, $A, $0, $0, $F1
	dc.b $5, $9, $0, $9, $F9
	dc.b $F5, $1, $0, $F, $9
Shadow_Map_65: dc.b $3
	dc.b $F4, $C, $0, $0, $EC
	dc.b $EC, $8, $0, $4, $F4
	dc.b $FC, $A, $0, $7, $F4
Shadow_Map_66: dc.b $3
	dc.b $EC, $B, $0, $0, $F4
	dc.b $F4, $0, $0, $C, $EC
	dc.b $C, $C, $0, $D, $F4
Shadow_Map_67: dc.b $3
	dc.b $F4, $C, $0, $0, $EC
	dc.b $EC, $8, $0, $4, $F4
	dc.b $FC, $A, $0, $7, $F4
Shadow_Map_68: dc.b $3
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $A, $0, $8, $F5
	dc.b $E4, $0, $0, $11, $FD
Shadow_Map_69: dc.b $2
	dc.b $EC, $B, $0, $0, $F6
	dc.b $C, $8, $0, $C, $F8
Shadow_Map_6A: dc.b $7
	dc.b $C, $8, $0, $0, $F9
	dc.b $4, $0, $0, $3, $4
	dc.b $4, $0, $0, $4, $FC
	dc.b $4, $0, $0, $5, $F4
	dc.b $EC, $2, $0, $6, $F6
	dc.b $EC, $2, $0, $9, $FE
	dc.b $EC, $2, $0, $C, $6
	even