; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 29 2018 11:32:53 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAYD92TJL1PZ:
	dc.w DATAYD92TJL1PZ_0-DATAYD92TJL1PZ
DATAYD92TJL1PZ_0: dc.b $2
	dc.b $F0, $F, $0, $0, $E8
	dc.b $F0, $7, $0, $10, $8
	even