; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Apr 07 2018 23:00:31 GMT-0400 (Eastern Daylight Time)
; ================================================================================

Sonic_Map:
	dc.w $0, Sonic_Map_1-Sonic_Map
	dc.w Sonic_Map_2-Sonic_Map, Sonic_Map_3-Sonic_Map
	dc.w Sonic_Map_4-Sonic_Map, Sonic_Map_5-Sonic_Map
	dc.w Sonic_Map_6-Sonic_Map, Sonic_Map_7-Sonic_Map
	dc.w Sonic_Map_8-Sonic_Map, Sonic_Map_9-Sonic_Map
	dc.w Sonic_Map_A-Sonic_Map, Sonic_Map_B-Sonic_Map
	dc.w Sonic_Map_C-Sonic_Map, Sonic_Map_D-Sonic_Map
	dc.w Sonic_Map_E-Sonic_Map, Sonic_Map_F-Sonic_Map
	dc.w Sonic_Map_10-Sonic_Map, Sonic_Map_11-Sonic_Map
	dc.w Sonic_Map_12-Sonic_Map, Sonic_Map_13-Sonic_Map
	dc.w Sonic_Map_14-Sonic_Map, Sonic_Map_15-Sonic_Map
	dc.w Sonic_Map_16-Sonic_Map, Sonic_Map_17-Sonic_Map
	dc.w Sonic_Map_18-Sonic_Map, Sonic_Map_19-Sonic_Map
	dc.w Sonic_Map_1A-Sonic_Map, Sonic_Map_1B-Sonic_Map
	dc.w Sonic_Map_1C-Sonic_Map, Sonic_Map_1D-Sonic_Map
	dc.w Sonic_Map_1E-Sonic_Map, Sonic_Map_1F-Sonic_Map
	dc.w Sonic_Map_20-Sonic_Map, Sonic_Map_21-Sonic_Map
	dc.w Sonic_Map_22-Sonic_Map, Sonic_Map_23-Sonic_Map
	dc.w Sonic_Map_24-Sonic_Map, Sonic_Map_25-Sonic_Map
	dc.w Sonic_Map_26-Sonic_Map, Sonic_Map_27-Sonic_Map
	dc.w Sonic_Map_28-Sonic_Map, Sonic_Map_29-Sonic_Map
	dc.w Sonic_Map_2A-Sonic_Map, Sonic_Map_2B-Sonic_Map
	dc.w Sonic_Map_2C-Sonic_Map, Sonic_Map_2D-Sonic_Map
	dc.w Sonic_Map_2E-Sonic_Map, Sonic_Map_2F-Sonic_Map
	dc.w Sonic_Map_30-Sonic_Map, Sonic_Map_31-Sonic_Map
	dc.w Sonic_Map_32-Sonic_Map, Sonic_Map_33-Sonic_Map
	dc.w Sonic_Map_34-Sonic_Map, Sonic_Map_35-Sonic_Map
	dc.w Sonic_Map_36-Sonic_Map, Sonic_Map_37-Sonic_Map
	dc.w Sonic_Map_38-Sonic_Map, Sonic_Map_39-Sonic_Map
	dc.w Sonic_Map_3A-Sonic_Map, Sonic_Map_3B-Sonic_Map
	dc.w Sonic_Map_3C-Sonic_Map, Sonic_Map_3D-Sonic_Map
	dc.w Sonic_Map_3E-Sonic_Map, Sonic_Map_3F-Sonic_Map
	dc.w Sonic_Map_40-Sonic_Map, Sonic_Map_41-Sonic_Map
	dc.w Sonic_Map_42-Sonic_Map, Sonic_Map_43-Sonic_Map
	dc.w Sonic_Map_44-Sonic_Map, Sonic_Map_45-Sonic_Map
	dc.w Sonic_Map_46-Sonic_Map, Sonic_Map_47-Sonic_Map
	dc.w Sonic_Map_48-Sonic_Map, $0
	dc.w Sonic_Map_4A-Sonic_Map, Sonic_Map_4B-Sonic_Map
	dc.w Sonic_Map_4C-Sonic_Map, Sonic_Map_4D-Sonic_Map
	dc.w Sonic_Map_4E-Sonic_Map, Sonic_Map_4F-Sonic_Map
	dc.w Sonic_Map_50-Sonic_Map, Sonic_Map_51-Sonic_Map
	dc.w Sonic_Map_52-Sonic_Map, Sonic_Map_53-Sonic_Map
	dc.w Sonic_Map_54-Sonic_Map, Sonic_Map_55-Sonic_Map
	dc.w Sonic_Map_56-Sonic_Map, Sonic_Map_57-Sonic_Map
	dc.w Sonic_Map_58-Sonic_Map, Sonic_Map_59-Sonic_Map
	dc.w Sonic_Map_5A-Sonic_Map, Sonic_Map_5B-Sonic_Map
	dc.w Sonic_Map_5C-Sonic_Map, Sonic_Map_5D-Sonic_Map
	dc.w Sonic_Map_5E-Sonic_Map, Sonic_Map_5F-Sonic_Map
	dc.w Sonic_Map_60-Sonic_Map, Sonic_Map_61-Sonic_Map
	dc.w Sonic_Map_62-Sonic_Map, Sonic_Map_63-Sonic_Map
	dc.w Sonic_Map_64-Sonic_Map, Sonic_Map_65-Sonic_Map
	dc.w Sonic_Map_66-Sonic_Map, Sonic_Map_67-Sonic_Map
	dc.w Sonic_Map_68-Sonic_Map, Sonic_Map_69-Sonic_Map
	dc.w Sonic_Map_6A-Sonic_Map, Sonic_Map_6B-Sonic_Map
	dc.w Sonic_Map_6C-Sonic_Map, Sonic_Map_6D-Sonic_Map
	dc.w Sonic_Map_6E-Sonic_Map, Sonic_Map_6F-Sonic_Map
	dc.w Sonic_Map_70-Sonic_Map, Sonic_Map_71-Sonic_Map
	dc.w Sonic_Map_72-Sonic_Map, Sonic_Map_73-Sonic_Map
	dc.w Sonic_Map_74-Sonic_Map, Sonic_Map_75-Sonic_Map
	dc.w Sonic_Map_76-Sonic_Map, Sonic_Map_77-Sonic_Map
	dc.w Sonic_Map_78-Sonic_Map, Sonic_Map_79-Sonic_Map
	dc.w Sonic_Map_7A-Sonic_Map, Sonic_Map_7B-Sonic_Map
	dc.w Sonic_Map_7C-Sonic_Map, Sonic_Map_7D-Sonic_Map
	dc.w Sonic_Map_7E-Sonic_Map, Sonic_Map_7F-Sonic_Map
	dc.w Sonic_Map_80-Sonic_Map, Sonic_Map_81-Sonic_Map
	dc.w Sonic_Map_82-Sonic_Map, Sonic_Map_83-Sonic_Map
	dc.w Sonic_Map_84-Sonic_Map, Sonic_Map_85-Sonic_Map
	dc.w Sonic_Map_86-Sonic_Map, Sonic_Map_87-Sonic_Map
	dc.w Sonic_Map_88-Sonic_Map
Sonic_Map_1: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FC, $2, $0, $10, $D
	dc.b $C, $4, $0, $13, $ED
	dc.b $C, $0, $0, $15, $5
Sonic_Map_2: dc.b $4
	dc.b $ED, $D, $0, $0, $ED
	dc.b $FD, $A, $0, $8, $F5
	dc.b $5, $1, $0, $11, $ED
	dc.b $5, $1, $0, $13, $D
Sonic_Map_3: dc.b $2
	dc.b $EE, $D, $0, $0, $F2
	dc.b $FE, $A, $0, $8, $F2
Sonic_Map_4: dc.b $3
	dc.b $EC, $B, $0, $0, $F2
	dc.b $F4, $3, $0, $C, $A
	dc.b $C, $8, $0, $10, $F2
Sonic_Map_5: dc.b $4
	dc.b $EC, $F, $0, $0, $EE
	dc.b $FC, $1, $0, $10, $E
	dc.b $C, $4, $0, $12, $EE
	dc.b $C, $0, $0, $14, $6
Sonic_Map_6: dc.b $5
	dc.b $ED, $D, $0, $0, $EE
	dc.b $FD, $9, $0, $8, $F6
	dc.b $5, $1, $0, $E, $EE
	dc.b $5, $1, $0, $10, $E
	dc.b $D, $0, $0, $12, $6
Sonic_Map_7: dc.b $2
	dc.b $EE, $D, $0, $0, $F2
	dc.b $FE, $A, $0, $8, $F2
Sonic_Map_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F2
	dc.b $F4, $0, $0, $C, $A
	dc.b $C, $C, $0, $D, $F2
Sonic_Map_9: dc.b $4
	dc.b $F0, $E, $0, $0, $EB
	dc.b $F0, $2, $0, $C, $B
	dc.b $8, $8, $0, $F, $F3
	dc.b $10, $5, $0, $12, $FB
Sonic_Map_A: dc.b $4
	dc.b $F2, $E, $0, $0, $ED
	dc.b $FA, $5, $0, $C, $D
	dc.b $A, $8, $0, $10, $FD
	dc.b $12, $0, $0, $13, $FD
Sonic_Map_B: dc.b $3
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $C, $0, $C, $F7
	dc.b $D, $4, $0, $10, $7
Sonic_Map_C: dc.b $4
	dc.b $ED, $E, $0, $0, $ED
	dc.b $FD, $5, $0, $C, $D
	dc.b $5, $8, $0, $10, $F5
	dc.b $D, $8, $0, $13, $FD
Sonic_Map_D: dc.b $4
	dc.b $EE, $F, $0, $0, $ED
	dc.b $F6, $2, $0, $10, $D
	dc.b $E, $8, $0, $13, $ED
	dc.b $16, $4, $0, $16, $FD
Sonic_Map_E: dc.b $4
	dc.b $ED, $A, $0, $0, $ED
	dc.b $F5, $A, $0, $9, $5
	dc.b $5, $5, $0, $12, $F5
	dc.b $15, $0, $0, $16, $FD
Sonic_Map_F: dc.b $3
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $C, $0, $C, $F4
	dc.b $11, $4, $0, $10, $FC
Sonic_Map_10: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $2, $2, $0, $C, $C
	dc.b $A, $5, $0, $F, $FC
Sonic_Map_11: dc.b $5
	dc.b $ED, $9, $0, $0, $FC
	dc.b $F5, $7, $0, $6, $EC
	dc.b $FD, $5, $0, $E, $FC
	dc.b $5, $1, $0, $12, $C
	dc.b $D, $0, $0, $14, $4
Sonic_Map_12: dc.b $5
	dc.b $ED, $5, $0, $0, $5
	dc.b $F5, $A, $0, $4, $ED
	dc.b $FD, $2, $0, $D, $5
	dc.b $5, $1, $0, $10, $D
	dc.b $D, $4, $0, $12, $ED
Sonic_Map_13: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $F5, $2, $0, $C, $E
	dc.b $D, $0, $0, $F, $F6
Sonic_Map_14: dc.b $2
	dc.b $F3, $F, $0, $0, $EC
	dc.b $F3, $3, $0, $10, $C
Sonic_Map_15: dc.b $5
	dc.b $EE, $D, $0, $0, $F4
	dc.b $F6, $2, $0, $8, $EC
	dc.b $FE, $9, $0, $B, $F4
	dc.b $6, $1, $0, $11, $C
	dc.b $E, $4, $0, $13, $FC
Sonic_Map_16: dc.b $6
	dc.b $ED, $9, $0, $0, $FD
	dc.b $F5, $6, $0, $6, $ED
	dc.b $FD, $5, $0, $C, $FD
	dc.b $5, $1, $0, $10, $D
	dc.b $D, $0, $0, $12, $F5
	dc.b $D, $0, $0, $13, $5
Sonic_Map_17: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $F5, $2, $0, $C, $E
	dc.b $D, $0, $0, $F, $F6
Sonic_Map_18: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
	dc.b $D, $4, $0, $F, $EC
Sonic_Map_19: dc.b $4
	dc.b $EF, $B, $0, $0, $F1
	dc.b $F7, $9, $0, $C, $9
	dc.b $7, $0, $0, $12, $9
	dc.b $F, $8, $0, $13, $F1
Sonic_Map_1A: dc.b $5
	dc.b $EA, $8, $0, $0, $F8
	dc.b $F2, $7, $0, $3, $F8
	dc.b $FA, $3, $0, $B, $F0
	dc.b $FA, $5, $0, $F, $8
	dc.b $12, $0, $0, $13, $F8
Sonic_Map_1B: dc.b $3
	dc.b $EF, $5, $0, $0, $7
	dc.b $F7, $B, $0, $4, $EF
	dc.b $FF, $1, $0, $10, $7
Sonic_Map_1C: dc.b $6
	dc.b $ED, $7, $0, $0, $0
	dc.b $F5, $3, $0, $8, $F8
	dc.b $F5, $1, $0, $C, $10
	dc.b $FD, $2, $0, $E, $F0
	dc.b $D, $0, $0, $11, $0
	dc.b $15, $0, $0, $12, $F8
Sonic_Map_1D: dc.b $4
	dc.b $EE, $F, $0, $0, $EF
	dc.b $F6, $1, $0, $10, $17
	dc.b $FE, $1, $0, $12, $F
	dc.b $E, $C, $0, $14, $EF
Sonic_Map_1E: dc.b $5
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $7, $0, $3, $F8
	dc.b $FC, $2, $0, $B, $F0
	dc.b $FC, $9, $0, $E, $8
	dc.b $14, $0, $0, $14, $F8
Sonic_Map_1F: dc.b $3
	dc.b $EF, $5, $0, $0, $8
	dc.b $F7, $B, $0, $4, $F0
	dc.b $FF, $1, $0, $10, $8
Sonic_Map_20: dc.b $3
	dc.b $EE, $A, $0, $0, $2
	dc.b $F6, $7, $0, $9, $F2
	dc.b $6, $1, $0, $11, $2
Sonic_Map_21: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $C, $0, $10, $F0
Sonic_Map_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $3, $0, $C, $F0
	dc.b $10, $8, $0, $10, $F8
Sonic_Map_23: dc.b $2
	dc.b $F0, $F, $0, $0, $F1
	dc.b $10, $8, $0, $10, $F1
Sonic_Map_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $3, $0, $C, $F0
	dc.b $10, $8, $0, $10, $F8
Sonic_Map_25: dc.b $3
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $1, $0, $C, $D
	dc.b $7, $9, $0, $E, $F5
Sonic_Map_26: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $3, $0, $C, $8
	dc.b $E, $8, $0, $10, $F0
Sonic_Map_27: dc.b $3
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $1, $0, $C, $D
	dc.b $7, $9, $0, $E, $F5
Sonic_Map_28: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $3, $0, $C, $8
	dc.b $E, $8, $0, $10, $F0
Sonic_Map_29: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $F0, $3, $0, $10, $10
Sonic_Map_2A: dc.b $3
	dc.b $F0, $E, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $10
	dc.b $8, $8, $0, $10, $F8
Sonic_Map_2B: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $F0, $3, $0, $10, $10
Sonic_Map_2C: dc.b $3
	dc.b $F0, $E, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $10
	dc.b $8, $8, $0, $10, $F8
Sonic_Map_2D: dc.b $3
	dc.b $EE, $F, $0, $0, $F6
	dc.b $F6, $2, $0, $10, $EE
	dc.b $E, $0, $0, $13, $F6
Sonic_Map_2E: dc.b $2
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
Sonic_Map_2F: dc.b $4
	dc.b $EF, $E, $0, $0, $EE
	dc.b $EF, $2, $0, $C, $E
	dc.b $7, $8, $0, $F, $EE
	dc.b $F, $0, $0, $12, $F6
Sonic_Map_30: dc.b $2
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
Sonic_Map_31: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_32: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_33: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_34: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_35: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_36: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
Sonic_Map_37: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $F0, $2, $0, $C, $D
	dc.b $8, $8, $0, $F, $F5
Sonic_Map_38: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $8, $0, $F, $F4
Sonic_Map_39: dc.b $2
	dc.b $EB, $A, $0, $0, $F1
	dc.b $3, $6, $0, $9, $F9
Sonic_Map_3A: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Sonic_Map_3B: dc.b $2
	dc.b $F1, $E, $0, $0, $F1
	dc.b $9, $8, $0, $C, $F1
Sonic_Map_3C: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Sonic_Map_3D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Sonic_Map_3E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
Sonic_Map_3F: dc.b $2
	dc.b $F2, $B, $0, $0, $F8
	dc.b $12, $8, $0, $C, $F8
Sonic_Map_40: dc.b $2
	dc.b $FA, $B, $0, $0, $F7
	dc.b $2, $1, $0, $C, $F
Sonic_Map_41: dc.b $4
	dc.b $EE, $B, $0, $0, $F5
	dc.b $F6, $1, $0, $C, $ED
	dc.b $FE, $2, $0, $E, $D
	dc.b $E, $4, $0, $11, $FD
Sonic_Map_42: dc.b $4
	dc.b $EE, $B, $0, $0, $F6
	dc.b $F6, $1, $0, $C, $EE
	dc.b $FE, $1, $0, $E, $E
	dc.b $E, $4, $0, $10, $FE
Sonic_Map_43: dc.b $3
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $1, $0, $C, $F1
	dc.b $F, $4, $0, $E, $1
Sonic_Map_44: dc.b $4
	dc.b $EB, $A, $0, $0, $ED
	dc.b $3, $9, $0, $9, $F5
	dc.b $F3, $1, $0, $F, $5
	dc.b $B, $1, $0, $11, $D
Sonic_Map_45: dc.b $3
	dc.b $EC, $D, $0, $0, $EB
	dc.b $EC, $0, $0, $8, $B
	dc.b $FC, $A, $0, $9, $EB
Sonic_Map_46: dc.b $5
	dc.b $EA, $E, $0, $0, $EA
	dc.b $FA, $0, $0, $C, $A
	dc.b $2, $8, $0, $D, $F2
	dc.b $A, $8, $0, $10, $EA
	dc.b $12, $4, $0, $13, $F2
Sonic_Map_47: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $F2, $2, $0, $9, $3
	dc.b $2, $6, $0, $C, $F3
	dc.b $A, $0, $0, $12, $EB
Sonic_Map_48: dc.b $4
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $3, $0, $C, $F0
	dc.b $F4, $0, $0, $10, $10
	dc.b $C, $8, $0, $11, $F8
Sonic_Map_4A: dc.b $3
	dc.b $EE, $F, $0, $0, $F0
	dc.b $F6, $0, $0, $10, $10
	dc.b $E, $C, $0, $11, $F0
Sonic_Map_4B: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
Sonic_Map_4C: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
Sonic_Map_4D: dc.b $3
	dc.b $EC, $F, $0, $0, $EF
	dc.b $4, $0, $0, $10, $F
	dc.b $C, $C, $0, $11, $EF
Sonic_Map_4E: dc.b $5
	dc.b $ED, $A, $0, $0, $EE
	dc.b $5, $0, $0, $9, $F6
	dc.b $F5, $0, $0, $A, $6
	dc.b $5, $0, $0, $B, $FE
	dc.b $D, $8, $0, $C, $F6
Sonic_Map_4F: dc.b $5
	dc.b $F5, $0, $0, $0, $6
	dc.b $ED, $A, $0, $1, $EE
	dc.b $5, $0, $0, $A, $FE
	dc.b $5, $0, $0, $B, $F6
	dc.b $D, $8, $0, $C, $F6
Sonic_Map_50: dc.b $3
	dc.b $EE, $B, $0, $0, $ED
	dc.b $F6, $2, $0, $C, $5
	dc.b $D, $8, $0, $F, $F6
Sonic_Map_51: dc.b $4
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $0, $0, $C, $F1
	dc.b $7, $1, $0, $D, $F1
	dc.b $F, $8, $0, $F, $F9
Sonic_Map_52: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
Sonic_Map_53: dc.b $4
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $0, $0, $C, $F1
	dc.b $7, $1, $0, $D, $F1
	dc.b $F, $4, $0, $F, $F9
Sonic_Map_54: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
Sonic_Map_55: dc.b $3
	dc.b $ED, $A, $0, $0, $F0
	dc.b $F5, $3, $0, $9, $8
	dc.b $5, $5, $0, $D, $F8
Sonic_Map_56: dc.b $5
	dc.b $ED, $B, $0, $0, $EF
	dc.b $D, $0, $0, $C, $F8
	dc.b $D, $0, $0, $D, $8
	dc.b $D, $0, $0, $E, $0
	dc.b $F5, $0, $0, $F, $7
Sonic_Map_57: dc.b $A
	dc.b $FD, $0, $0, $0, $FE
	dc.b $F5, $0, $0, $1, $FE
	dc.b $D, $8, $0, $2, $F6
	dc.b $F5, $0, $0, $5, $6
	dc.b $ED, $3, $0, $6, $EE
	dc.b $ED, $1, $0, $A, $F6
	dc.b $FD, $0, $0, $C, $F6
	dc.b $5, $0, $0, $D, $F6
	dc.b $5, $0, $0, $E, $FE
	dc.b $ED, $0, $0, $F, $FE
Sonic_Map_58: dc.b $3
	dc.b $ED, $B, $0, $0, $EE
	dc.b $D, $8, $0, $C, $F6
	dc.b $F5, $0, $0, $F, $6
Sonic_Map_59: dc.b $7
	dc.b $F5, $0, $0, $0, $6
	dc.b $5, $0, $0, $1, $6
	dc.b $5, $0, $0, $2, $FE
	dc.b $D, $0, $0, $3, $6
	dc.b $D, $4, $0, $4, $F6
	dc.b $ED, $7, $0, $6, $EE
	dc.b $ED, $2, $0, $E, $FE
Sonic_Map_5A: dc.b $3
	dc.b $EC, $A, $0, $0, $ED
	dc.b $F4, $3, $0, $9, $5
	dc.b $4, $5, $0, $D, $F5
Sonic_Map_5B: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $9, $0, $C, $F2
	dc.b $E, $0, $0, $12, $A
Sonic_Map_5C: dc.b $3
	dc.b $F4, $A, $8, $0, $FB
	dc.b $FC, $5, $8, $9, $EB
	dc.b $4, $0, $8, $D, $E3
Sonic_Map_5D: dc.b $3
	dc.b $F4, $A, $8, $0, $F4
	dc.b $4, $0, $8, $9, $C
	dc.b $4, $0, $8, $A, $EC
Sonic_Map_5E: dc.b $2
	dc.b $F4, $A, $0, $0, $F2
	dc.b $4, $0, $0, $9, $A
Sonic_Map_5F: dc.b $3
	dc.b $F4, $A, $0, $0, $F3
	dc.b $4, $0, $0, $9, $EB
	dc.b $4, $0, $0, $A, $B
Sonic_Map_60: dc.b $3
	dc.b $F4, $A, $0, $0, $EE
	dc.b $FC, $5, $0, $9, $6
	dc.b $4, $0, $0, $D, $16
Sonic_Map_61: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $4, $0, $0, $C, $10
Sonic_Map_62: dc.b $2
	dc.b $F4, $A, $0, $0, $F2
	dc.b $4, $0, $0, $9, $A
Sonic_Map_63: dc.b $2
	dc.b $F4, $E, $8, $0, $F1
	dc.b $4, $0, $8, $C, $E9
Sonic_Map_64: dc.b $3
	dc.b $F4, $E, $0, $0, $E9
	dc.b $F4, $2, $0, $C, $9
	dc.b $C, $8, $0, $F, $F1
Sonic_Map_65: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $C, $8, $0, $F, $F0
Sonic_Map_66: dc.b $5
	dc.b $EE, $A, $0, $0, $EC
	dc.b $F6, $3, $0, $9, $4
	dc.b $FE, $0, $0, $D, $C
	dc.b $6, $5, $0, $E, $F4
	dc.b $E, $0, $0, $12, $C
Sonic_Map_67: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $4, $0, $C, $F4
	dc.b $F2, $0, $0, $E, $C
	dc.b $14, $0, $0, $F, $F5
Sonic_Map_68: dc.b $4
	dc.b $FC, $E, $0, $0, $F0
	dc.b $14, $0, $0, $C, $1
	dc.b $F7, $0, $0, $D, $10
	dc.b $EC, $9, $0, $E, $F8
Sonic_Map_69: dc.b $3
	dc.b $F0, $B, $0, $0, $EC
	dc.b $F8, $2, $0, $C, $4
	dc.b $F8, $2, $0, $F, $C
Sonic_Map_6A: dc.b $2
	dc.b $F1, $F, $0, $0, $F2
	dc.b $11, $C, $0, $10, $F2
Sonic_Map_6B: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $4, $0, $10, $F8
Sonic_Map_6C: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $4, $0, $10, $F8
Sonic_Map_6D: dc.b $3
	dc.b $EC, $A, $0, $0, $EF
	dc.b $4, $6, $0, $9, $F7
	dc.b $F4, $1, $0, $F, $7
Sonic_Map_6E: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F8
	dc.b $F8, $1, $0, $10, $8
Sonic_Map_6F: dc.b $8
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F0, $2, $0, $D, $F0
	dc.b $E8, $0, $0, $10, $F8
	dc.b $E8, $0, $0, $11, $F0
Sonic_Map_70: dc.b $9
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F8, $1, $0, $D, $F0
	dc.b $E8, $0, $0, $F, $F0
	dc.b $F0, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
Sonic_Map_71: dc.b $4
	dc.b $F0, $D, $0, $0, $EE
	dc.b $E8, $8, $0, $8, $F6
	dc.b $F0, $0, $0, $B, $E
	dc.b $FF, $6, $0, $C, $F7
Sonic_Map_72: dc.b $4
	dc.b $E7, $A, $0, $0, $F7
	dc.b $EF, $0, $0, $9, $EF
	dc.b $EF, $0, $0, $A, $F
	dc.b $FF, $6, $0, $B, $F7
Sonic_Map_73: dc.b $3
	dc.b $F4, $D, $0, $0, $EE
	dc.b $EC, $4, $0, $8, $F6
	dc.b $4, $9, $0, $A, $F6
Sonic_Map_74: dc.b $3
	dc.b $FC, $E, $0, $0, $EF
	dc.b $EC, $9, $0, $C, $F7
	dc.b $FC, $0, $0, $12, $F
Sonic_Map_75: dc.b $3
	dc.b $FC, $E, $0, $0, $EF
	dc.b $EC, $9, $0, $C, $F7
	dc.b $FC, $0, $0, $12, $F
Sonic_Map_76: dc.b $3
	dc.b $FC, $E, $0, $0, $EF
	dc.b $FC, $0, $0, $C, $F
	dc.b $EC, $9, $0, $D, $F7
Sonic_Map_77: dc.b $3
	dc.b $FC, $E, $0, $0, $EF
	dc.b $FC, $0, $0, $C, $F
	dc.b $EC, $9, $0, $D, $F7
Sonic_Map_78: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $0, $0, $C, $E8
	dc.b $F8, $3, $0, $D, $8
	dc.b $10, $4, $0, $11, $F8
Sonic_Map_79: dc.b $3
	dc.b $F5, $C, $0, $0, $E9
	dc.b $ED, $8, $0, $4, $F1
	dc.b $FD, $E, $0, $7, $F1
Sonic_Map_7A: dc.b $2
	dc.b $F0, $F, $0, $0, $EF
	dc.b $10, $C, $0, $10, $EF
Sonic_Map_7B: dc.b $3
	dc.b $F0, $F, $0, $0, $EF
	dc.b $F8, $0, $0, $10, $E7
	dc.b $10, $8, $0, $11, $F7
Sonic_Map_7C: dc.b $4
	dc.b $F1, $E, $0, $0, $EC
	dc.b $E9, $0, $0, $C, $FC
	dc.b $9, $8, $0, $D, $FC
	dc.b $F1, $2, $0, $10, $C
Sonic_Map_7D: dc.b $4
	dc.b $F2, $E, $0, $0, $F0
	dc.b $EA, $0, $0, $C, $F8
	dc.b $A, $8, $0, $D, $F8
	dc.b $F2, $2, $0, $10, $10
Sonic_Map_7E: dc.b $4
	dc.b $F1, $E, $0, $0, $F0
	dc.b $9, $C, $0, $C, $F8
	dc.b $F9, $1, $0, $10, $10
	dc.b $E9, $0, $0, $12, $FC
Sonic_Map_7F: dc.b $4
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $8, $0, $C, $FC
	dc.b $F1, $2, $0, $F, $C
	dc.b $E9, $0, $0, $12, $FC
Sonic_Map_80: dc.b $4
	dc.b $F7, $E, $0, $0, $EF
	dc.b $EF, $C, $0, $C, $F7
	dc.b $F, $0, $0, $10, $F7
	dc.b $F7, $1, $0, $11, $F
Sonic_Map_81: dc.b $3
	dc.b $EE, $B, $0, $0, $FD
	dc.b $F6, $6, $0, $C, $ED
	dc.b $E, $0, $0, $12, $F5
Sonic_Map_82: dc.b $2
	dc.b $F1, $F, $0, $0, $EF
	dc.b $F1, $3, $0, $10, $F
Sonic_Map_83: dc.b $3
	dc.b $F0, $F, $0, $0, $EF
	dc.b $10, $0, $0, $10, $F7
	dc.b $F0, $2, $0, $11, $F
Sonic_Map_84: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
Sonic_Map_85: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $9, $0, $C, $F4
	dc.b $F8, $0, $0, $12, $C
Sonic_Map_86: dc.b $5
	dc.b $E8, $B, $0, $0, $F4
	dc.b $F0, $0, $0, $C, $EC
	dc.b $0, $0, $0, $D, $EC
	dc.b $0, $0, $0, $E, $C
	dc.b $8, $9, $0, $F, $F4
Sonic_Map_87: dc.b $7
	dc.b $F0, $0, $0, $0, $EC
	dc.b $0, $0, $0, $1, $EC
	dc.b $0, $0, $0, $2, $C
	dc.b $8, $9, $0, $3, $F4
	dc.b $E8, $7, $0, $9, $F4
	dc.b $E8, $0, $0, $11, $4
	dc.b $F0, $2, $0, $12, $4
Sonic_Map_88: dc.b $7
	dc.b $F0, $0, $0, $0, $EC
	dc.b $0, $0, $0, $1, $EC
	dc.b $0, $0, $0, $2, $C
	dc.b $8, $9, $0, $3, $F4
	dc.b $E8, $7, $0, $9, $F4
	dc.b $F0, $2, $0, $11, $4
	dc.b $E8, $0, $0, $14, $4
	even